// Generated by clientipc/internal/dartmetadata. Do not edit.
/// Exact producer identity for bootstrap and every subsequent v0 RPC.
abstract final class ClientContract {
  static const protocol = 'endlessnet-client-ipc';
  static const version = 0;
  static const sha256 = 'ffc4b4a2edf94e18fec83a66aa441a7a80c69647a4d453ee48c191d015251cfe';
  static const metadata = <String, String>{
    'x-endlessnet-ipc-protocol': protocol,
    'x-endlessnet-ipc-version': '0',
    'x-endlessnet-ipc-contract-sha256': sha256,
  };
}
