// Accepted producer-owned IPC v0 contract. Not yet served by the runtime.
// See docs/client-ipc-protobuf.md for normative semantics and adoption gates.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: client/v0/common.proto

package clientipc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Access int32

const (
	Access_ACCESS_UNSPECIFIED   Access = 0
	Access_ACCESS_OBSERVER      Access = 1
	Access_ACCESS_OWNER         Access = 2
	Access_ACCESS_ADMINISTRATOR Access = 3
)

// Enum value maps for Access.
var (
	Access_name = map[int32]string{
		0: "ACCESS_UNSPECIFIED",
		1: "ACCESS_OBSERVER",
		2: "ACCESS_OWNER",
		3: "ACCESS_ADMINISTRATOR",
	}
	Access_value = map[string]int32{
		"ACCESS_UNSPECIFIED":   0,
		"ACCESS_OBSERVER":      1,
		"ACCESS_OWNER":         2,
		"ACCESS_ADMINISTRATOR": 3,
	}
)

func (x Access) Enum() *Access {
	p := new(Access)
	*p = x
	return p
}

func (x Access) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Access) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[0].Descriptor()
}

func (Access) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[0]
}

func (x Access) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Access.Descriptor instead.
func (Access) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{0}
}

type Platform int32

const (
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	Platform_PLATFORM_WINDOWS     Platform = 1
	Platform_PLATFORM_MACOS       Platform = 2
	Platform_PLATFORM_LINUX       Platform = 3
	Platform_PLATFORM_ANDROID     Platform = 4
	Platform_PLATFORM_IOS         Platform = 5
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_WINDOWS",
		2: "PLATFORM_MACOS",
		3: "PLATFORM_LINUX",
		4: "PLATFORM_ANDROID",
		5: "PLATFORM_IOS",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"PLATFORM_WINDOWS":     1,
		"PLATFORM_MACOS":       2,
		"PLATFORM_LINUX":       3,
		"PLATFORM_ANDROID":     4,
		"PLATFORM_IOS":         5,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[1].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[1]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{1}
}

type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED       Capability = 0
	Capability_CAPABILITY_ENROLLMENT        Capability = 1
	Capability_CAPABILITY_CONNECTION        Capability = 2
	Capability_CAPABILITY_PEERS             Capability = 3
	Capability_CAPABILITY_NETWORK_SELECTION Capability = 4
	Capability_CAPABILITY_EXIT_NODE         Capability = 5
	Capability_CAPABILITY_IDENTITY_RECOVERY Capability = 6
	Capability_CAPABILITY_DIAGNOSTICS       Capability = 7
	Capability_CAPABILITY_LOGOUT            Capability = 8
	Capability_CAPABILITY_LOCAL_FORGET      Capability = 9
	Capability_CAPABILITY_PROFILES          Capability = 10
	Capability_CAPABILITY_SESSION_RENEWAL   Capability = 11
	Capability_CAPABILITY_PREFERENCES       Capability = 12
	Capability_CAPABILITY_RESOURCES         Capability = 13
	Capability_CAPABILITY_MANAGED_SETTINGS  Capability = 14
	Capability_CAPABILITY_RUNTIME_LIFECYCLE Capability = 15
	Capability_CAPABILITY_UPDATE_DISCOVERY  Capability = 16
	Capability_CAPABILITY_SUPPORT_INFO      Capability = 17
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0:  "CAPABILITY_UNSPECIFIED",
		1:  "CAPABILITY_ENROLLMENT",
		2:  "CAPABILITY_CONNECTION",
		3:  "CAPABILITY_PEERS",
		4:  "CAPABILITY_NETWORK_SELECTION",
		5:  "CAPABILITY_EXIT_NODE",
		6:  "CAPABILITY_IDENTITY_RECOVERY",
		7:  "CAPABILITY_DIAGNOSTICS",
		8:  "CAPABILITY_LOGOUT",
		9:  "CAPABILITY_LOCAL_FORGET",
		10: "CAPABILITY_PROFILES",
		11: "CAPABILITY_SESSION_RENEWAL",
		12: "CAPABILITY_PREFERENCES",
		13: "CAPABILITY_RESOURCES",
		14: "CAPABILITY_MANAGED_SETTINGS",
		15: "CAPABILITY_RUNTIME_LIFECYCLE",
		16: "CAPABILITY_UPDATE_DISCOVERY",
		17: "CAPABILITY_SUPPORT_INFO",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":       0,
		"CAPABILITY_ENROLLMENT":        1,
		"CAPABILITY_CONNECTION":        2,
		"CAPABILITY_PEERS":             3,
		"CAPABILITY_NETWORK_SELECTION": 4,
		"CAPABILITY_EXIT_NODE":         5,
		"CAPABILITY_IDENTITY_RECOVERY": 6,
		"CAPABILITY_DIAGNOSTICS":       7,
		"CAPABILITY_LOGOUT":            8,
		"CAPABILITY_LOCAL_FORGET":      9,
		"CAPABILITY_PROFILES":          10,
		"CAPABILITY_SESSION_RENEWAL":   11,
		"CAPABILITY_PREFERENCES":       12,
		"CAPABILITY_RESOURCES":         13,
		"CAPABILITY_MANAGED_SETTINGS":  14,
		"CAPABILITY_RUNTIME_LIFECYCLE": 15,
		"CAPABILITY_UPDATE_DISCOVERY":  16,
		"CAPABILITY_SUPPORT_INFO":      17,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[2].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[2]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{2}
}

type Availability int32

const (
	Availability_AVAILABILITY_UNSPECIFIED             Availability = 0
	Availability_AVAILABILITY_AVAILABLE               Availability = 1
	Availability_AVAILABILITY_UNSUPPORTED             Availability = 2
	Availability_AVAILABILITY_POLICY_BLOCKED          Availability = 3
	Availability_AVAILABILITY_PERMISSION_REQUIRED     Availability = 4
	Availability_AVAILABILITY_TEMPORARILY_UNAVAILABLE Availability = 5
)

// Enum value maps for Availability.
var (
	Availability_name = map[int32]string{
		0: "AVAILABILITY_UNSPECIFIED",
		1: "AVAILABILITY_AVAILABLE",
		2: "AVAILABILITY_UNSUPPORTED",
		3: "AVAILABILITY_POLICY_BLOCKED",
		4: "AVAILABILITY_PERMISSION_REQUIRED",
		5: "AVAILABILITY_TEMPORARILY_UNAVAILABLE",
	}
	Availability_value = map[string]int32{
		"AVAILABILITY_UNSPECIFIED":             0,
		"AVAILABILITY_AVAILABLE":               1,
		"AVAILABILITY_UNSUPPORTED":             2,
		"AVAILABILITY_POLICY_BLOCKED":          3,
		"AVAILABILITY_PERMISSION_REQUIRED":     4,
		"AVAILABILITY_TEMPORARILY_UNAVAILABLE": 5,
	}
)

func (x Availability) Enum() *Availability {
	p := new(Availability)
	*p = x
	return p
}

func (x Availability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Availability) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[3].Descriptor()
}

func (Availability) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[3]
}

func (x Availability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Availability.Descriptor instead.
func (Availability) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{3}
}

type ActionOwner int32

const (
	ActionOwner_ACTION_OWNER_UNSPECIFIED          ActionOwner = 0
	ActionOwner_ACTION_OWNER_USER                 ActionOwner = 1
	ActionOwner_ACTION_OWNER_DEVICE_ADMINISTRATOR ActionOwner = 2
	ActionOwner_ACTION_OWNER_ACCESS_ADMINISTRATOR ActionOwner = 3
	ActionOwner_ACTION_OWNER_SUPPORT              ActionOwner = 4
)

// Enum value maps for ActionOwner.
var (
	ActionOwner_name = map[int32]string{
		0: "ACTION_OWNER_UNSPECIFIED",
		1: "ACTION_OWNER_USER",
		2: "ACTION_OWNER_DEVICE_ADMINISTRATOR",
		3: "ACTION_OWNER_ACCESS_ADMINISTRATOR",
		4: "ACTION_OWNER_SUPPORT",
	}
	ActionOwner_value = map[string]int32{
		"ACTION_OWNER_UNSPECIFIED":          0,
		"ACTION_OWNER_USER":                 1,
		"ACTION_OWNER_DEVICE_ADMINISTRATOR": 2,
		"ACTION_OWNER_ACCESS_ADMINISTRATOR": 3,
		"ACTION_OWNER_SUPPORT":              4,
	}
)

func (x ActionOwner) Enum() *ActionOwner {
	p := new(ActionOwner)
	*p = x
	return p
}

func (x ActionOwner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionOwner) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[4].Descriptor()
}

func (ActionOwner) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[4]
}

func (x ActionOwner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionOwner.Descriptor instead.
func (ActionOwner) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{4}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED                        ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT                   ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHENTICATED                    ErrorCode = 2
	ErrorCode_ERROR_CODE_OWNER_REQUIRED                     ErrorCode = 3
	ErrorCode_ERROR_CODE_ADMINISTRATOR_REQUIRED             ErrorCode = 4
	ErrorCode_ERROR_CODE_UNSUPPORTED                        ErrorCode = 5
	ErrorCode_ERROR_CODE_NOT_FOUND                          ErrorCode = 6
	ErrorCode_ERROR_CODE_STALE_STATE                        ErrorCode = 7
	ErrorCode_ERROR_CODE_POLICY_BLOCKED                     ErrorCode = 8
	ErrorCode_ERROR_CODE_PERMISSION_REQUIRED                ErrorCode = 9
	ErrorCode_ERROR_CODE_BUSY                               ErrorCode = 10
	ErrorCode_ERROR_CODE_LIMIT_EXCEEDED                     ErrorCode = 11
	ErrorCode_ERROR_CODE_UNAVAILABLE                        ErrorCode = 12
	ErrorCode_ERROR_CODE_DEADLINE_EXCEEDED                  ErrorCode = 13
	ErrorCode_ERROR_CODE_CANCELLED                          ErrorCode = 14
	ErrorCode_ERROR_CODE_INTERNAL                           ErrorCode = 15
	ErrorCode_ERROR_CODE_NEEDS_ENROLLMENT                   ErrorCode = 16
	ErrorCode_ERROR_CODE_NEEDS_LOGIN                        ErrorCode = 17
	ErrorCode_ERROR_CODE_APPROVAL_REQUIRED                  ErrorCode = 18
	ErrorCode_ERROR_CODE_APPROVAL_REJECTED                  ErrorCode = 19
	ErrorCode_ERROR_CODE_SERVER_IDENTITY_CHANGED            ErrorCode = 20
	ErrorCode_ERROR_CODE_IDENTITY_CONFIRMATION_MISMATCH     ErrorCode = 21
	ErrorCode_ERROR_CODE_REMOTE_CLEANUP_REQUIRED            ErrorCode = 22
	ErrorCode_ERROR_CODE_LOCAL_FORGET_CONFIRMATION_REQUIRED ErrorCode = 23
	ErrorCode_ERROR_CODE_APPLY_FAILED                       ErrorCode = 24
	ErrorCode_ERROR_CODE_PROFILE_ACTIVE                     ErrorCode = 25
	ErrorCode_ERROR_CODE_RESOURCE_CONFLICT                  ErrorCode = 26
	ErrorCode_ERROR_CODE_CONTRACT_MISMATCH                  ErrorCode = 27
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_INVALID_ARGUMENT",
		2:  "ERROR_CODE_UNAUTHENTICATED",
		3:  "ERROR_CODE_OWNER_REQUIRED",
		4:  "ERROR_CODE_ADMINISTRATOR_REQUIRED",
		5:  "ERROR_CODE_UNSUPPORTED",
		6:  "ERROR_CODE_NOT_FOUND",
		7:  "ERROR_CODE_STALE_STATE",
		8:  "ERROR_CODE_POLICY_BLOCKED",
		9:  "ERROR_CODE_PERMISSION_REQUIRED",
		10: "ERROR_CODE_BUSY",
		11: "ERROR_CODE_LIMIT_EXCEEDED",
		12: "ERROR_CODE_UNAVAILABLE",
		13: "ERROR_CODE_DEADLINE_EXCEEDED",
		14: "ERROR_CODE_CANCELLED",
		15: "ERROR_CODE_INTERNAL",
		16: "ERROR_CODE_NEEDS_ENROLLMENT",
		17: "ERROR_CODE_NEEDS_LOGIN",
		18: "ERROR_CODE_APPROVAL_REQUIRED",
		19: "ERROR_CODE_APPROVAL_REJECTED",
		20: "ERROR_CODE_SERVER_IDENTITY_CHANGED",
		21: "ERROR_CODE_IDENTITY_CONFIRMATION_MISMATCH",
		22: "ERROR_CODE_REMOTE_CLEANUP_REQUIRED",
		23: "ERROR_CODE_LOCAL_FORGET_CONFIRMATION_REQUIRED",
		24: "ERROR_CODE_APPLY_FAILED",
		25: "ERROR_CODE_PROFILE_ACTIVE",
		26: "ERROR_CODE_RESOURCE_CONFLICT",
		27: "ERROR_CODE_CONTRACT_MISMATCH",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":                        0,
		"ERROR_CODE_INVALID_ARGUMENT":                   1,
		"ERROR_CODE_UNAUTHENTICATED":                    2,
		"ERROR_CODE_OWNER_REQUIRED":                     3,
		"ERROR_CODE_ADMINISTRATOR_REQUIRED":             4,
		"ERROR_CODE_UNSUPPORTED":                        5,
		"ERROR_CODE_NOT_FOUND":                          6,
		"ERROR_CODE_STALE_STATE":                        7,
		"ERROR_CODE_POLICY_BLOCKED":                     8,
		"ERROR_CODE_PERMISSION_REQUIRED":                9,
		"ERROR_CODE_BUSY":                               10,
		"ERROR_CODE_LIMIT_EXCEEDED":                     11,
		"ERROR_CODE_UNAVAILABLE":                        12,
		"ERROR_CODE_DEADLINE_EXCEEDED":                  13,
		"ERROR_CODE_CANCELLED":                          14,
		"ERROR_CODE_INTERNAL":                           15,
		"ERROR_CODE_NEEDS_ENROLLMENT":                   16,
		"ERROR_CODE_NEEDS_LOGIN":                        17,
		"ERROR_CODE_APPROVAL_REQUIRED":                  18,
		"ERROR_CODE_APPROVAL_REJECTED":                  19,
		"ERROR_CODE_SERVER_IDENTITY_CHANGED":            20,
		"ERROR_CODE_IDENTITY_CONFIRMATION_MISMATCH":     21,
		"ERROR_CODE_REMOTE_CLEANUP_REQUIRED":            22,
		"ERROR_CODE_LOCAL_FORGET_CONFIRMATION_REQUIRED": 23,
		"ERROR_CODE_APPLY_FAILED":                       24,
		"ERROR_CODE_PROFILE_ACTIVE":                     25,
		"ERROR_CODE_RESOURCE_CONFLICT":                  26,
		"ERROR_CODE_CONTRACT_MISMATCH":                  27,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[5].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[5]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{5}
}

// Transport error details carry Failure. Completed operations use Failure too.
type OperationState int32

const (
	OperationState_OPERATION_STATE_UNSPECIFIED      OperationState = 0
	OperationState_OPERATION_STATE_PENDING          OperationState = 1
	OperationState_OPERATION_STATE_RUNNING          OperationState = 2
	OperationState_OPERATION_STATE_WAITING_FOR_USER OperationState = 3
	OperationState_OPERATION_STATE_SUCCEEDED        OperationState = 4
	OperationState_OPERATION_STATE_FAILED           OperationState = 5
	OperationState_OPERATION_STATE_CANCELLED        OperationState = 6
)

// Enum value maps for OperationState.
var (
	OperationState_name = map[int32]string{
		0: "OPERATION_STATE_UNSPECIFIED",
		1: "OPERATION_STATE_PENDING",
		2: "OPERATION_STATE_RUNNING",
		3: "OPERATION_STATE_WAITING_FOR_USER",
		4: "OPERATION_STATE_SUCCEEDED",
		5: "OPERATION_STATE_FAILED",
		6: "OPERATION_STATE_CANCELLED",
	}
	OperationState_value = map[string]int32{
		"OPERATION_STATE_UNSPECIFIED":      0,
		"OPERATION_STATE_PENDING":          1,
		"OPERATION_STATE_RUNNING":          2,
		"OPERATION_STATE_WAITING_FOR_USER": 3,
		"OPERATION_STATE_SUCCEEDED":        4,
		"OPERATION_STATE_FAILED":           5,
		"OPERATION_STATE_CANCELLED":        6,
	}
)

func (x OperationState) Enum() *OperationState {
	p := new(OperationState)
	*p = x
	return p
}

func (x OperationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationState) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[6].Descriptor()
}

func (OperationState) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[6]
}

func (x OperationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationState.Descriptor instead.
func (OperationState) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{6}
}

type ConnectionContinuity int32

const (
	ConnectionContinuity_CONNECTION_CONTINUITY_UNSPECIFIED    ConnectionContinuity = 0
	ConnectionContinuity_CONNECTION_CONTINUITY_NOT_APPLICABLE ConnectionContinuity = 1
	ConnectionContinuity_CONNECTION_CONTINUITY_PRESERVED      ConnectionContinuity = 2
	ConnectionContinuity_CONNECTION_CONTINUITY_INTERRUPTED    ConnectionContinuity = 3
	ConnectionContinuity_CONNECTION_CONTINUITY_UNKNOWN        ConnectionContinuity = 4
)

// Enum value maps for ConnectionContinuity.
var (
	ConnectionContinuity_name = map[int32]string{
		0: "CONNECTION_CONTINUITY_UNSPECIFIED",
		1: "CONNECTION_CONTINUITY_NOT_APPLICABLE",
		2: "CONNECTION_CONTINUITY_PRESERVED",
		3: "CONNECTION_CONTINUITY_INTERRUPTED",
		4: "CONNECTION_CONTINUITY_UNKNOWN",
	}
	ConnectionContinuity_value = map[string]int32{
		"CONNECTION_CONTINUITY_UNSPECIFIED":    0,
		"CONNECTION_CONTINUITY_NOT_APPLICABLE": 1,
		"CONNECTION_CONTINUITY_PRESERVED":      2,
		"CONNECTION_CONTINUITY_INTERRUPTED":    3,
		"CONNECTION_CONTINUITY_UNKNOWN":        4,
	}
)

func (x ConnectionContinuity) Enum() *ConnectionContinuity {
	p := new(ConnectionContinuity)
	*p = x
	return p
}

func (x ConnectionContinuity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionContinuity) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[7].Descriptor()
}

func (ConnectionContinuity) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[7]
}

func (x ConnectionContinuity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionContinuity.Descriptor instead.
func (ConnectionContinuity) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{7}
}

type CleanupOutcome int32

const (
	CleanupOutcome_CLEANUP_OUTCOME_UNSPECIFIED        CleanupOutcome = 0
	CleanupOutcome_CLEANUP_OUTCOME_REMOTE_CONFIRMED   CleanupOutcome = 1
	CleanupOutcome_CLEANUP_OUTCOME_REMOTE_UNCONFIRMED CleanupOutcome = 2
	CleanupOutcome_CLEANUP_OUTCOME_NOT_REGISTERED     CleanupOutcome = 3
)

// Enum value maps for CleanupOutcome.
var (
	CleanupOutcome_name = map[int32]string{
		0: "CLEANUP_OUTCOME_UNSPECIFIED",
		1: "CLEANUP_OUTCOME_REMOTE_CONFIRMED",
		2: "CLEANUP_OUTCOME_REMOTE_UNCONFIRMED",
		3: "CLEANUP_OUTCOME_NOT_REGISTERED",
	}
	CleanupOutcome_value = map[string]int32{
		"CLEANUP_OUTCOME_UNSPECIFIED":        0,
		"CLEANUP_OUTCOME_REMOTE_CONFIRMED":   1,
		"CLEANUP_OUTCOME_REMOTE_UNCONFIRMED": 2,
		"CLEANUP_OUTCOME_NOT_REGISTERED":     3,
	}
)

func (x CleanupOutcome) Enum() *CleanupOutcome {
	p := new(CleanupOutcome)
	*p = x
	return p
}

func (x CleanupOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CleanupOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[8].Descriptor()
}

func (CleanupOutcome) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[8]
}

func (x CleanupOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CleanupOutcome.Descriptor instead.
func (CleanupOutcome) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{8}
}

// Closed mutation vocabulary; UNSPECIFIED is invalid in returned operations.
type OperationKind int32

const (
	OperationKind_OPERATION_KIND_UNSPECIFIED               OperationKind = 0
	OperationKind_OPERATION_KIND_ENROLL                    OperationKind = 1
	OperationKind_OPERATION_KIND_CONNECT                   OperationKind = 2
	OperationKind_OPERATION_KIND_DISCONNECT                OperationKind = 3
	OperationKind_OPERATION_KIND_TRUST_SERVER_IDENTITY     OperationKind = 4
	OperationKind_OPERATION_KIND_LOGOUT                    OperationKind = 5
	OperationKind_OPERATION_KIND_FORGET_LOCAL_ENROLLMENT   OperationKind = 6
	OperationKind_OPERATION_KIND_SELECT_NETWORK            OperationKind = 7
	OperationKind_OPERATION_KIND_CREATE_DIAGNOSTICS_BUNDLE OperationKind = 8
	OperationKind_OPERATION_KIND_CREATE_PROFILE            OperationKind = 9
	OperationKind_OPERATION_KIND_SELECT_PROFILE            OperationKind = 10
	OperationKind_OPERATION_KIND_RENAME_PROFILE            OperationKind = 11
	OperationKind_OPERATION_KIND_REMOVE_PROFILE            OperationKind = 12
	OperationKind_OPERATION_KIND_RENEW_SESSION             OperationKind = 13
	OperationKind_OPERATION_KIND_SELECT_EXIT_NODE          OperationKind = 14
	OperationKind_OPERATION_KIND_CLEAR_EXIT_NODE           OperationKind = 15
	OperationKind_OPERATION_KIND_SET_PREFERENCES           OperationKind = 16
	OperationKind_OPERATION_KIND_RESET_PREFERENCES         OperationKind = 17
	OperationKind_OPERATION_KIND_SET_RESOURCE_ENABLED      OperationKind = 18
	OperationKind_OPERATION_KIND_NOTIFY_LIFECYCLE          OperationKind = 19
)

// Enum value maps for OperationKind.
var (
	OperationKind_name = map[int32]string{
		0:  "OPERATION_KIND_UNSPECIFIED",
		1:  "OPERATION_KIND_ENROLL",
		2:  "OPERATION_KIND_CONNECT",
		3:  "OPERATION_KIND_DISCONNECT",
		4:  "OPERATION_KIND_TRUST_SERVER_IDENTITY",
		5:  "OPERATION_KIND_LOGOUT",
		6:  "OPERATION_KIND_FORGET_LOCAL_ENROLLMENT",
		7:  "OPERATION_KIND_SELECT_NETWORK",
		8:  "OPERATION_KIND_CREATE_DIAGNOSTICS_BUNDLE",
		9:  "OPERATION_KIND_CREATE_PROFILE",
		10: "OPERATION_KIND_SELECT_PROFILE",
		11: "OPERATION_KIND_RENAME_PROFILE",
		12: "OPERATION_KIND_REMOVE_PROFILE",
		13: "OPERATION_KIND_RENEW_SESSION",
		14: "OPERATION_KIND_SELECT_EXIT_NODE",
		15: "OPERATION_KIND_CLEAR_EXIT_NODE",
		16: "OPERATION_KIND_SET_PREFERENCES",
		17: "OPERATION_KIND_RESET_PREFERENCES",
		18: "OPERATION_KIND_SET_RESOURCE_ENABLED",
		19: "OPERATION_KIND_NOTIFY_LIFECYCLE",
	}
	OperationKind_value = map[string]int32{
		"OPERATION_KIND_UNSPECIFIED":               0,
		"OPERATION_KIND_ENROLL":                    1,
		"OPERATION_KIND_CONNECT":                   2,
		"OPERATION_KIND_DISCONNECT":                3,
		"OPERATION_KIND_TRUST_SERVER_IDENTITY":     4,
		"OPERATION_KIND_LOGOUT":                    5,
		"OPERATION_KIND_FORGET_LOCAL_ENROLLMENT":   6,
		"OPERATION_KIND_SELECT_NETWORK":            7,
		"OPERATION_KIND_CREATE_DIAGNOSTICS_BUNDLE": 8,
		"OPERATION_KIND_CREATE_PROFILE":            9,
		"OPERATION_KIND_SELECT_PROFILE":            10,
		"OPERATION_KIND_RENAME_PROFILE":            11,
		"OPERATION_KIND_REMOVE_PROFILE":            12,
		"OPERATION_KIND_RENEW_SESSION":             13,
		"OPERATION_KIND_SELECT_EXIT_NODE":          14,
		"OPERATION_KIND_CLEAR_EXIT_NODE":           15,
		"OPERATION_KIND_SET_PREFERENCES":           16,
		"OPERATION_KIND_RESET_PREFERENCES":         17,
		"OPERATION_KIND_SET_RESOURCE_ENABLED":      18,
		"OPERATION_KIND_NOTIFY_LIFECYCLE":          19,
	}
)

func (x OperationKind) Enum() *OperationKind {
	p := new(OperationKind)
	*p = x
	return p
}

func (x OperationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[9].Descriptor()
}

func (OperationKind) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[9]
}

func (x OperationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationKind.Descriptor instead.
func (OperationKind) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{9}
}

type UserAction_Kind int32

const (
	UserAction_KIND_UNSPECIFIED                  UserAction_Kind = 0
	UserAction_KIND_OPEN_BROWSER                 UserAction_Kind = 1
	UserAction_KIND_WAIT_FOR_APPROVAL            UserAction_Kind = 2
	UserAction_KIND_GRANT_VPN_PERMISSION         UserAction_Kind = 3
	UserAction_KIND_USE_PRIVILEGED_HELPER        UserAction_Kind = 4
	UserAction_KIND_CONTACT_ACCESS_ADMINISTRATOR UserAction_Kind = 5
)

// Enum value maps for UserAction_Kind.
var (
	UserAction_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_OPEN_BROWSER",
		2: "KIND_WAIT_FOR_APPROVAL",
		3: "KIND_GRANT_VPN_PERMISSION",
		4: "KIND_USE_PRIVILEGED_HELPER",
		5: "KIND_CONTACT_ACCESS_ADMINISTRATOR",
	}
	UserAction_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":                  0,
		"KIND_OPEN_BROWSER":                 1,
		"KIND_WAIT_FOR_APPROVAL":            2,
		"KIND_GRANT_VPN_PERMISSION":         3,
		"KIND_USE_PRIVILEGED_HELPER":        4,
		"KIND_CONTACT_ACCESS_ADMINISTRATOR": 5,
	}
)

func (x UserAction_Kind) Enum() *UserAction_Kind {
	p := new(UserAction_Kind)
	*p = x
	return p
}

func (x UserAction_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserAction_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_common_proto_enumTypes[10].Descriptor()
}

func (UserAction_Kind) Type() protoreflect.EnumType {
	return &file_client_v0_common_proto_enumTypes[10]
}

func (x UserAction_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserAction_Kind.Descriptor instead.
func (UserAction_Kind) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{8, 0}
}

type Restriction struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Availability Availability           `protobuf:"varint,1,opt,name=availability,proto3,enum=client.v0.Availability" json:"availability,omitempty"`
	// Stable localization key; never arbitrary server text or a secret.
	ReasonKey     string      `protobuf:"bytes,2,opt,name=reason_key,json=reasonKey,proto3" json:"reason_key,omitempty"`
	ActionOwner   ActionOwner `protobuf:"varint,3,opt,name=action_owner,json=actionOwner,proto3,enum=client.v0.ActionOwner" json:"action_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restriction) Reset() {
	*x = Restriction{}
	mi := &file_client_v0_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restriction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restriction) ProtoMessage() {}

func (x *Restriction) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restriction.ProtoReflect.Descriptor instead.
func (*Restriction) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{0}
}

func (x *Restriction) GetAvailability() Availability {
	if x != nil {
		return x.Availability
	}
	return Availability_AVAILABILITY_UNSPECIFIED
}

func (x *Restriction) GetReasonKey() string {
	if x != nil {
		return x.ReasonKey
	}
	return ""
}

func (x *Restriction) GetActionOwner() ActionOwner {
	if x != nil {
		return x.ActionOwner
	}
	return ActionOwner_ACTION_OWNER_UNSPECIFIED
}

type CapabilityStatus struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Capability  Capability             `protobuf:"varint,1,opt,name=capability,proto3,enum=client.v0.Capability" json:"capability,omitempty"`
	Restriction *Restriction           `protobuf:"bytes,2,opt,name=restriction,proto3" json:"restriction,omitempty"`
	// Indicates applicability on this runtime, not a promise of release support.
	Platform      Platform `protobuf:"varint,3,opt,name=platform,proto3,enum=client.v0.Platform" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityStatus) Reset() {
	*x = CapabilityStatus{}
	mi := &file_client_v0_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityStatus) ProtoMessage() {}

func (x *CapabilityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityStatus.ProtoReflect.Descriptor instead.
func (*CapabilityStatus) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilityStatus) GetCapability() Capability {
	if x != nil {
		return x.Capability
	}
	return Capability_CAPABILITY_UNSPECIFIED
}

func (x *CapabilityStatus) GetRestriction() *Restriction {
	if x != nil {
		return x.Restriction
	}
	return nil
}

func (x *CapabilityStatus) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

type BuildIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	BuildDate     string                 `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	Platform      Platform               `protobuf:"varint,4,opt,name=platform,proto3,enum=client.v0.Platform" json:"platform,omitempty"`
	Architecture  string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildIdentity) Reset() {
	*x = BuildIdentity{}
	mi := &file_client_v0_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildIdentity) ProtoMessage() {}

func (x *BuildIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildIdentity.ProtoReflect.Descriptor instead.
func (*BuildIdentity) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{2}
}

func (x *BuildIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BuildIdentity) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *BuildIdentity) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *BuildIdentity) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *BuildIdentity) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type RuntimeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Build *BuildIdentity         `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	// Opaque identifier changes on every runtime start.
	InstanceId   string              `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Capabilities []*CapabilityStatus `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	CallerAccess Access              `protobuf:"varint,4,opt,name=caller_access,json=callerAccess,proto3,enum=client.v0.Access" json:"caller_access,omitempty"`
	// Exact contract revision/hash. Version number alone cannot pair artifacts.
	ContractSha256 string `protobuf:"bytes,5,opt,name=contract_sha256,json=contractSha256,proto3" json:"contract_sha256,omitempty"`
	Protocol       string `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`                        // Must be endlessnet-client-ipc.
	IpcVersion     uint32 `protobuf:"varint,7,opt,name=ipc_version,json=ipcVersion,proto3" json:"ipc_version,omitempty"` // Must be 0, as explicitly selected for this new contract.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_client_v0_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeInfo) GetBuild() *BuildIdentity {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *RuntimeInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RuntimeInfo) GetCapabilities() []*CapabilityStatus {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RuntimeInfo) GetCallerAccess() Access {
	if x != nil {
		return x.CallerAccess
	}
	return Access_ACCESS_UNSPECIFIED
}

func (x *RuntimeInfo) GetContractSha256() string {
	if x != nil {
		return x.ContractSha256
	}
	return ""
}

func (x *RuntimeInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RuntimeInfo) GetIpcVersion() uint32 {
	if x != nil {
		return x.IpcVersion
	}
	return 0
}

type SnapshotMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotMetadata) Reset() {
	*x = SnapshotMetadata{}
	mi := &file_client_v0_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMetadata) ProtoMessage() {}

func (x *SnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMetadata.ProtoReflect.Descriptor instead.
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotMetadata) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SnapshotMetadata) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *SnapshotMetadata) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type ProfileRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileRef) Reset() {
	*x = ProfileRef{}
	mi := &file_client_v0_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRef) ProtoMessage() {}

func (x *ProfileRef) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRef.ProtoReflect.Descriptor instead.
func (*ProfileRef) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{5}
}

func (x *ProfileRef) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

// Mandatory on every mutation. Never contains credentials or claimed roles.
type MutationContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID, scoped to authenticated installation owner. Durable for at least 24h.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Both required; stale values fail before side effects.
	ExpectedInstanceId string `protobuf:"bytes,2,opt,name=expected_instance_id,json=expectedInstanceId,proto3" json:"expected_instance_id,omitempty"`
	ExpectedRevision   uint64 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MutationContext) Reset() {
	*x = MutationContext{}
	mi := &file_client_v0_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationContext) ProtoMessage() {}

func (x *MutationContext) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationContext.ProtoReflect.Descriptor instead.
func (*MutationContext) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{6}
}

func (x *MutationContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MutationContext) GetExpectedInstanceId() string {
	if x != nil {
		return x.ExpectedInstanceId
	}
	return ""
}

func (x *MutationContext) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type Failure struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Code      ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=client.v0.ErrorCode" json:"code,omitempty"`
	ReasonKey string                 `protobuf:"bytes,2,opt,name=reason_key,json=reasonKey,proto3" json:"reason_key,omitempty"`
	// Correlation IDs only; no diagnostic payload, bearer token or credentials.
	ControlRequestId string               `protobuf:"bytes,3,opt,name=control_request_id,json=controlRequestId,proto3" json:"control_request_id,omitempty"`
	Retryable        bool                 `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	RetryAfter       *durationpb.Duration `protobuf:"bytes,5,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	ActionOwner      ActionOwner          `protobuf:"varint,6,opt,name=action_owner,json=actionOwner,proto3,enum=client.v0.ActionOwner" json:"action_owner,omitempty"`
	FieldPaths       []string             `protobuf:"bytes,7,rep,name=field_paths,json=fieldPaths,proto3" json:"field_paths,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_client_v0_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{7}
}

func (x *Failure) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Failure) GetReasonKey() string {
	if x != nil {
		return x.ReasonKey
	}
	return ""
}

func (x *Failure) GetControlRequestId() string {
	if x != nil {
		return x.ControlRequestId
	}
	return ""
}

func (x *Failure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Failure) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

func (x *Failure) GetActionOwner() ActionOwner {
	if x != nil {
		return x.ActionOwner
	}
	return ActionOwner_ACTION_OWNER_UNSPECIFIED
}

func (x *Failure) GetFieldPaths() []string {
	if x != nil {
		return x.FieldPaths
	}
	return nil
}

type UserAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  UserAction_Kind        `protobuf:"varint,1,opt,name=kind,proto3,enum=client.v0.UserAction_Kind" json:"kind,omitempty"`
	// Optional validated HTTPS browser URL; sensitive and excluded from logs.
	BrowserUrl    string                 `protobuf:"bytes,2,opt,name=browser_url,json=browserUrl,proto3" json:"browser_url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ReasonKey     string                 `protobuf:"bytes,4,opt,name=reason_key,json=reasonKey,proto3" json:"reason_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAction) Reset() {
	*x = UserAction{}
	mi := &file_client_v0_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAction) ProtoMessage() {}

func (x *UserAction) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAction.ProtoReflect.Descriptor instead.
func (*UserAction) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{8}
}

func (x *UserAction) GetKind() UserAction_Kind {
	if x != nil {
		return x.Kind
	}
	return UserAction_KIND_UNSPECIFIED
}

func (x *UserAction) GetBrowserUrl() string {
	if x != nil {
		return x.BrowserUrl
	}
	return ""
}

func (x *UserAction) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *UserAction) GetReasonKey() string {
	if x != nil {
		return x.ReasonKey
	}
	return ""
}

type ChangeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeResult) Reset() {
	*x = ChangeResult{}
	mi := &file_client_v0_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeResult) ProtoMessage() {}

func (x *ChangeResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeResult.ProtoReflect.Descriptor instead.
func (*ChangeResult) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeResult) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

type EnrollmentResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollmentResult) Reset() {
	*x = EnrollmentResult{}
	mi := &file_client_v0_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentResult) ProtoMessage() {}

func (x *EnrollmentResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentResult.ProtoReflect.Descriptor instead.
func (*EnrollmentResult) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{10}
}

func (x *EnrollmentResult) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *EnrollmentResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type SelectionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SelectedId    string                 `protobuf:"bytes,1,opt,name=selected_id,json=selectedId,proto3" json:"selected_id,omitempty"` // Empty means cleared, only for exit-node selection.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectionResult) Reset() {
	*x = SelectionResult{}
	mi := &file_client_v0_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionResult) ProtoMessage() {}

func (x *SelectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionResult.ProtoReflect.Descriptor instead.
func (*SelectionResult) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{11}
}

func (x *SelectionResult) GetSelectedId() string {
	if x != nil {
		return x.SelectedId
	}
	return ""
}

type CleanupResult struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Outcome                  CleanupOutcome         `protobuf:"varint,1,opt,name=outcome,proto3,enum=client.v0.CleanupOutcome" json:"outcome,omitempty"`
	LocalRegistrationRemoved bool                   `protobuf:"varint,2,opt,name=local_registration_removed,json=localRegistrationRemoved,proto3" json:"local_registration_removed,omitempty"`
	ControlRequestId         string                 `protobuf:"bytes,3,opt,name=control_request_id,json=controlRequestId,proto3" json:"control_request_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CleanupResult) Reset() {
	*x = CleanupResult{}
	mi := &file_client_v0_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupResult) ProtoMessage() {}

func (x *CleanupResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupResult.ProtoReflect.Descriptor instead.
func (*CleanupResult) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{12}
}

func (x *CleanupResult) GetOutcome() CleanupOutcome {
	if x != nil {
		return x.Outcome
	}
	return CleanupOutcome_CLEANUP_OUTCOME_UNSPECIFIED
}

func (x *CleanupResult) GetLocalRegistrationRemoved() bool {
	if x != nil {
		return x.LocalRegistrationRemoved
	}
	return false
}

func (x *CleanupResult) GetControlRequestId() string {
	if x != nil {
		return x.ControlRequestId
	}
	return ""
}

type RenewalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewalResult) Reset() {
	*x = RenewalResult{}
	mi := &file_client_v0_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewalResult) ProtoMessage() {}

func (x *RenewalResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewalResult.ProtoReflect.Descriptor instead.
func (*RenewalResult) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{13}
}

func (x *RenewalResult) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type BundleResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque, caller-bound handle; never an arbitrary filesystem path.
	BundleId      string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Reused        bool                   `protobuf:"varint,6,opt,name=reused,proto3" json:"reused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleResult) Reset() {
	*x = BundleResult{}
	mi := &file_client_v0_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleResult) ProtoMessage() {}

func (x *BundleResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleResult.ProtoReflect.Descriptor instead.
func (*BundleResult) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{14}
}

func (x *BundleResult) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *BundleResult) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BundleResult) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *BundleResult) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *BundleResult) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *BundleResult) GetReused() bool {
	if x != nil {
		return x.Reused
	}
	return false
}

type Operation struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId  string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ProfileId  string                 `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	State      OperationState         `protobuf:"varint,4,opt,name=state,proto3,enum=client.v0.OperationState" json:"state,omitempty"`
	Metadata   *SnapshotMetadata      `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserAction *UserAction            `protobuf:"bytes,6,opt,name=user_action,json=userAction,proto3" json:"user_action,omitempty"`
	Continuity ConnectionContinuity   `protobuf:"varint,7,opt,name=continuity,proto3,enum=client.v0.ConnectionContinuity" json:"continuity,omitempty"`
	// Immutable, including pending operations, snapshots and restart recovery.
	Kind OperationKind `protobuf:"varint,8,opt,name=kind,proto3,enum=client.v0.OperationKind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*Operation_Failure
	//	*Operation_Change
	//	*Operation_Enrollment
	//	*Operation_Selection
	//	*Operation_Cleanup
	//	*Operation_Renewal
	//	*Operation_Bundle
	Outcome       isOperation_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_client_v0_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{15}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Operation) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Operation) GetState() OperationState {
	if x != nil {
		return x.State
	}
	return OperationState_OPERATION_STATE_UNSPECIFIED
}

func (x *Operation) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Operation) GetUserAction() *UserAction {
	if x != nil {
		return x.UserAction
	}
	return nil
}

func (x *Operation) GetContinuity() ConnectionContinuity {
	if x != nil {
		return x.Continuity
	}
	return ConnectionContinuity_CONNECTION_CONTINUITY_UNSPECIFIED
}

func (x *Operation) GetKind() OperationKind {
	if x != nil {
		return x.Kind
	}
	return OperationKind_OPERATION_KIND_UNSPECIFIED
}

func (x *Operation) GetOutcome() isOperation_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *Operation) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Outcome.(*Operation_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

func (x *Operation) GetChange() *ChangeResult {
	if x != nil {
		if x, ok := x.Outcome.(*Operation_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *Operation) GetEnrollment() *EnrollmentResult {
	if x != nil {
		if x, ok := x.Outcome.(*Operation_Enrollment); ok {
			return x.Enrollment
		}
	}
	return nil
}

func (x *Operation) GetSelection() *SelectionResult {
	if x != nil {
		if x, ok := x.Outcome.(*Operation_Selection); ok {
			return x.Selection
		}
	}
	return nil
}

func (x *Operation) GetCleanup() *CleanupResult {
	if x != nil {
		if x, ok := x.Outcome.(*Operation_Cleanup); ok {
			return x.Cleanup
		}
	}
	return nil
}

func (x *Operation) GetRenewal() *RenewalResult {
	if x != nil {
		if x, ok := x.Outcome.(*Operation_Renewal); ok {
			return x.Renewal
		}
	}
	return nil
}

func (x *Operation) GetBundle() *BundleResult {
	if x != nil {
		if x, ok := x.Outcome.(*Operation_Bundle); ok {
			return x.Bundle
		}
	}
	return nil
}

type isOperation_Outcome interface {
	isOperation_Outcome()
}

type Operation_Failure struct {
	Failure *Failure `protobuf:"bytes,10,opt,name=failure,proto3,oneof"`
}

type Operation_Change struct {
	Change *ChangeResult `protobuf:"bytes,11,opt,name=change,proto3,oneof"`
}

type Operation_Enrollment struct {
	Enrollment *EnrollmentResult `protobuf:"bytes,12,opt,name=enrollment,proto3,oneof"`
}

type Operation_Selection struct {
	Selection *SelectionResult `protobuf:"bytes,13,opt,name=selection,proto3,oneof"`
}

type Operation_Cleanup struct {
	Cleanup *CleanupResult `protobuf:"bytes,14,opt,name=cleanup,proto3,oneof"`
}

type Operation_Renewal struct {
	Renewal *RenewalResult `protobuf:"bytes,15,opt,name=renewal,proto3,oneof"`
}

type Operation_Bundle struct {
	Bundle *BundleResult `protobuf:"bytes,16,opt,name=bundle,proto3,oneof"`
}

func (*Operation_Failure) isOperation_Outcome() {}

func (*Operation_Change) isOperation_Outcome() {}

func (*Operation_Enrollment) isOperation_Outcome() {}

func (*Operation_Selection) isOperation_Outcome() {}

func (*Operation_Cleanup) isOperation_Outcome() {}

func (*Operation_Renewal) isOperation_Outcome() {}

func (*Operation_Bundle) isOperation_Outcome() {}

type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 0 = 100; max 500.
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // Opaque, caller/query/profile/revision-bound.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_client_v0_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{16}
}

func (x *PageRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Metadata      *SnapshotMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_client_v0_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_client_v0_common_proto_rawDescGZIP(), []int{17}
}

func (x *PageResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *PageResponse) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var file_client_v0_common_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Access)(nil),
		Field:         51000,
		Name:          "client.v0.access",
		Tag:           "varint,51000,opt,name=access,enum=client.v0.Access",
		Filename:      "client/v0/common.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         51001,
		Name:          "client.v0.allows_initial_ownership_claim",
		Tag:           "varint,51001,opt,name=allows_initial_ownership_claim",
		Filename:      "client/v0/common.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*OperationKind)(nil),
		Field:         51002,
		Name:          "client.v0.operation_kind",
		Tag:           "varint,51002,opt,name=operation_kind,enum=client.v0.OperationKind",
		Filename:      "client/v0/common.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// Minimum role, derived from authenticated local peer identity, never payload.
	//
	// optional client.v0.Access access = 51000;
	E_Access = &file_client_v0_common_proto_extTypes[0]
	// Only a fresh installation with no owner or enrollment may claim atomically.
	//
	// optional bool allows_initial_ownership_claim = 51001;
	E_AllowsInitialOwnershipClaim = &file_client_v0_common_proto_extTypes[1]
	// Required for every mutation; persisted into Operation.kind at acceptance.
	//
	// optional client.v0.OperationKind operation_kind = 51002;
	E_OperationKind = &file_client_v0_common_proto_extTypes[2]
)

var File_client_v0_common_proto protoreflect.FileDescriptor

const file_client_v0_common_proto_rawDesc = "" +
	"\n" +
	"\x16client/v0/common.proto\x12\tclient.v0\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x01\n" +
	"\vRestriction\x12;\n" +
	"\favailability\x18\x01 \x01(\x0e2\x17.client.v0.AvailabilityR\favailability\x12\x1d\n" +
	"\n" +
	"reason_key\x18\x02 \x01(\tR\treasonKey\x129\n" +
	"\faction_owner\x18\x03 \x01(\x0e2\x16.client.v0.ActionOwnerR\vactionOwner\"\xb4\x01\n" +
	"\x10CapabilityStatus\x125\n" +
	"\n" +
	"capability\x18\x01 \x01(\x0e2\x15.client.v0.CapabilityR\n" +
	"capability\x128\n" +
	"\vrestriction\x18\x02 \x01(\v2\x16.client.v0.RestrictionR\vrestriction\x12/\n" +
	"\bplatform\x18\x03 \x01(\x0e2\x13.client.v0.PlatformR\bplatform\"\xb5\x01\n" +
	"\rBuildIdentity\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\x12/\n" +
	"\bplatform\x18\x04 \x01(\x0e2\x13.client.v0.PlatformR\bplatform\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\"\xbd\x02\n" +
	"\vRuntimeInfo\x12.\n" +
	"\x05build\x18\x01 \x01(\v2\x18.client.v0.BuildIdentityR\x05build\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12?\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x1b.client.v0.CapabilityStatusR\fcapabilities\x126\n" +
	"\rcaller_access\x18\x04 \x01(\x0e2\x11.client.v0.AccessR\fcallerAccess\x12'\n" +
	"\x0fcontract_sha256\x18\x05 \x01(\tR\x0econtractSha256\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vipc_version\x18\a \x01(\rR\n" +
	"ipcVersion\"\x8e\x01\n" +
	"\x10SnapshotMetadata\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"+\n" +
	"\n" +
	"ProfileRef\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"\x8f\x01\n" +
	"\x0fMutationContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x120\n" +
	"\x14expected_instance_id\x18\x02 \x01(\tR\x12expectedInstanceId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\x04R\x10expectedRevision\"\xb6\x02\n" +
	"\aFailure\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.client.v0.ErrorCodeR\x04code\x12\x1d\n" +
	"\n" +
	"reason_key\x18\x02 \x01(\tR\treasonKey\x12,\n" +
	"\x12control_request_id\x18\x03 \x01(\tR\x10controlRequestId\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12:\n" +
	"\vretry_after\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\x129\n" +
	"\faction_owner\x18\x06 \x01(\x0e2\x16.client.v0.ActionOwnerR\vactionOwner\x12\x1f\n" +
	"\vfield_paths\x18\a \x03(\tR\n" +
	"fieldPaths\"\xef\x02\n" +
	"\n" +
	"UserAction\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.client.v0.UserAction.KindR\x04kind\x12\x1f\n" +
	"\vbrowser_url\x18\x02 \x01(\tR\n" +
	"browserUrl\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"reason_key\x18\x04 \x01(\tR\treasonKey\"\xb5\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11KIND_OPEN_BROWSER\x10\x01\x12\x1a\n" +
	"\x16KIND_WAIT_FOR_APPROVAL\x10\x02\x12\x1d\n" +
	"\x19KIND_GRANT_VPN_PERMISSION\x10\x03\x12\x1e\n" +
	"\x1aKIND_USE_PRIVILEGED_HELPER\x10\x04\x12%\n" +
	"!KIND_CONTACT_ACCESS_ADMINISTRATOR\x10\x05\"(\n" +
	"\fChangeResult\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\"J\n" +
	"\x10EnrollmentResult\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"2\n" +
	"\x0fSelectionResult\x12\x1f\n" +
	"\vselected_id\x18\x01 \x01(\tR\n" +
	"selectedId\"\xb0\x01\n" +
	"\rCleanupResult\x123\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x19.client.v0.CleanupOutcomeR\aoutcome\x12<\n" +
	"\x1alocal_registration_removed\x18\x02 \x01(\bR\x18localRegistrationRemoved\x12,\n" +
	"\x12control_request_id\x18\x03 \x01(\tR\x10controlRequestId\"J\n" +
	"\rRenewalResult\x129\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xf0\x01\n" +
	"\fBundleResult\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06reused\x18\x06 \x01(\bR\x06reused\"\xf2\x05\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\tprofileId\x12/\n" +
	"\x05state\x18\x04 \x01(\x0e2\x19.client.v0.OperationStateR\x05state\x127\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1b.client.v0.SnapshotMetadataR\bmetadata\x126\n" +
	"\vuser_action\x18\x06 \x01(\v2\x15.client.v0.UserActionR\n" +
	"userAction\x12?\n" +
	"\n" +
	"continuity\x18\a \x01(\x0e2\x1f.client.v0.ConnectionContinuityR\n" +
	"continuity\x12,\n" +
	"\x04kind\x18\b \x01(\x0e2\x18.client.v0.OperationKindR\x04kind\x12.\n" +
	"\afailure\x18\n" +
	" \x01(\v2\x12.client.v0.FailureH\x00R\afailure\x121\n" +
	"\x06change\x18\v \x01(\v2\x17.client.v0.ChangeResultH\x00R\x06change\x12=\n" +
	"\n" +
	"enrollment\x18\f \x01(\v2\x1b.client.v0.EnrollmentResultH\x00R\n" +
	"enrollment\x12:\n" +
	"\tselection\x18\r \x01(\v2\x1a.client.v0.SelectionResultH\x00R\tselection\x124\n" +
	"\acleanup\x18\x0e \x01(\v2\x18.client.v0.CleanupResultH\x00R\acleanup\x124\n" +
	"\arenewal\x18\x0f \x01(\v2\x18.client.v0.RenewalResultH\x00R\arenewal\x121\n" +
	"\x06bundle\x18\x10 \x01(\v2\x17.client.v0.BundleResultH\x00R\x06bundleB\t\n" +
	"\aoutcome\"I\n" +
	"\vPageRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"o\n" +
	"\fPageResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x127\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.client.v0.SnapshotMetadataR\bmetadata*a\n" +
	"\x06Access\x12\x16\n" +
	"\x12ACCESS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACCESS_OBSERVER\x10\x01\x12\x10\n" +
	"\fACCESS_OWNER\x10\x02\x12\x18\n" +
	"\x14ACCESS_ADMINISTRATOR\x10\x03*\x8a\x01\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PLATFORM_WINDOWS\x10\x01\x12\x12\n" +
	"\x0ePLATFORM_MACOS\x10\x02\x12\x12\n" +
	"\x0ePLATFORM_LINUX\x10\x03\x12\x14\n" +
	"\x10PLATFORM_ANDROID\x10\x04\x12\x10\n" +
	"\fPLATFORM_IOS\x10\x05*\x92\x04\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CAPABILITY_ENROLLMENT\x10\x01\x12\x19\n" +
	"\x15CAPABILITY_CONNECTION\x10\x02\x12\x14\n" +
	"\x10CAPABILITY_PEERS\x10\x03\x12 \n" +
	"\x1cCAPABILITY_NETWORK_SELECTION\x10\x04\x12\x18\n" +
	"\x14CAPABILITY_EXIT_NODE\x10\x05\x12 \n" +
	"\x1cCAPABILITY_IDENTITY_RECOVERY\x10\x06\x12\x1a\n" +
	"\x16CAPABILITY_DIAGNOSTICS\x10\a\x12\x15\n" +
	"\x11CAPABILITY_LOGOUT\x10\b\x12\x1b\n" +
	"\x17CAPABILITY_LOCAL_FORGET\x10\t\x12\x17\n" +
	"\x13CAPABILITY_PROFILES\x10\n" +
	"\x12\x1e\n" +
	"\x1aCAPABILITY_SESSION_RENEWAL\x10\v\x12\x1a\n" +
	"\x16CAPABILITY_PREFERENCES\x10\f\x12\x18\n" +
	"\x14CAPABILITY_RESOURCES\x10\r\x12\x1f\n" +
	"\x1bCAPABILITY_MANAGED_SETTINGS\x10\x0e\x12 \n" +
	"\x1cCAPABILITY_RUNTIME_LIFECYCLE\x10\x0f\x12\x1f\n" +
	"\x1bCAPABILITY_UPDATE_DISCOVERY\x10\x10\x12\x1b\n" +
	"\x17CAPABILITY_SUPPORT_INFO\x10\x11*\xd7\x01\n" +
	"\fAvailability\x12\x1c\n" +
	"\x18AVAILABILITY_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16AVAILABILITY_AVAILABLE\x10\x01\x12\x1c\n" +
	"\x18AVAILABILITY_UNSUPPORTED\x10\x02\x12\x1f\n" +
	"\x1bAVAILABILITY_POLICY_BLOCKED\x10\x03\x12$\n" +
	" AVAILABILITY_PERMISSION_REQUIRED\x10\x04\x12(\n" +
	"$AVAILABILITY_TEMPORARILY_UNAVAILABLE\x10\x05*\xaa\x01\n" +
	"\vActionOwner\x12\x1c\n" +
	"\x18ACTION_OWNER_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTION_OWNER_USER\x10\x01\x12%\n" +
	"!ACTION_OWNER_DEVICE_ADMINISTRATOR\x10\x02\x12%\n" +
	"!ACTION_OWNER_ACCESS_ADMINISTRATOR\x10\x03\x12\x18\n" +
	"\x14ACTION_OWNER_SUPPORT\x10\x04*\x9b\a\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x1e\n" +
	"\x1aERROR_CODE_UNAUTHENTICATED\x10\x02\x12\x1d\n" +
	"\x19ERROR_CODE_OWNER_REQUIRED\x10\x03\x12%\n" +
	"!ERROR_CODE_ADMINISTRATOR_REQUIRED\x10\x04\x12\x1a\n" +
	"\x16ERROR_CODE_UNSUPPORTED\x10\x05\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x06\x12\x1a\n" +
	"\x16ERROR_CODE_STALE_STATE\x10\a\x12\x1d\n" +
	"\x19ERROR_CODE_POLICY_BLOCKED\x10\b\x12\"\n" +
	"\x1eERROR_CODE_PERMISSION_REQUIRED\x10\t\x12\x13\n" +
	"\x0fERROR_CODE_BUSY\x10\n" +
	"\x12\x1d\n" +
	"\x19ERROR_CODE_LIMIT_EXCEEDED\x10\v\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\f\x12 \n" +
	"\x1cERROR_CODE_DEADLINE_EXCEEDED\x10\r\x12\x18\n" +
	"\x14ERROR_CODE_CANCELLED\x10\x0e\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x0f\x12\x1f\n" +
	"\x1bERROR_CODE_NEEDS_ENROLLMENT\x10\x10\x12\x1a\n" +
	"\x16ERROR_CODE_NEEDS_LOGIN\x10\x11\x12 \n" +
	"\x1cERROR_CODE_APPROVAL_REQUIRED\x10\x12\x12 \n" +
	"\x1cERROR_CODE_APPROVAL_REJECTED\x10\x13\x12&\n" +
	"\"ERROR_CODE_SERVER_IDENTITY_CHANGED\x10\x14\x12-\n" +
	")ERROR_CODE_IDENTITY_CONFIRMATION_MISMATCH\x10\x15\x12&\n" +
	"\"ERROR_CODE_REMOTE_CLEANUP_REQUIRED\x10\x16\x121\n" +
	"-ERROR_CODE_LOCAL_FORGET_CONFIRMATION_REQUIRED\x10\x17\x12\x1b\n" +
	"\x17ERROR_CODE_APPLY_FAILED\x10\x18\x12\x1d\n" +
	"\x19ERROR_CODE_PROFILE_ACTIVE\x10\x19\x12 \n" +
	"\x1cERROR_CODE_RESOURCE_CONFLICT\x10\x1a\x12 \n" +
	"\x1cERROR_CODE_CONTRACT_MISMATCH\x10\x1b*\xeb\x01\n" +
	"\x0eOperationState\x12\x1f\n" +
	"\x1bOPERATION_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OPERATION_STATE_PENDING\x10\x01\x12\x1b\n" +
	"\x17OPERATION_STATE_RUNNING\x10\x02\x12$\n" +
	" OPERATION_STATE_WAITING_FOR_USER\x10\x03\x12\x1d\n" +
	"\x19OPERATION_STATE_SUCCEEDED\x10\x04\x12\x1a\n" +
	"\x16OPERATION_STATE_FAILED\x10\x05\x12\x1d\n" +
	"\x19OPERATION_STATE_CANCELLED\x10\x06*\xd6\x01\n" +
	"\x14ConnectionContinuity\x12%\n" +
	"!CONNECTION_CONTINUITY_UNSPECIFIED\x10\x00\x12(\n" +
	"$CONNECTION_CONTINUITY_NOT_APPLICABLE\x10\x01\x12#\n" +
	"\x1fCONNECTION_CONTINUITY_PRESERVED\x10\x02\x12%\n" +
	"!CONNECTION_CONTINUITY_INTERRUPTED\x10\x03\x12!\n" +
	"\x1dCONNECTION_CONTINUITY_UNKNOWN\x10\x04*\xa3\x01\n" +
	"\x0eCleanupOutcome\x12\x1f\n" +
	"\x1bCLEANUP_OUTCOME_UNSPECIFIED\x10\x00\x12$\n" +
	" CLEANUP_OUTCOME_REMOTE_CONFIRMED\x10\x01\x12&\n" +
	"\"CLEANUP_OUTCOME_REMOTE_UNCONFIRMED\x10\x02\x12\"\n" +
	"\x1eCLEANUP_OUTCOME_NOT_REGISTERED\x10\x03*\xd6\x05\n" +
	"\rOperationKind\x12\x1e\n" +
	"\x1aOPERATION_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OPERATION_KIND_ENROLL\x10\x01\x12\x1a\n" +
	"\x16OPERATION_KIND_CONNECT\x10\x02\x12\x1d\n" +
	"\x19OPERATION_KIND_DISCONNECT\x10\x03\x12(\n" +
	"$OPERATION_KIND_TRUST_SERVER_IDENTITY\x10\x04\x12\x19\n" +
	"\x15OPERATION_KIND_LOGOUT\x10\x05\x12*\n" +
	"&OPERATION_KIND_FORGET_LOCAL_ENROLLMENT\x10\x06\x12!\n" +
	"\x1dOPERATION_KIND_SELECT_NETWORK\x10\a\x12,\n" +
	"(OPERATION_KIND_CREATE_DIAGNOSTICS_BUNDLE\x10\b\x12!\n" +
	"\x1dOPERATION_KIND_CREATE_PROFILE\x10\t\x12!\n" +
	"\x1dOPERATION_KIND_SELECT_PROFILE\x10\n" +
	"\x12!\n" +
	"\x1dOPERATION_KIND_RENAME_PROFILE\x10\v\x12!\n" +
	"\x1dOPERATION_KIND_REMOVE_PROFILE\x10\f\x12 \n" +
	"\x1cOPERATION_KIND_RENEW_SESSION\x10\r\x12#\n" +
	"\x1fOPERATION_KIND_SELECT_EXIT_NODE\x10\x0e\x12\"\n" +
	"\x1eOPERATION_KIND_CLEAR_EXIT_NODE\x10\x0f\x12\"\n" +
	"\x1eOPERATION_KIND_SET_PREFERENCES\x10\x10\x12$\n" +
	" OPERATION_KIND_RESET_PREFERENCES\x10\x11\x12'\n" +
	"#OPERATION_KIND_SET_RESOURCE_ENABLED\x10\x12\x12#\n" +
	"\x1fOPERATION_KIND_NOTIFY_LIFECYCLE\x10\x13:K\n" +
	"\x06access\x12\x1e.google.protobuf.MethodOptions\x18\xb8\x8e\x03 \x01(\x0e2\x11.client.v0.AccessR\x06access:e\n" +
	"\x1eallows_initial_ownership_claim\x12\x1e.google.protobuf.MethodOptions\x18\xb9\x8e\x03 \x01(\bR\x1ballowsInitialOwnershipClaim:a\n" +
	"\x0eoperation_kind\x12\x1e.google.protobuf.MethodOptions\x18\xba\x8e\x03 \x01(\x0e2\x18.client.v0.OperationKindR\roperationKindB6Z4github.com/endless-net/client/clientipc/v0;clientipcb\x06proto3"

var (
	file_client_v0_common_proto_rawDescOnce sync.Once
	file_client_v0_common_proto_rawDescData []byte
)

func file_client_v0_common_proto_rawDescGZIP() []byte {
	file_client_v0_common_proto_rawDescOnce.Do(func() {
		file_client_v0_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v0_common_proto_rawDesc), len(file_client_v0_common_proto_rawDesc)))
	})
	return file_client_v0_common_proto_rawDescData
}

var file_client_v0_common_proto_enumTypes = make([]protoimpl.EnumInfo, 11)
var file_client_v0_common_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_client_v0_common_proto_goTypes = []any{
	(Access)(0),                        // 0: client.v0.Access
	(Platform)(0),                      // 1: client.v0.Platform
	(Capability)(0),                    // 2: client.v0.Capability
	(Availability)(0),                  // 3: client.v0.Availability
	(ActionOwner)(0),                   // 4: client.v0.ActionOwner
	(ErrorCode)(0),                     // 5: client.v0.ErrorCode
	(OperationState)(0),                // 6: client.v0.OperationState
	(ConnectionContinuity)(0),          // 7: client.v0.ConnectionContinuity
	(CleanupOutcome)(0),                // 8: client.v0.CleanupOutcome
	(OperationKind)(0),                 // 9: client.v0.OperationKind
	(UserAction_Kind)(0),               // 10: client.v0.UserAction.Kind
	(*Restriction)(nil),                // 11: client.v0.Restriction
	(*CapabilityStatus)(nil),           // 12: client.v0.CapabilityStatus
	(*BuildIdentity)(nil),              // 13: client.v0.BuildIdentity
	(*RuntimeInfo)(nil),                // 14: client.v0.RuntimeInfo
	(*SnapshotMetadata)(nil),           // 15: client.v0.SnapshotMetadata
	(*ProfileRef)(nil),                 // 16: client.v0.ProfileRef
	(*MutationContext)(nil),            // 17: client.v0.MutationContext
	(*Failure)(nil),                    // 18: client.v0.Failure
	(*UserAction)(nil),                 // 19: client.v0.UserAction
	(*ChangeResult)(nil),               // 20: client.v0.ChangeResult
	(*EnrollmentResult)(nil),           // 21: client.v0.EnrollmentResult
	(*SelectionResult)(nil),            // 22: client.v0.SelectionResult
	(*CleanupResult)(nil),              // 23: client.v0.CleanupResult
	(*RenewalResult)(nil),              // 24: client.v0.RenewalResult
	(*BundleResult)(nil),               // 25: client.v0.BundleResult
	(*Operation)(nil),                  // 26: client.v0.Operation
	(*PageRequest)(nil),                // 27: client.v0.PageRequest
	(*PageResponse)(nil),               // 28: client.v0.PageResponse
	(*timestamppb.Timestamp)(nil),      // 29: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 30: google.protobuf.Duration
	(*descriptorpb.MethodOptions)(nil), // 31: google.protobuf.MethodOptions
}
var file_client_v0_common_proto_depIdxs = []int32{
	3,  // 0: client.v0.Restriction.availability:type_name -> client.v0.Availability
	4,  // 1: client.v0.Restriction.action_owner:type_name -> client.v0.ActionOwner
	2,  // 2: client.v0.CapabilityStatus.capability:type_name -> client.v0.Capability
	11, // 3: client.v0.CapabilityStatus.restriction:type_name -> client.v0.Restriction
	1,  // 4: client.v0.CapabilityStatus.platform:type_name -> client.v0.Platform
	1,  // 5: client.v0.BuildIdentity.platform:type_name -> client.v0.Platform
	13, // 6: client.v0.RuntimeInfo.build:type_name -> client.v0.BuildIdentity
	12, // 7: client.v0.RuntimeInfo.capabilities:type_name -> client.v0.CapabilityStatus
	0,  // 8: client.v0.RuntimeInfo.caller_access:type_name -> client.v0.Access
	29, // 9: client.v0.SnapshotMetadata.generated_at:type_name -> google.protobuf.Timestamp
	5,  // 10: client.v0.Failure.code:type_name -> client.v0.ErrorCode
	30, // 11: client.v0.Failure.retry_after:type_name -> google.protobuf.Duration
	4,  // 12: client.v0.Failure.action_owner:type_name -> client.v0.ActionOwner
	10, // 13: client.v0.UserAction.kind:type_name -> client.v0.UserAction.Kind
	29, // 14: client.v0.UserAction.expires_at:type_name -> google.protobuf.Timestamp
	8,  // 15: client.v0.CleanupResult.outcome:type_name -> client.v0.CleanupOutcome
	29, // 16: client.v0.RenewalResult.expires_at:type_name -> google.protobuf.Timestamp
	29, // 17: client.v0.BundleResult.created_at:type_name -> google.protobuf.Timestamp
	29, // 18: client.v0.BundleResult.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 19: client.v0.Operation.state:type_name -> client.v0.OperationState
	15, // 20: client.v0.Operation.metadata:type_name -> client.v0.SnapshotMetadata
	19, // 21: client.v0.Operation.user_action:type_name -> client.v0.UserAction
	7,  // 22: client.v0.Operation.continuity:type_name -> client.v0.ConnectionContinuity
	9,  // 23: client.v0.Operation.kind:type_name -> client.v0.OperationKind
	18, // 24: client.v0.Operation.failure:type_name -> client.v0.Failure
	20, // 25: client.v0.Operation.change:type_name -> client.v0.ChangeResult
	21, // 26: client.v0.Operation.enrollment:type_name -> client.v0.EnrollmentResult
	22, // 27: client.v0.Operation.selection:type_name -> client.v0.SelectionResult
	23, // 28: client.v0.Operation.cleanup:type_name -> client.v0.CleanupResult
	24, // 29: client.v0.Operation.renewal:type_name -> client.v0.RenewalResult
	25, // 30: client.v0.Operation.bundle:type_name -> client.v0.BundleResult
	15, // 31: client.v0.PageResponse.metadata:type_name -> client.v0.SnapshotMetadata
	31, // 32: client.v0.access:extendee -> google.protobuf.MethodOptions
	31, // 33: client.v0.allows_initial_ownership_claim:extendee -> google.protobuf.MethodOptions
	31, // 34: client.v0.operation_kind:extendee -> google.protobuf.MethodOptions
	0,  // 35: client.v0.access:type_name -> client.v0.Access
	9,  // 36: client.v0.operation_kind:type_name -> client.v0.OperationKind
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	35, // [35:37] is the sub-list for extension type_name
	32, // [32:35] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_client_v0_common_proto_init() }
func file_client_v0_common_proto_init() {
	if File_client_v0_common_proto != nil {
		return
	}
	file_client_v0_common_proto_msgTypes[15].OneofWrappers = []any{
		(*Operation_Failure)(nil),
		(*Operation_Change)(nil),
		(*Operation_Enrollment)(nil),
		(*Operation_Selection)(nil),
		(*Operation_Cleanup)(nil),
		(*Operation_Renewal)(nil),
		(*Operation_Bundle)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v0_common_proto_rawDesc), len(file_client_v0_common_proto_rawDesc)),
			NumEnums:      11,
			NumMessages:   18,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_client_v0_common_proto_goTypes,
		DependencyIndexes: file_client_v0_common_proto_depIdxs,
		EnumInfos:         file_client_v0_common_proto_enumTypes,
		MessageInfos:      file_client_v0_common_proto_msgTypes,
		ExtensionInfos:    file_client_v0_common_proto_extTypes,
	}.Build()
	File_client_v0_common_proto = out.File
	file_client_v0_common_proto_goTypes = nil
	file_client_v0_common_proto_depIdxs = nil
}
