// Contract extensions for UF-08 and UF-16..UF-23.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: client/v0/features.proto

package clientipc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingSource int32

const (
	SettingSource_SETTING_SOURCE_UNSPECIFIED    SettingSource = 0
	SettingSource_SETTING_SOURCE_DEFAULT        SettingSource = 1
	SettingSource_SETTING_SOURCE_USER           SettingSource = 2
	SettingSource_SETTING_SOURCE_DEVICE_POLICY  SettingSource = 3
	SettingSource_SETTING_SOURCE_ACCOUNT_POLICY SettingSource = 4
	SettingSource_SETTING_SOURCE_PLATFORM       SettingSource = 5
)

// Enum value maps for SettingSource.
var (
	SettingSource_name = map[int32]string{
		0: "SETTING_SOURCE_UNSPECIFIED",
		1: "SETTING_SOURCE_DEFAULT",
		2: "SETTING_SOURCE_USER",
		3: "SETTING_SOURCE_DEVICE_POLICY",
		4: "SETTING_SOURCE_ACCOUNT_POLICY",
		5: "SETTING_SOURCE_PLATFORM",
	}
	SettingSource_value = map[string]int32{
		"SETTING_SOURCE_UNSPECIFIED":    0,
		"SETTING_SOURCE_DEFAULT":        1,
		"SETTING_SOURCE_USER":           2,
		"SETTING_SOURCE_DEVICE_POLICY":  3,
		"SETTING_SOURCE_ACCOUNT_POLICY": 4,
		"SETTING_SOURCE_PLATFORM":       5,
	}
)

func (x SettingSource) Enum() *SettingSource {
	p := new(SettingSource)
	*p = x
	return p
}

func (x SettingSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SettingSource) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[0].Descriptor()
}

func (SettingSource) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[0]
}

func (x SettingSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SettingSource.Descriptor instead.
func (SettingSource) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{0}
}

type LifecycleBehavior int32

const (
	LifecycleBehavior_LIFECYCLE_BEHAVIOR_UNSPECIFIED      LifecycleBehavior = 0
	LifecycleBehavior_LIFECYCLE_BEHAVIOR_KEEP_INTENT      LifecycleBehavior = 1
	LifecycleBehavior_LIFECYCLE_BEHAVIOR_CONNECT          LifecycleBehavior = 2
	LifecycleBehavior_LIFECYCLE_BEHAVIOR_DISCONNECT       LifecycleBehavior = 3
	LifecycleBehavior_LIFECYCLE_BEHAVIOR_PLATFORM_MANAGED LifecycleBehavior = 4
)

// Enum value maps for LifecycleBehavior.
var (
	LifecycleBehavior_name = map[int32]string{
		0: "LIFECYCLE_BEHAVIOR_UNSPECIFIED",
		1: "LIFECYCLE_BEHAVIOR_KEEP_INTENT",
		2: "LIFECYCLE_BEHAVIOR_CONNECT",
		3: "LIFECYCLE_BEHAVIOR_DISCONNECT",
		4: "LIFECYCLE_BEHAVIOR_PLATFORM_MANAGED",
	}
	LifecycleBehavior_value = map[string]int32{
		"LIFECYCLE_BEHAVIOR_UNSPECIFIED":      0,
		"LIFECYCLE_BEHAVIOR_KEEP_INTENT":      1,
		"LIFECYCLE_BEHAVIOR_CONNECT":          2,
		"LIFECYCLE_BEHAVIOR_DISCONNECT":       3,
		"LIFECYCLE_BEHAVIOR_PLATFORM_MANAGED": 4,
	}
)

func (x LifecycleBehavior) Enum() *LifecycleBehavior {
	p := new(LifecycleBehavior)
	*p = x
	return p
}

func (x LifecycleBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[1].Descriptor()
}

func (LifecycleBehavior) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[1]
}

func (x LifecycleBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleBehavior.Descriptor instead.
func (LifecycleBehavior) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{1}
}

type PreferenceKey int32

const (
	PreferenceKey_PREFERENCE_KEY_UNSPECIFIED   PreferenceKey = 0
	PreferenceKey_PREFERENCE_KEY_ALLOW_INBOUND PreferenceKey = 1
	PreferenceKey_PREFERENCE_KEY_ACCEPT_DNS    PreferenceKey = 2
	PreferenceKey_PREFERENCE_KEY_ACCEPT_ROUTES PreferenceKey = 3
	PreferenceKey_PREFERENCE_KEY_RUNTIME_START PreferenceKey = 4
	PreferenceKey_PREFERENCE_KEY_UI_QUIT       PreferenceKey = 5
	PreferenceKey_PREFERENCE_KEY_USER_LOGOFF   PreferenceKey = 6
	PreferenceKey_PREFERENCE_KEY_SUSPEND       PreferenceKey = 7
	PreferenceKey_PREFERENCE_KEY_RESUME        PreferenceKey = 8
)

// Enum value maps for PreferenceKey.
var (
	PreferenceKey_name = map[int32]string{
		0: "PREFERENCE_KEY_UNSPECIFIED",
		1: "PREFERENCE_KEY_ALLOW_INBOUND",
		2: "PREFERENCE_KEY_ACCEPT_DNS",
		3: "PREFERENCE_KEY_ACCEPT_ROUTES",
		4: "PREFERENCE_KEY_RUNTIME_START",
		5: "PREFERENCE_KEY_UI_QUIT",
		6: "PREFERENCE_KEY_USER_LOGOFF",
		7: "PREFERENCE_KEY_SUSPEND",
		8: "PREFERENCE_KEY_RESUME",
	}
	PreferenceKey_value = map[string]int32{
		"PREFERENCE_KEY_UNSPECIFIED":   0,
		"PREFERENCE_KEY_ALLOW_INBOUND": 1,
		"PREFERENCE_KEY_ACCEPT_DNS":    2,
		"PREFERENCE_KEY_ACCEPT_ROUTES": 3,
		"PREFERENCE_KEY_RUNTIME_START": 4,
		"PREFERENCE_KEY_UI_QUIT":       5,
		"PREFERENCE_KEY_USER_LOGOFF":   6,
		"PREFERENCE_KEY_SUSPEND":       7,
		"PREFERENCE_KEY_RESUME":        8,
	}
)

func (x PreferenceKey) Enum() *PreferenceKey {
	p := new(PreferenceKey)
	*p = x
	return p
}

func (x PreferenceKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PreferenceKey) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[2].Descriptor()
}

func (PreferenceKey) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[2]
}

func (x PreferenceKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PreferenceKey.Descriptor instead.
func (PreferenceKey) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{2}
}

type LanAccess int32

const (
	LanAccess_LAN_ACCESS_UNSPECIFIED LanAccess = 0
	LanAccess_LAN_ACCESS_BLOCK       LanAccess = 1
	LanAccess_LAN_ACCESS_ALLOW       LanAccess = 2
)

// Enum value maps for LanAccess.
var (
	LanAccess_name = map[int32]string{
		0: "LAN_ACCESS_UNSPECIFIED",
		1: "LAN_ACCESS_BLOCK",
		2: "LAN_ACCESS_ALLOW",
	}
	LanAccess_value = map[string]int32{
		"LAN_ACCESS_UNSPECIFIED": 0,
		"LAN_ACCESS_BLOCK":       1,
		"LAN_ACCESS_ALLOW":       2,
	}
)

func (x LanAccess) Enum() *LanAccess {
	p := new(LanAccess)
	*p = x
	return p
}

func (x LanAccess) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LanAccess) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[3].Descriptor()
}

func (LanAccess) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[3]
}

func (x LanAccess) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LanAccess.Descriptor instead.
func (LanAccess) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{3}
}

// NONE is a status-only cleared selection, never a SelectExitNode mode.
type ExitFamilyMode int32

const (
	ExitFamilyMode_EXIT_FAMILY_MODE_UNSPECIFIED ExitFamilyMode = 0
	ExitFamilyMode_EXIT_FAMILY_MODE_NONE        ExitFamilyMode = 1
	ExitFamilyMode_EXIT_FAMILY_MODE_IPV4_ONLY   ExitFamilyMode = 2
	ExitFamilyMode_EXIT_FAMILY_MODE_IPV6_ONLY   ExitFamilyMode = 3
	ExitFamilyMode_EXIT_FAMILY_MODE_DUAL_STACK  ExitFamilyMode = 4
)

// Enum value maps for ExitFamilyMode.
var (
	ExitFamilyMode_name = map[int32]string{
		0: "EXIT_FAMILY_MODE_UNSPECIFIED",
		1: "EXIT_FAMILY_MODE_NONE",
		2: "EXIT_FAMILY_MODE_IPV4_ONLY",
		3: "EXIT_FAMILY_MODE_IPV6_ONLY",
		4: "EXIT_FAMILY_MODE_DUAL_STACK",
	}
	ExitFamilyMode_value = map[string]int32{
		"EXIT_FAMILY_MODE_UNSPECIFIED": 0,
		"EXIT_FAMILY_MODE_NONE":        1,
		"EXIT_FAMILY_MODE_IPV4_ONLY":   2,
		"EXIT_FAMILY_MODE_IPV6_ONLY":   3,
		"EXIT_FAMILY_MODE_DUAL_STACK":  4,
	}
)

func (x ExitFamilyMode) Enum() *ExitFamilyMode {
	p := new(ExitFamilyMode)
	*p = x
	return p
}

func (x ExitFamilyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExitFamilyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[4].Descriptor()
}

func (ExitFamilyMode) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[4]
}

func (x ExitFamilyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExitFamilyMode.Descriptor instead.
func (ExitFamilyMode) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{4}
}

type ApplyState int32

const (
	ApplyState_APPLY_STATE_UNSPECIFIED ApplyState = 0
	ApplyState_APPLY_STATE_PENDING     ApplyState = 1
	ApplyState_APPLY_STATE_APPLIED     ApplyState = 2
	ApplyState_APPLY_STATE_FAILED      ApplyState = 3
)

// Enum value maps for ApplyState.
var (
	ApplyState_name = map[int32]string{
		0: "APPLY_STATE_UNSPECIFIED",
		1: "APPLY_STATE_PENDING",
		2: "APPLY_STATE_APPLIED",
		3: "APPLY_STATE_FAILED",
	}
	ApplyState_value = map[string]int32{
		"APPLY_STATE_UNSPECIFIED": 0,
		"APPLY_STATE_PENDING":     1,
		"APPLY_STATE_APPLIED":     2,
		"APPLY_STATE_FAILED":      3,
	}
)

func (x ApplyState) Enum() *ApplyState {
	p := new(ApplyState)
	*p = x
	return p
}

func (x ApplyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplyState) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[5].Descriptor()
}

func (ApplyState) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[5]
}

func (x ApplyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplyState.Descriptor instead.
func (ApplyState) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{5}
}

type ResourceKind int32

const (
	ResourceKind_RESOURCE_KIND_UNSPECIFIED ResourceKind = 0
	ResourceKind_RESOURCE_KIND_HOST        ResourceKind = 1
	ResourceKind_RESOURCE_KIND_SUBNET      ResourceKind = 2
	ResourceKind_RESOURCE_KIND_SERVICE     ResourceKind = 3
	ResourceKind_RESOURCE_KIND_APPLICATION ResourceKind = 4
)

// Enum value maps for ResourceKind.
var (
	ResourceKind_name = map[int32]string{
		0: "RESOURCE_KIND_UNSPECIFIED",
		1: "RESOURCE_KIND_HOST",
		2: "RESOURCE_KIND_SUBNET",
		3: "RESOURCE_KIND_SERVICE",
		4: "RESOURCE_KIND_APPLICATION",
	}
	ResourceKind_value = map[string]int32{
		"RESOURCE_KIND_UNSPECIFIED": 0,
		"RESOURCE_KIND_HOST":        1,
		"RESOURCE_KIND_SUBNET":      2,
		"RESOURCE_KIND_SERVICE":     3,
		"RESOURCE_KIND_APPLICATION": 4,
	}
)

func (x ResourceKind) Enum() *ResourceKind {
	p := new(ResourceKind)
	*p = x
	return p
}

func (x ResourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[6].Descriptor()
}

func (ResourceKind) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[6]
}

func (x ResourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceKind.Descriptor instead.
func (ResourceKind) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{6}
}

type UpdateClassification int32

const (
	UpdateClassification_UPDATE_CLASSIFICATION_UNSPECIFIED UpdateClassification = 0
	UpdateClassification_UPDATE_CLASSIFICATION_ORDINARY    UpdateClassification = 1
	UpdateClassification_UPDATE_CLASSIFICATION_SECURITY    UpdateClassification = 2
	UpdateClassification_UPDATE_CLASSIFICATION_MANDATORY   UpdateClassification = 3
)

// Enum value maps for UpdateClassification.
var (
	UpdateClassification_name = map[int32]string{
		0: "UPDATE_CLASSIFICATION_UNSPECIFIED",
		1: "UPDATE_CLASSIFICATION_ORDINARY",
		2: "UPDATE_CLASSIFICATION_SECURITY",
		3: "UPDATE_CLASSIFICATION_MANDATORY",
	}
	UpdateClassification_value = map[string]int32{
		"UPDATE_CLASSIFICATION_UNSPECIFIED": 0,
		"UPDATE_CLASSIFICATION_ORDINARY":    1,
		"UPDATE_CLASSIFICATION_SECURITY":    2,
		"UPDATE_CLASSIFICATION_MANDATORY":   3,
	}
)

func (x UpdateClassification) Enum() *UpdateClassification {
	p := new(UpdateClassification)
	*p = x
	return p
}

func (x UpdateClassification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateClassification) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[7].Descriptor()
}

func (UpdateClassification) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[7]
}

func (x UpdateClassification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateClassification.Descriptor instead.
func (UpdateClassification) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{7}
}

type DistributionChannel int32

const (
	DistributionChannel_DISTRIBUTION_CHANNEL_UNSPECIFIED     DistributionChannel = 0
	DistributionChannel_DISTRIBUTION_CHANNEL_VENDOR_PACKAGE  DistributionChannel = 1
	DistributionChannel_DISTRIBUTION_CHANNEL_PACKAGE_MANAGER DistributionChannel = 2
	DistributionChannel_DISTRIBUTION_CHANNEL_APP_STORE       DistributionChannel = 3
	DistributionChannel_DISTRIBUTION_CHANNEL_ENTERPRISE      DistributionChannel = 4
)

// Enum value maps for DistributionChannel.
var (
	DistributionChannel_name = map[int32]string{
		0: "DISTRIBUTION_CHANNEL_UNSPECIFIED",
		1: "DISTRIBUTION_CHANNEL_VENDOR_PACKAGE",
		2: "DISTRIBUTION_CHANNEL_PACKAGE_MANAGER",
		3: "DISTRIBUTION_CHANNEL_APP_STORE",
		4: "DISTRIBUTION_CHANNEL_ENTERPRISE",
	}
	DistributionChannel_value = map[string]int32{
		"DISTRIBUTION_CHANNEL_UNSPECIFIED":     0,
		"DISTRIBUTION_CHANNEL_VENDOR_PACKAGE":  1,
		"DISTRIBUTION_CHANNEL_PACKAGE_MANAGER": 2,
		"DISTRIBUTION_CHANNEL_APP_STORE":       3,
		"DISTRIBUTION_CHANNEL_ENTERPRISE":      4,
	}
)

func (x DistributionChannel) Enum() *DistributionChannel {
	p := new(DistributionChannel)
	*p = x
	return p
}

func (x DistributionChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistributionChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[8].Descriptor()
}

func (DistributionChannel) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[8]
}

func (x DistributionChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistributionChannel.Descriptor instead.
func (DistributionChannel) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{8}
}

type CompatibilityState int32

const (
	CompatibilityState_COMPATIBILITY_STATE_UNSPECIFIED  CompatibilityState = 0
	CompatibilityState_COMPATIBILITY_STATE_COMPATIBLE   CompatibilityState = 1
	CompatibilityState_COMPATIBILITY_STATE_INCOMPATIBLE CompatibilityState = 2
	CompatibilityState_COMPATIBILITY_STATE_UNKNOWN      CompatibilityState = 3
)

// Enum value maps for CompatibilityState.
var (
	CompatibilityState_name = map[int32]string{
		0: "COMPATIBILITY_STATE_UNSPECIFIED",
		1: "COMPATIBILITY_STATE_COMPATIBLE",
		2: "COMPATIBILITY_STATE_INCOMPATIBLE",
		3: "COMPATIBILITY_STATE_UNKNOWN",
	}
	CompatibilityState_value = map[string]int32{
		"COMPATIBILITY_STATE_UNSPECIFIED":  0,
		"COMPATIBILITY_STATE_COMPATIBLE":   1,
		"COMPATIBILITY_STATE_INCOMPATIBLE": 2,
		"COMPATIBILITY_STATE_UNKNOWN":      3,
	}
)

func (x CompatibilityState) Enum() *CompatibilityState {
	p := new(CompatibilityState)
	*p = x
	return p
}

func (x CompatibilityState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompatibilityState) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[9].Descriptor()
}

func (CompatibilityState) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[9]
}

func (x CompatibilityState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompatibilityState.Descriptor instead.
func (CompatibilityState) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{9}
}

type UpdateState int32

const (
	UpdateState_UPDATE_STATE_UNSPECIFIED               UpdateState = 0
	UpdateState_UPDATE_STATE_UNKNOWN                   UpdateState = 1
	UpdateState_UPDATE_STATE_UP_TO_DATE                UpdateState = 2
	UpdateState_UPDATE_STATE_AVAILABLE                 UpdateState = 3
	UpdateState_UPDATE_STATE_EXTERNAL_MANAGER_REQUIRED UpdateState = 4
	UpdateState_UPDATE_STATE_SOURCE_UNAVAILABLE        UpdateState = 5
	UpdateState_UPDATE_STATE_VERIFICATION_FAILED       UpdateState = 6
)

// Enum value maps for UpdateState.
var (
	UpdateState_name = map[int32]string{
		0: "UPDATE_STATE_UNSPECIFIED",
		1: "UPDATE_STATE_UNKNOWN",
		2: "UPDATE_STATE_UP_TO_DATE",
		3: "UPDATE_STATE_AVAILABLE",
		4: "UPDATE_STATE_EXTERNAL_MANAGER_REQUIRED",
		5: "UPDATE_STATE_SOURCE_UNAVAILABLE",
		6: "UPDATE_STATE_VERIFICATION_FAILED",
	}
	UpdateState_value = map[string]int32{
		"UPDATE_STATE_UNSPECIFIED":               0,
		"UPDATE_STATE_UNKNOWN":                   1,
		"UPDATE_STATE_UP_TO_DATE":                2,
		"UPDATE_STATE_AVAILABLE":                 3,
		"UPDATE_STATE_EXTERNAL_MANAGER_REQUIRED": 4,
		"UPDATE_STATE_SOURCE_UNAVAILABLE":        5,
		"UPDATE_STATE_VERIFICATION_FAILED":       6,
	}
)

func (x UpdateState) Enum() *UpdateState {
	p := new(UpdateState)
	*p = x
	return p
}

func (x UpdateState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateState) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[10].Descriptor()
}

func (UpdateState) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[10]
}

func (x UpdateState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateState.Descriptor instead.
func (UpdateState) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{10}
}

type LifecycleEvent int32

const (
	LifecycleEvent_LIFECYCLE_EVENT_UNSPECIFIED LifecycleEvent = 0
	LifecycleEvent_LIFECYCLE_EVENT_UI_QUIT     LifecycleEvent = 1
)

// Enum value maps for LifecycleEvent.
var (
	LifecycleEvent_name = map[int32]string{
		0: "LIFECYCLE_EVENT_UNSPECIFIED",
		1: "LIFECYCLE_EVENT_UI_QUIT",
	}
	LifecycleEvent_value = map[string]int32{
		"LIFECYCLE_EVENT_UNSPECIFIED": 0,
		"LIFECYCLE_EVENT_UI_QUIT":     1,
	}
)

func (x LifecycleEvent) Enum() *LifecycleEvent {
	p := new(LifecycleEvent)
	*p = x
	return p
}

func (x LifecycleEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_client_v0_features_proto_enumTypes[11].Descriptor()
}

func (LifecycleEvent) Type() protoreflect.EnumType {
	return &file_client_v0_features_proto_enumTypes[11]
}

func (x LifecycleEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleEvent.Descriptor instead.
func (LifecycleEvent) EnumDescriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{11}
}

type SettingControl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        SettingSource          `protobuf:"varint,1,opt,name=source,proto3,enum=client.v0.SettingSource" json:"source,omitempty"`
	Locked        bool                   `protobuf:"varint,2,opt,name=locked,proto3" json:"locked,omitempty"`
	Mutation      *Restriction           `protobuf:"bytes,3,opt,name=mutation,proto3" json:"mutation,omitempty"`
	PolicyId      string                 `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingControl) Reset() {
	*x = SettingControl{}
	mi := &file_client_v0_features_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingControl) ProtoMessage() {}

func (x *SettingControl) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingControl.ProtoReflect.Descriptor instead.
func (*SettingControl) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{0}
}

func (x *SettingControl) GetSource() SettingSource {
	if x != nil {
		return x.Source
	}
	return SettingSource_SETTING_SOURCE_UNSPECIFIED
}

func (x *SettingControl) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *SettingControl) GetMutation() *Restriction {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *SettingControl) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type BooleanSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effective     bool                   `protobuf:"varint,1,opt,name=effective,proto3" json:"effective,omitempty"`
	Requested     *bool                  `protobuf:"varint,2,opt,name=requested,proto3,oneof" json:"requested,omitempty"`
	Control       *SettingControl        `protobuf:"bytes,3,opt,name=control,proto3" json:"control,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanSetting) Reset() {
	*x = BooleanSetting{}
	mi := &file_client_v0_features_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanSetting) ProtoMessage() {}

func (x *BooleanSetting) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanSetting.ProtoReflect.Descriptor instead.
func (*BooleanSetting) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{1}
}

func (x *BooleanSetting) GetEffective() bool {
	if x != nil {
		return x.Effective
	}
	return false
}

func (x *BooleanSetting) GetRequested() bool {
	if x != nil && x.Requested != nil {
		return *x.Requested
	}
	return false
}

func (x *BooleanSetting) GetControl() *SettingControl {
	if x != nil {
		return x.Control
	}
	return nil
}

type LifecycleSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effective     LifecycleBehavior      `protobuf:"varint,1,opt,name=effective,proto3,enum=client.v0.LifecycleBehavior" json:"effective,omitempty"`
	Requested     *LifecycleBehavior     `protobuf:"varint,2,opt,name=requested,proto3,enum=client.v0.LifecycleBehavior,oneof" json:"requested,omitempty"`
	Control       *SettingControl        `protobuf:"bytes,3,opt,name=control,proto3" json:"control,omitempty"`
	AllowedValues []LifecycleBehavior    `protobuf:"varint,4,rep,packed,name=allowed_values,json=allowedValues,proto3,enum=client.v0.LifecycleBehavior" json:"allowed_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleSetting) Reset() {
	*x = LifecycleSetting{}
	mi := &file_client_v0_features_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleSetting) ProtoMessage() {}

func (x *LifecycleSetting) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleSetting.ProtoReflect.Descriptor instead.
func (*LifecycleSetting) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{2}
}

func (x *LifecycleSetting) GetEffective() LifecycleBehavior {
	if x != nil {
		return x.Effective
	}
	return LifecycleBehavior_LIFECYCLE_BEHAVIOR_UNSPECIFIED
}

func (x *LifecycleSetting) GetRequested() LifecycleBehavior {
	if x != nil && x.Requested != nil {
		return *x.Requested
	}
	return LifecycleBehavior_LIFECYCLE_BEHAVIOR_UNSPECIFIED
}

func (x *LifecycleSetting) GetControl() *SettingControl {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *LifecycleSetting) GetAllowedValues() []LifecycleBehavior {
	if x != nil {
		return x.AllowedValues
	}
	return nil
}

type RuntimeLifecycle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// These concern tunnel intent, not whether the UI window starts or closes.
	RuntimeStart  *LifecycleSetting `protobuf:"bytes,1,opt,name=runtime_start,json=runtimeStart,proto3" json:"runtime_start,omitempty"`
	UiQuit        *LifecycleSetting `protobuf:"bytes,2,opt,name=ui_quit,json=uiQuit,proto3" json:"ui_quit,omitempty"`
	UserLogoff    *LifecycleSetting `protobuf:"bytes,3,opt,name=user_logoff,json=userLogoff,proto3" json:"user_logoff,omitempty"`
	Suspend       *LifecycleSetting `protobuf:"bytes,4,opt,name=suspend,proto3" json:"suspend,omitempty"`
	Resume        *LifecycleSetting `protobuf:"bytes,5,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeLifecycle) Reset() {
	*x = RuntimeLifecycle{}
	mi := &file_client_v0_features_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeLifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeLifecycle) ProtoMessage() {}

func (x *RuntimeLifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeLifecycle.ProtoReflect.Descriptor instead.
func (*RuntimeLifecycle) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeLifecycle) GetRuntimeStart() *LifecycleSetting {
	if x != nil {
		return x.RuntimeStart
	}
	return nil
}

func (x *RuntimeLifecycle) GetUiQuit() *LifecycleSetting {
	if x != nil {
		return x.UiQuit
	}
	return nil
}

func (x *RuntimeLifecycle) GetUserLogoff() *LifecycleSetting {
	if x != nil {
		return x.UserLogoff
	}
	return nil
}

func (x *RuntimeLifecycle) GetSuspend() *LifecycleSetting {
	if x != nil {
		return x.Suspend
	}
	return nil
}

func (x *RuntimeLifecycle) GetResume() *LifecycleSetting {
	if x != nil {
		return x.Resume
	}
	return nil
}

type Preferences struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Metadata  *SnapshotMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ProfileId string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	// This switch may only restrict traffic already permitted by backend policy.
	AllowInbound  *BooleanSetting   `protobuf:"bytes,3,opt,name=allow_inbound,json=allowInbound,proto3" json:"allow_inbound,omitempty"`
	AcceptDns     *BooleanSetting   `protobuf:"bytes,4,opt,name=accept_dns,json=acceptDns,proto3" json:"accept_dns,omitempty"`
	AcceptRoutes  *BooleanSetting   `protobuf:"bytes,5,opt,name=accept_routes,json=acceptRoutes,proto3" json:"accept_routes,omitempty"`
	Lifecycle     *RuntimeLifecycle `protobuf:"bytes,6,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preferences) Reset() {
	*x = Preferences{}
	mi := &file_client_v0_features_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preferences) ProtoMessage() {}

func (x *Preferences) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preferences.ProtoReflect.Descriptor instead.
func (*Preferences) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{4}
}

func (x *Preferences) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Preferences) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Preferences) GetAllowInbound() *BooleanSetting {
	if x != nil {
		return x.AllowInbound
	}
	return nil
}

func (x *Preferences) GetAcceptDns() *BooleanSetting {
	if x != nil {
		return x.AcceptDns
	}
	return nil
}

func (x *Preferences) GetAcceptRoutes() *BooleanSetting {
	if x != nil {
		return x.AcceptRoutes
	}
	return nil
}

func (x *Preferences) GetLifecycle() *RuntimeLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

// Presence means "set user preference", omission means "leave unchanged".
// ResetPreferences removes user overrides instead of setting false/default.
type PreferencesPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllowInbound  *bool                  `protobuf:"varint,1,opt,name=allow_inbound,json=allowInbound,proto3,oneof" json:"allow_inbound,omitempty"`
	AcceptDns     *bool                  `protobuf:"varint,2,opt,name=accept_dns,json=acceptDns,proto3,oneof" json:"accept_dns,omitempty"`
	AcceptRoutes  *bool                  `protobuf:"varint,3,opt,name=accept_routes,json=acceptRoutes,proto3,oneof" json:"accept_routes,omitempty"`
	RuntimeStart  *LifecycleBehavior     `protobuf:"varint,4,opt,name=runtime_start,json=runtimeStart,proto3,enum=client.v0.LifecycleBehavior,oneof" json:"runtime_start,omitempty"`
	UiQuit        *LifecycleBehavior     `protobuf:"varint,5,opt,name=ui_quit,json=uiQuit,proto3,enum=client.v0.LifecycleBehavior,oneof" json:"ui_quit,omitempty"`
	UserLogoff    *LifecycleBehavior     `protobuf:"varint,6,opt,name=user_logoff,json=userLogoff,proto3,enum=client.v0.LifecycleBehavior,oneof" json:"user_logoff,omitempty"`
	Suspend       *LifecycleBehavior     `protobuf:"varint,7,opt,name=suspend,proto3,enum=client.v0.LifecycleBehavior,oneof" json:"suspend,omitempty"`
	Resume        *LifecycleBehavior     `protobuf:"varint,8,opt,name=resume,proto3,enum=client.v0.LifecycleBehavior,oneof" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreferencesPatch) Reset() {
	*x = PreferencesPatch{}
	mi := &file_client_v0_features_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreferencesPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreferencesPatch) ProtoMessage() {}

func (x *PreferencesPatch) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreferencesPatch.ProtoReflect.Descriptor instead.
func (*PreferencesPatch) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{5}
}

func (x *PreferencesPatch) GetAllowInbound() bool {
	if x != nil && x.AllowInbound != nil {
		return *x.AllowInbound
	}
	return false
}

func (x *PreferencesPatch) GetAcceptDns() bool {
	if x != nil && x.AcceptDns != nil {
		return *x.AcceptDns
	}
	return false
}

func (x *PreferencesPatch) GetAcceptRoutes() bool {
	if x != nil && x.AcceptRoutes != nil {
		return *x.AcceptRoutes
	}
	return false
}

func (x *PreferencesPatch) GetRuntimeStart() LifecycleBehavior {
	if x != nil && x.RuntimeStart != nil {
		return *x.RuntimeStart
	}
	return LifecycleBehavior_LIFECYCLE_BEHAVIOR_UNSPECIFIED
}

func (x *PreferencesPatch) GetUiQuit() LifecycleBehavior {
	if x != nil && x.UiQuit != nil {
		return *x.UiQuit
	}
	return LifecycleBehavior_LIFECYCLE_BEHAVIOR_UNSPECIFIED
}

func (x *PreferencesPatch) GetUserLogoff() LifecycleBehavior {
	if x != nil && x.UserLogoff != nil {
		return *x.UserLogoff
	}
	return LifecycleBehavior_LIFECYCLE_BEHAVIOR_UNSPECIFIED
}

func (x *PreferencesPatch) GetSuspend() LifecycleBehavior {
	if x != nil && x.Suspend != nil {
		return *x.Suspend
	}
	return LifecycleBehavior_LIFECYCLE_BEHAVIOR_UNSPECIFIED
}

func (x *PreferencesPatch) GetResume() LifecycleBehavior {
	if x != nil && x.Resume != nil {
		return *x.Resume
	}
	return LifecycleBehavior_LIFECYCLE_BEHAVIOR_UNSPECIFIED
}

type ManagedSetting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Closed keys for runtime-owned settings; UI-only preferences stay in UI.
	Key     PreferenceKey   `protobuf:"varint,1,opt,name=key,proto3,enum=client.v0.PreferenceKey" json:"key,omitempty"`
	Control *SettingControl `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	// Types that are valid to be assigned to EffectiveValue:
	//
	//	*ManagedSetting_BooleanValue
	//	*ManagedSetting_LifecycleValue
	EffectiveValue isManagedSetting_EffectiveValue `protobuf_oneof:"effective_value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ManagedSetting) Reset() {
	*x = ManagedSetting{}
	mi := &file_client_v0_features_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedSetting) ProtoMessage() {}

func (x *ManagedSetting) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedSetting.ProtoReflect.Descriptor instead.
func (*ManagedSetting) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{6}
}

func (x *ManagedSetting) GetKey() PreferenceKey {
	if x != nil {
		return x.Key
	}
	return PreferenceKey_PREFERENCE_KEY_UNSPECIFIED
}

func (x *ManagedSetting) GetControl() *SettingControl {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *ManagedSetting) GetEffectiveValue() isManagedSetting_EffectiveValue {
	if x != nil {
		return x.EffectiveValue
	}
	return nil
}

func (x *ManagedSetting) GetBooleanValue() bool {
	if x != nil {
		if x, ok := x.EffectiveValue.(*ManagedSetting_BooleanValue); ok {
			return x.BooleanValue
		}
	}
	return false
}

func (x *ManagedSetting) GetLifecycleValue() LifecycleBehavior {
	if x != nil {
		if x, ok := x.EffectiveValue.(*ManagedSetting_LifecycleValue); ok {
			return x.LifecycleValue
		}
	}
	return LifecycleBehavior_LIFECYCLE_BEHAVIOR_UNSPECIFIED
}

type isManagedSetting_EffectiveValue interface {
	isManagedSetting_EffectiveValue()
}

type ManagedSetting_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,3,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

type ManagedSetting_LifecycleValue struct {
	LifecycleValue LifecycleBehavior `protobuf:"varint,4,opt,name=lifecycle_value,json=lifecycleValue,proto3,enum=client.v0.LifecycleBehavior,oneof"`
}

func (*ManagedSetting_BooleanValue) isManagedSetting_EffectiveValue() {}

func (*ManagedSetting_LifecycleValue) isManagedSetting_EffectiveValue() {}

type ExitNode struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName      string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PeerId           string                 `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Selection        *Restriction           `protobuf:"bytes,4,opt,name=selection,proto3" json:"selection,omitempty"`
	AllowedLanAccess []LanAccess            `protobuf:"varint,5,rep,packed,name=allowed_lan_access,json=allowedLanAccess,proto3,enum=client.v0.LanAccess" json:"allowed_lan_access,omitempty"`
	// Exact selectable modes after platform, provider and policy restrictions.
	// Empty means not selectable; never infer dual-stack from separate modes.
	AllowedFamilyModes []ExitFamilyMode `protobuf:"varint,6,rep,packed,name=allowed_family_modes,json=allowedFamilyModes,proto3,enum=client.v0.ExitFamilyMode" json:"allowed_family_modes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExitNode) Reset() {
	*x = ExitNode{}
	mi := &file_client_v0_features_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitNode) ProtoMessage() {}

func (x *ExitNode) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitNode.ProtoReflect.Descriptor instead.
func (*ExitNode) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{7}
}

func (x *ExitNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExitNode) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ExitNode) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ExitNode) GetSelection() *Restriction {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *ExitNode) GetAllowedLanAccess() []LanAccess {
	if x != nil {
		return x.AllowedLanAccess
	}
	return nil
}

func (x *ExitNode) GetAllowedFamilyModes() []ExitFamilyMode {
	if x != nil {
		return x.AllowedFamilyModes
	}
	return nil
}

// One address family's authoritative requested/effective enforcement state.
type ExitFamilyStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestedExitNodeId *string                `protobuf:"bytes,1,opt,name=requested_exit_node_id,json=requestedExitNodeId,proto3,oneof" json:"requested_exit_node_id,omitempty"`
	EffectiveExitNodeId *string                `protobuf:"bytes,2,opt,name=effective_exit_node_id,json=effectiveExitNodeId,proto3,oneof" json:"effective_exit_node_id,omitempty"`
	ApplyState          ApplyState             `protobuf:"varint,3,opt,name=apply_state,json=applyState,proto3,enum=client.v0.ApplyState" json:"apply_state,omitempty"`
	Failure             *Failure               `protobuf:"bytes,4,opt,name=failure,proto3" json:"failure,omitempty"`
	// Actual blocking protection, not merely desired policy.
	FailClosed    bool `protobuf:"varint,5,opt,name=fail_closed,json=failClosed,proto3" json:"fail_closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitFamilyStatus) Reset() {
	*x = ExitFamilyStatus{}
	mi := &file_client_v0_features_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitFamilyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitFamilyStatus) ProtoMessage() {}

func (x *ExitFamilyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitFamilyStatus.ProtoReflect.Descriptor instead.
func (*ExitFamilyStatus) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{8}
}

func (x *ExitFamilyStatus) GetRequestedExitNodeId() string {
	if x != nil && x.RequestedExitNodeId != nil {
		return *x.RequestedExitNodeId
	}
	return ""
}

func (x *ExitFamilyStatus) GetEffectiveExitNodeId() string {
	if x != nil && x.EffectiveExitNodeId != nil {
		return *x.EffectiveExitNodeId
	}
	return ""
}

func (x *ExitFamilyStatus) GetApplyState() ApplyState {
	if x != nil {
		return x.ApplyState
	}
	return ApplyState_APPLY_STATE_UNSPECIFIED
}

func (x *ExitFamilyStatus) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *ExitFamilyStatus) GetFailClosed() bool {
	if x != nil {
		return x.FailClosed
	}
	return false
}

type ExitNodeStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Metadata            *SnapshotMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ProfileId           string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	RequestedExitNodeId *string                `protobuf:"bytes,3,opt,name=requested_exit_node_id,json=requestedExitNodeId,proto3,oneof" json:"requested_exit_node_id,omitempty"`
	EffectiveExitNodeId *string                `protobuf:"bytes,4,opt,name=effective_exit_node_id,json=effectiveExitNodeId,proto3,oneof" json:"effective_exit_node_id,omitempty"`
	RequestedLanAccess  LanAccess              `protobuf:"varint,5,opt,name=requested_lan_access,json=requestedLanAccess,proto3,enum=client.v0.LanAccess" json:"requested_lan_access,omitempty"`
	EffectiveLanAccess  LanAccess              `protobuf:"varint,6,opt,name=effective_lan_access,json=effectiveLanAccess,proto3,enum=client.v0.LanAccess" json:"effective_lan_access,omitempty"`
	ApplyState          ApplyState             `protobuf:"varint,7,opt,name=apply_state,json=applyState,proto3,enum=client.v0.ApplyState" json:"apply_state,omitempty"`
	Control             *SettingControl        `protobuf:"bytes,8,opt,name=control,proto3" json:"control,omitempty"`
	Failure             *Failure               `protobuf:"bytes,9,opt,name=failure,proto3" json:"failure,omitempty"`
	// On path loss, traffic cannot silently escape via a direct default route.
	FailClosed          bool           `protobuf:"varint,10,opt,name=fail_closed,json=failClosed,proto3" json:"fail_closed,omitempty"`
	RequestedFamilyMode ExitFamilyMode `protobuf:"varint,11,opt,name=requested_family_mode,json=requestedFamilyMode,proto3,enum=client.v0.ExitFamilyMode" json:"requested_family_mode,omitempty"`
	// Both required, including a disabled/cleared family. Partial application
	// remains visible here and cannot be reported as aggregate APPLIED.
	Ipv4          *ExitFamilyStatus `protobuf:"bytes,12,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6          *ExitFamilyStatus `protobuf:"bytes,13,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitNodeStatus) Reset() {
	*x = ExitNodeStatus{}
	mi := &file_client_v0_features_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitNodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitNodeStatus) ProtoMessage() {}

func (x *ExitNodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitNodeStatus.ProtoReflect.Descriptor instead.
func (*ExitNodeStatus) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{9}
}

func (x *ExitNodeStatus) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExitNodeStatus) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ExitNodeStatus) GetRequestedExitNodeId() string {
	if x != nil && x.RequestedExitNodeId != nil {
		return *x.RequestedExitNodeId
	}
	return ""
}

func (x *ExitNodeStatus) GetEffectiveExitNodeId() string {
	if x != nil && x.EffectiveExitNodeId != nil {
		return *x.EffectiveExitNodeId
	}
	return ""
}

func (x *ExitNodeStatus) GetRequestedLanAccess() LanAccess {
	if x != nil {
		return x.RequestedLanAccess
	}
	return LanAccess_LAN_ACCESS_UNSPECIFIED
}

func (x *ExitNodeStatus) GetEffectiveLanAccess() LanAccess {
	if x != nil {
		return x.EffectiveLanAccess
	}
	return LanAccess_LAN_ACCESS_UNSPECIFIED
}

func (x *ExitNodeStatus) GetApplyState() ApplyState {
	if x != nil {
		return x.ApplyState
	}
	return ApplyState_APPLY_STATE_UNSPECIFIED
}

func (x *ExitNodeStatus) GetControl() *SettingControl {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *ExitNodeStatus) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *ExitNodeStatus) GetFailClosed() bool {
	if x != nil {
		return x.FailClosed
	}
	return false
}

func (x *ExitNodeStatus) GetRequestedFamilyMode() ExitFamilyMode {
	if x != nil {
		return x.RequestedFamilyMode
	}
	return ExitFamilyMode_EXIT_FAMILY_MODE_UNSPECIFIED
}

func (x *ExitNodeStatus) GetIpv4() *ExitFamilyStatus {
	if x != nil {
		return x.Ipv4
	}
	return nil
}

func (x *ExitNodeStatus) GetIpv6() *ExitFamilyStatus {
	if x != nil {
		return x.Ipv6
	}
	return nil
}

type HostTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []string               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostTarget) Reset() {
	*x = HostTarget{}
	mi := &file_client_v0_features_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTarget) ProtoMessage() {}

func (x *HostTarget) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostTarget.ProtoReflect.Descriptor instead.
func (*HostTarget) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{10}
}

func (x *HostTarget) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *HostTarget) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type SubnetTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetTarget) Reset() {
	*x = SubnetTarget{}
	mi := &file_client_v0_features_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubnetTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubnetTarget) ProtoMessage() {}

func (x *SubnetTarget) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubnetTarget.ProtoReflect.Descriptor instead.
func (*SubnetTarget) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{11}
}

func (x *SubnetTarget) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type ServiceTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTarget) Reset() {
	*x = ServiceTarget{}
	mi := &file_client_v0_features_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTarget) ProtoMessage() {}

func (x *ServiceTarget) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTarget.ProtoReflect.Descriptor instead.
func (*ServiceTarget) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceTarget) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ServiceTarget) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceTarget) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ApplicationTarget struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DisplayAddress string                 `protobuf:"bytes,1,opt,name=display_address,json=displayAddress,proto3" json:"display_address,omitempty"`
	// Validated HTTPS link when the authorized resource supports a browser.
	BrowserUrl    string `protobuf:"bytes,2,opt,name=browser_url,json=browserUrl,proto3" json:"browser_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationTarget) Reset() {
	*x = ApplicationTarget{}
	mi := &file_client_v0_features_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationTarget) ProtoMessage() {}

func (x *ApplicationTarget) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationTarget.ProtoReflect.Descriptor instead.
func (*ApplicationTarget) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{13}
}

func (x *ApplicationTarget) GetDisplayAddress() string {
	if x != nil {
		return x.DisplayAddress
	}
	return ""
}

func (x *ApplicationTarget) GetBrowserUrl() string {
	if x != nil {
		return x.BrowserUrl
	}
	return ""
}

type Resource struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName  string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Kind         ResourceKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=client.v0.ResourceKind" json:"kind,omitempty"`
	NetworkId    string                 `protobuf:"bytes,4,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	Availability *Restriction           `protobuf:"bytes,5,opt,name=availability,proto3" json:"availability,omitempty"`
	Enabled      *BooleanSetting        `protobuf:"bytes,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// IDs refer only to resources disclosed to this caller; never hidden resources.
	OverlappingResourceIds []string `protobuf:"bytes,7,rep,name=overlapping_resource_ids,json=overlappingResourceIds,proto3" json:"overlapping_resource_ids,omitempty"`
	OverlapReasonKey       string   `protobuf:"bytes,8,opt,name=overlap_reason_key,json=overlapReasonKey,proto3" json:"overlap_reason_key,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*Resource_Host
	//	*Resource_Subnet
	//	*Resource_Service
	//	*Resource_Application
	Target        isResource_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_client_v0_features_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{14}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Resource) GetKind() ResourceKind {
	if x != nil {
		return x.Kind
	}
	return ResourceKind_RESOURCE_KIND_UNSPECIFIED
}

func (x *Resource) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *Resource) GetAvailability() *Restriction {
	if x != nil {
		return x.Availability
	}
	return nil
}

func (x *Resource) GetEnabled() *BooleanSetting {
	if x != nil {
		return x.Enabled
	}
	return nil
}

func (x *Resource) GetOverlappingResourceIds() []string {
	if x != nil {
		return x.OverlappingResourceIds
	}
	return nil
}

func (x *Resource) GetOverlapReasonKey() string {
	if x != nil {
		return x.OverlapReasonKey
	}
	return ""
}

func (x *Resource) GetTarget() isResource_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *Resource) GetHost() *HostTarget {
	if x != nil {
		if x, ok := x.Target.(*Resource_Host); ok {
			return x.Host
		}
	}
	return nil
}

func (x *Resource) GetSubnet() *SubnetTarget {
	if x != nil {
		if x, ok := x.Target.(*Resource_Subnet); ok {
			return x.Subnet
		}
	}
	return nil
}

func (x *Resource) GetService() *ServiceTarget {
	if x != nil {
		if x, ok := x.Target.(*Resource_Service); ok {
			return x.Service
		}
	}
	return nil
}

func (x *Resource) GetApplication() *ApplicationTarget {
	if x != nil {
		if x, ok := x.Target.(*Resource_Application); ok {
			return x.Application
		}
	}
	return nil
}

type isResource_Target interface {
	isResource_Target()
}

type Resource_Host struct {
	Host *HostTarget `protobuf:"bytes,10,opt,name=host,proto3,oneof"`
}

type Resource_Subnet struct {
	Subnet *SubnetTarget `protobuf:"bytes,11,opt,name=subnet,proto3,oneof"`
}

type Resource_Service struct {
	Service *ServiceTarget `protobuf:"bytes,12,opt,name=service,proto3,oneof"`
}

type Resource_Application struct {
	Application *ApplicationTarget `protobuf:"bytes,13,opt,name=application,proto3,oneof"`
}

func (*Resource_Host) isResource_Target() {}

func (*Resource_Subnet) isResource_Target() {}

func (*Resource_Service) isResource_Target() {}

func (*Resource_Application) isResource_Target() {}

type Compatibility struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	State                  CompatibilityState     `protobuf:"varint,1,opt,name=state,proto3,enum=client.v0.CompatibilityState" json:"state,omitempty"`
	ReasonKey              string                 `protobuf:"bytes,2,opt,name=reason_key,json=reasonKey,proto3" json:"reason_key,omitempty"`
	MinimumIpcVersion      uint32                 `protobuf:"varint,3,opt,name=minimum_ipc_version,json=minimumIpcVersion,proto3" json:"minimum_ipc_version,omitempty"`
	MaximumIpcVersion      uint32                 `protobuf:"varint,4,opt,name=maximum_ipc_version,json=maximumIpcVersion,proto3" json:"maximum_ipc_version,omitempty"`
	AcceptedContractSha256 []string               `protobuf:"bytes,5,rep,name=accepted_contract_sha256,json=acceptedContractSha256,proto3" json:"accepted_contract_sha256,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Compatibility) Reset() {
	*x = Compatibility{}
	mi := &file_client_v0_features_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compatibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compatibility) ProtoMessage() {}

func (x *Compatibility) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compatibility.ProtoReflect.Descriptor instead.
func (*Compatibility) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{15}
}

func (x *Compatibility) GetState() CompatibilityState {
	if x != nil {
		return x.State
	}
	return CompatibilityState_COMPATIBILITY_STATE_UNSPECIFIED
}

func (x *Compatibility) GetReasonKey() string {
	if x != nil {
		return x.ReasonKey
	}
	return ""
}

func (x *Compatibility) GetMinimumIpcVersion() uint32 {
	if x != nil {
		return x.MinimumIpcVersion
	}
	return 0
}

func (x *Compatibility) GetMaximumIpcVersion() uint32 {
	if x != nil {
		return x.MaximumIpcVersion
	}
	return 0
}

func (x *Compatibility) GetAcceptedContractSha256() []string {
	if x != nil {
		return x.AcceptedContractSha256
	}
	return nil
}

type VerifiedUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Producer verifies signature, expiry, target and pairing before disclosure.
	ReleaseId       string                 `protobuf:"bytes,1,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	ManifestSha256  string                 `protobuf:"bytes,2,opt,name=manifest_sha256,json=manifestSha256,proto3" json:"manifest_sha256,omitempty"`
	SigningKeyId    string                 `protobuf:"bytes,3,opt,name=signing_key_id,json=signingKeyId,proto3" json:"signing_key_id,omitempty"`
	VerifiedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Runtime         *BuildIdentity         `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	PairedUiVersion string                 `protobuf:"bytes,7,opt,name=paired_ui_version,json=pairedUiVersion,proto3" json:"paired_ui_version,omitempty"`
	Compatibility   *Compatibility         `protobuf:"bytes,8,opt,name=compatibility,proto3" json:"compatibility,omitempty"`
	Classification  UpdateClassification   `protobuf:"varint,9,opt,name=classification,proto3,enum=client.v0.UpdateClassification" json:"classification,omitempty"`
	Channel         DistributionChannel    `protobuf:"varint,10,opt,name=channel,proto3,enum=client.v0.DistributionChannel" json:"channel,omitempty"`
	MandatoryAfter  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=mandatory_after,json=mandatoryAfter,proto3" json:"mandatory_after,omitempty"`
	// Validated destination for the platform package/store owner.
	ActionUrl       string `protobuf:"bytes,12,opt,name=action_url,json=actionUrl,proto3" json:"action_url,omitempty"`
	ReleaseNotesUrl string `protobuf:"bytes,13,opt,name=release_notes_url,json=releaseNotesUrl,proto3" json:"release_notes_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifiedUpdate) Reset() {
	*x = VerifiedUpdate{}
	mi := &file_client_v0_features_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifiedUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifiedUpdate) ProtoMessage() {}

func (x *VerifiedUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifiedUpdate.ProtoReflect.Descriptor instead.
func (*VerifiedUpdate) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{16}
}

func (x *VerifiedUpdate) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

func (x *VerifiedUpdate) GetManifestSha256() string {
	if x != nil {
		return x.ManifestSha256
	}
	return ""
}

func (x *VerifiedUpdate) GetSigningKeyId() string {
	if x != nil {
		return x.SigningKeyId
	}
	return ""
}

func (x *VerifiedUpdate) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *VerifiedUpdate) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *VerifiedUpdate) GetRuntime() *BuildIdentity {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *VerifiedUpdate) GetPairedUiVersion() string {
	if x != nil {
		return x.PairedUiVersion
	}
	return ""
}

func (x *VerifiedUpdate) GetCompatibility() *Compatibility {
	if x != nil {
		return x.Compatibility
	}
	return nil
}

func (x *VerifiedUpdate) GetClassification() UpdateClassification {
	if x != nil {
		return x.Classification
	}
	return UpdateClassification_UPDATE_CLASSIFICATION_UNSPECIFIED
}

func (x *VerifiedUpdate) GetChannel() DistributionChannel {
	if x != nil {
		return x.Channel
	}
	return DistributionChannel_DISTRIBUTION_CHANNEL_UNSPECIFIED
}

func (x *VerifiedUpdate) GetMandatoryAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.MandatoryAfter
	}
	return nil
}

func (x *VerifiedUpdate) GetActionUrl() string {
	if x != nil {
		return x.ActionUrl
	}
	return ""
}

func (x *VerifiedUpdate) GetReleaseNotesUrl() string {
	if x != nil {
		return x.ReleaseNotesUrl
	}
	return ""
}

type UpdateInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Metadata         *SnapshotMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	InstalledRuntime *BuildIdentity         `protobuf:"bytes,2,opt,name=installed_runtime,json=installedRuntime,proto3" json:"installed_runtime,omitempty"`
	// UI identity is a caller claim for pairing checks, never runtime attestation.
	ReportedUi    *BuildIdentity  `protobuf:"bytes,3,opt,name=reported_ui,json=reportedUi,proto3" json:"reported_ui,omitempty"`
	InstalledPair *Compatibility  `protobuf:"bytes,4,opt,name=installed_pair,json=installedPair,proto3" json:"installed_pair,omitempty"`
	State         UpdateState     `protobuf:"varint,5,opt,name=state,proto3,enum=client.v0.UpdateState" json:"state,omitempty"`
	Available     *VerifiedUpdate `protobuf:"bytes,6,opt,name=available,proto3" json:"available,omitempty"`
	Discovery     *Restriction    `protobuf:"bytes,7,opt,name=discovery,proto3" json:"discovery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInfo) Reset() {
	*x = UpdateInfo{}
	mi := &file_client_v0_features_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInfo) ProtoMessage() {}

func (x *UpdateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInfo.ProtoReflect.Descriptor instead.
func (*UpdateInfo) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateInfo) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateInfo) GetInstalledRuntime() *BuildIdentity {
	if x != nil {
		return x.InstalledRuntime
	}
	return nil
}

func (x *UpdateInfo) GetReportedUi() *BuildIdentity {
	if x != nil {
		return x.ReportedUi
	}
	return nil
}

func (x *UpdateInfo) GetInstalledPair() *Compatibility {
	if x != nil {
		return x.InstalledPair
	}
	return nil
}

func (x *UpdateInfo) GetState() UpdateState {
	if x != nil {
		return x.State
	}
	return UpdateState_UPDATE_STATE_UNSPECIFIED
}

func (x *UpdateInfo) GetAvailable() *VerifiedUpdate {
	if x != nil {
		return x.Available
	}
	return nil
}

func (x *UpdateInfo) GetDiscovery() *Restriction {
	if x != nil {
		return x.Discovery
	}
	return nil
}

type SupportInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Runtime          *BuildIdentity         `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	ProductName      string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	DocumentationUrl string                 `protobuf:"bytes,3,opt,name=documentation_url,json=documentationUrl,proto3" json:"documentation_url,omitempty"`
	SupportUrl       string                 `protobuf:"bytes,4,opt,name=support_url,json=supportUrl,proto3" json:"support_url,omitempty"`
	PrivacyUrl       string                 `protobuf:"bytes,5,opt,name=privacy_url,json=privacyUrl,proto3" json:"privacy_url,omitempty"`
	LicenseUrl       string                 `protobuf:"bytes,6,opt,name=license_url,json=licenseUrl,proto3" json:"license_url,omitempty"`
	// Stable offline resource key, with translated content shipped in the UI.
	OfflineHelpKey string `protobuf:"bytes,7,opt,name=offline_help_key,json=offlineHelpKey,proto3" json:"offline_help_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SupportInfo) Reset() {
	*x = SupportInfo{}
	mi := &file_client_v0_features_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportInfo) ProtoMessage() {}

func (x *SupportInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_v0_features_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportInfo.ProtoReflect.Descriptor instead.
func (*SupportInfo) Descriptor() ([]byte, []int) {
	return file_client_v0_features_proto_rawDescGZIP(), []int{18}
}

func (x *SupportInfo) GetRuntime() *BuildIdentity {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *SupportInfo) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *SupportInfo) GetDocumentationUrl() string {
	if x != nil {
		return x.DocumentationUrl
	}
	return ""
}

func (x *SupportInfo) GetSupportUrl() string {
	if x != nil {
		return x.SupportUrl
	}
	return ""
}

func (x *SupportInfo) GetPrivacyUrl() string {
	if x != nil {
		return x.PrivacyUrl
	}
	return ""
}

func (x *SupportInfo) GetLicenseUrl() string {
	if x != nil {
		return x.LicenseUrl
	}
	return ""
}

func (x *SupportInfo) GetOfflineHelpKey() string {
	if x != nil {
		return x.OfflineHelpKey
	}
	return ""
}

var File_client_v0_features_proto protoreflect.FileDescriptor

const file_client_v0_features_proto_rawDesc = "" +
	"\n" +
	"\x18client/v0/features.proto\x12\tclient.v0\x1a\x16client/v0/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n" +
	"\x0eSettingControl\x120\n" +
	"\x06source\x18\x01 \x01(\x0e2\x18.client.v0.SettingSourceR\x06source\x12\x16\n" +
	"\x06locked\x18\x02 \x01(\bR\x06locked\x122\n" +
	"\bmutation\x18\x03 \x01(\v2\x16.client.v0.RestrictionR\bmutation\x12\x1b\n" +
	"\tpolicy_id\x18\x04 \x01(\tR\bpolicyId\"\x94\x01\n" +
	"\x0eBooleanSetting\x12\x1c\n" +
	"\teffective\x18\x01 \x01(\bR\teffective\x12!\n" +
	"\trequested\x18\x02 \x01(\bH\x00R\trequested\x88\x01\x01\x123\n" +
	"\acontrol\x18\x03 \x01(\v2\x19.client.v0.SettingControlR\acontrolB\f\n" +
	"\n" +
	"_requested\"\x97\x02\n" +
	"\x10LifecycleSetting\x12:\n" +
	"\teffective\x18\x01 \x01(\x0e2\x1c.client.v0.LifecycleBehaviorR\teffective\x12?\n" +
	"\trequested\x18\x02 \x01(\x0e2\x1c.client.v0.LifecycleBehaviorH\x00R\trequested\x88\x01\x01\x123\n" +
	"\acontrol\x18\x03 \x01(\v2\x19.client.v0.SettingControlR\acontrol\x12C\n" +
	"\x0eallowed_values\x18\x04 \x03(\x0e2\x1c.client.v0.LifecycleBehaviorR\rallowedValuesB\f\n" +
	"\n" +
	"_requested\"\xb4\x02\n" +
	"\x10RuntimeLifecycle\x12@\n" +
	"\rruntime_start\x18\x01 \x01(\v2\x1b.client.v0.LifecycleSettingR\fruntimeStart\x124\n" +
	"\aui_quit\x18\x02 \x01(\v2\x1b.client.v0.LifecycleSettingR\x06uiQuit\x12<\n" +
	"\vuser_logoff\x18\x03 \x01(\v2\x1b.client.v0.LifecycleSettingR\n" +
	"userLogoff\x125\n" +
	"\asuspend\x18\x04 \x01(\v2\x1b.client.v0.LifecycleSettingR\asuspend\x123\n" +
	"\x06resume\x18\x05 \x01(\v2\x1b.client.v0.LifecycleSettingR\x06resume\"\xda\x02\n" +
	"\vPreferences\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.client.v0.SnapshotMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12>\n" +
	"\rallow_inbound\x18\x03 \x01(\v2\x19.client.v0.BooleanSettingR\fallowInbound\x128\n" +
	"\n" +
	"accept_dns\x18\x04 \x01(\v2\x19.client.v0.BooleanSettingR\tacceptDns\x12>\n" +
	"\raccept_routes\x18\x05 \x01(\v2\x19.client.v0.BooleanSettingR\facceptRoutes\x129\n" +
	"\tlifecycle\x18\x06 \x01(\v2\x1b.client.v0.RuntimeLifecycleR\tlifecycle\"\xc2\x04\n" +
	"\x10PreferencesPatch\x12(\n" +
	"\rallow_inbound\x18\x01 \x01(\bH\x00R\fallowInbound\x88\x01\x01\x12\"\n" +
	"\n" +
	"accept_dns\x18\x02 \x01(\bH\x01R\tacceptDns\x88\x01\x01\x12(\n" +
	"\raccept_routes\x18\x03 \x01(\bH\x02R\facceptRoutes\x88\x01\x01\x12F\n" +
	"\rruntime_start\x18\x04 \x01(\x0e2\x1c.client.v0.LifecycleBehaviorH\x03R\fruntimeStart\x88\x01\x01\x12:\n" +
	"\aui_quit\x18\x05 \x01(\x0e2\x1c.client.v0.LifecycleBehaviorH\x04R\x06uiQuit\x88\x01\x01\x12B\n" +
	"\vuser_logoff\x18\x06 \x01(\x0e2\x1c.client.v0.LifecycleBehaviorH\x05R\n" +
	"userLogoff\x88\x01\x01\x12;\n" +
	"\asuspend\x18\a \x01(\x0e2\x1c.client.v0.LifecycleBehaviorH\x06R\asuspend\x88\x01\x01\x129\n" +
	"\x06resume\x18\b \x01(\x0e2\x1c.client.v0.LifecycleBehaviorH\aR\x06resume\x88\x01\x01B\x10\n" +
	"\x0e_allow_inboundB\r\n" +
	"\v_accept_dnsB\x10\n" +
	"\x0e_accept_routesB\x10\n" +
	"\x0e_runtime_startB\n" +
	"\n" +
	"\b_ui_quitB\x0e\n" +
	"\f_user_logoffB\n" +
	"\n" +
	"\b_suspendB\t\n" +
	"\a_resume\"\xf4\x01\n" +
	"\x0eManagedSetting\x12*\n" +
	"\x03key\x18\x01 \x01(\x0e2\x18.client.v0.PreferenceKeyR\x03key\x123\n" +
	"\acontrol\x18\x02 \x01(\v2\x19.client.v0.SettingControlR\acontrol\x12%\n" +
	"\rboolean_value\x18\x03 \x01(\bH\x00R\fbooleanValue\x12G\n" +
	"\x0flifecycle_value\x18\x04 \x01(\x0e2\x1c.client.v0.LifecycleBehaviorH\x00R\x0elifecycleValueB\x11\n" +
	"\x0feffective_value\"\x9d\x02\n" +
	"\bExitNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\tR\x06peerId\x124\n" +
	"\tselection\x18\x04 \x01(\v2\x16.client.v0.RestrictionR\tselection\x12B\n" +
	"\x12allowed_lan_access\x18\x05 \x03(\x0e2\x14.client.v0.LanAccessR\x10allowedLanAccess\x12K\n" +
	"\x14allowed_family_modes\x18\x06 \x03(\x0e2\x19.client.v0.ExitFamilyModeR\x12allowedFamilyModes\"\xc3\x02\n" +
	"\x10ExitFamilyStatus\x128\n" +
	"\x16requested_exit_node_id\x18\x01 \x01(\tH\x00R\x13requestedExitNodeId\x88\x01\x01\x128\n" +
	"\x16effective_exit_node_id\x18\x02 \x01(\tH\x01R\x13effectiveExitNodeId\x88\x01\x01\x126\n" +
	"\vapply_state\x18\x03 \x01(\x0e2\x15.client.v0.ApplyStateR\n" +
	"applyState\x12,\n" +
	"\afailure\x18\x04 \x01(\v2\x12.client.v0.FailureR\afailure\x12\x1f\n" +
	"\vfail_closed\x18\x05 \x01(\bR\n" +
	"failClosedB\x19\n" +
	"\x17_requested_exit_node_idB\x19\n" +
	"\x17_effective_exit_node_id\"\x8f\x06\n" +
	"\x0eExitNodeStatus\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.client.v0.SnapshotMetadataR\bmetadata\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x128\n" +
	"\x16requested_exit_node_id\x18\x03 \x01(\tH\x00R\x13requestedExitNodeId\x88\x01\x01\x128\n" +
	"\x16effective_exit_node_id\x18\x04 \x01(\tH\x01R\x13effectiveExitNodeId\x88\x01\x01\x12F\n" +
	"\x14requested_lan_access\x18\x05 \x01(\x0e2\x14.client.v0.LanAccessR\x12requestedLanAccess\x12F\n" +
	"\x14effective_lan_access\x18\x06 \x01(\x0e2\x14.client.v0.LanAccessR\x12effectiveLanAccess\x126\n" +
	"\vapply_state\x18\a \x01(\x0e2\x15.client.v0.ApplyStateR\n" +
	"applyState\x123\n" +
	"\acontrol\x18\b \x01(\v2\x19.client.v0.SettingControlR\acontrol\x12,\n" +
	"\afailure\x18\t \x01(\v2\x12.client.v0.FailureR\afailure\x12\x1f\n" +
	"\vfail_closed\x18\n" +
	" \x01(\bR\n" +
	"failClosed\x12M\n" +
	"\x15requested_family_mode\x18\v \x01(\x0e2\x19.client.v0.ExitFamilyModeR\x13requestedFamilyMode\x12/\n" +
	"\x04ipv4\x18\f \x01(\v2\x1b.client.v0.ExitFamilyStatusR\x04ipv4\x12/\n" +
	"\x04ipv6\x18\r \x01(\v2\x1b.client.v0.ExitFamilyStatusR\x04ipv6B\x19\n" +
	"\x17_requested_exit_node_idB\x19\n" +
	"\x17_effective_exit_node_id\"F\n" +
	"\n" +
	"HostTarget\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\tR\taddresses\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"\"\n" +
	"\fSubnetTarget\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\"[\n" +
	"\rServiceTarget\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"]\n" +
	"\x11ApplicationTarget\x12'\n" +
	"\x0fdisplay_address\x18\x01 \x01(\tR\x0edisplayAddress\x12\x1f\n" +
	"\vbrowser_url\x18\x02 \x01(\tR\n" +
	"browserUrl\"\xc4\x04\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12+\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x17.client.v0.ResourceKindR\x04kind\x12\x1d\n" +
	"\n" +
	"network_id\x18\x04 \x01(\tR\tnetworkId\x12:\n" +
	"\favailability\x18\x05 \x01(\v2\x16.client.v0.RestrictionR\favailability\x123\n" +
	"\aenabled\x18\x06 \x01(\v2\x19.client.v0.BooleanSettingR\aenabled\x128\n" +
	"\x18overlapping_resource_ids\x18\a \x03(\tR\x16overlappingResourceIds\x12,\n" +
	"\x12overlap_reason_key\x18\b \x01(\tR\x10overlapReasonKey\x12+\n" +
	"\x04host\x18\n" +
	" \x01(\v2\x15.client.v0.HostTargetH\x00R\x04host\x121\n" +
	"\x06subnet\x18\v \x01(\v2\x17.client.v0.SubnetTargetH\x00R\x06subnet\x124\n" +
	"\aservice\x18\f \x01(\v2\x18.client.v0.ServiceTargetH\x00R\aservice\x12@\n" +
	"\vapplication\x18\r \x01(\v2\x1c.client.v0.ApplicationTargetH\x00R\vapplicationB\b\n" +
	"\x06target\"\xfd\x01\n" +
	"\rCompatibility\x123\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1d.client.v0.CompatibilityStateR\x05state\x12\x1d\n" +
	"\n" +
	"reason_key\x18\x02 \x01(\tR\treasonKey\x12.\n" +
	"\x13minimum_ipc_version\x18\x03 \x01(\rR\x11minimumIpcVersion\x12.\n" +
	"\x13maximum_ipc_version\x18\x04 \x01(\rR\x11maximumIpcVersion\x128\n" +
	"\x18accepted_contract_sha256\x18\x05 \x03(\tR\x16acceptedContractSha256\"\xa9\x05\n" +
	"\x0eVerifiedUpdate\x12\x1d\n" +
	"\n" +
	"release_id\x18\x01 \x01(\tR\treleaseId\x12'\n" +
	"\x0fmanifest_sha256\x18\x02 \x01(\tR\x0emanifestSha256\x12$\n" +
	"\x0esigning_key_id\x18\x03 \x01(\tR\fsigningKeyId\x12;\n" +
	"\vverified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x122\n" +
	"\aruntime\x18\x06 \x01(\v2\x18.client.v0.BuildIdentityR\aruntime\x12*\n" +
	"\x11paired_ui_version\x18\a \x01(\tR\x0fpairedUiVersion\x12>\n" +
	"\rcompatibility\x18\b \x01(\v2\x18.client.v0.CompatibilityR\rcompatibility\x12G\n" +
	"\x0eclassification\x18\t \x01(\x0e2\x1f.client.v0.UpdateClassificationR\x0eclassification\x128\n" +
	"\achannel\x18\n" +
	" \x01(\x0e2\x1e.client.v0.DistributionChannelR\achannel\x12C\n" +
	"\x0fmandatory_after\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0emandatoryAfter\x12\x1d\n" +
	"\n" +
	"action_url\x18\f \x01(\tR\tactionUrl\x12*\n" +
	"\x11release_notes_url\x18\r \x01(\tR\x0freleaseNotesUrl\"\xa5\x03\n" +
	"\n" +
	"UpdateInfo\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.client.v0.SnapshotMetadataR\bmetadata\x12E\n" +
	"\x11installed_runtime\x18\x02 \x01(\v2\x18.client.v0.BuildIdentityR\x10installedRuntime\x129\n" +
	"\vreported_ui\x18\x03 \x01(\v2\x18.client.v0.BuildIdentityR\n" +
	"reportedUi\x12?\n" +
	"\x0einstalled_pair\x18\x04 \x01(\v2\x18.client.v0.CompatibilityR\rinstalledPair\x12,\n" +
	"\x05state\x18\x05 \x01(\x0e2\x16.client.v0.UpdateStateR\x05state\x127\n" +
	"\tavailable\x18\x06 \x01(\v2\x19.client.v0.VerifiedUpdateR\tavailable\x124\n" +
	"\tdiscovery\x18\a \x01(\v2\x16.client.v0.RestrictionR\tdiscovery\"\x9e\x02\n" +
	"\vSupportInfo\x122\n" +
	"\aruntime\x18\x01 \x01(\v2\x18.client.v0.BuildIdentityR\aruntime\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12+\n" +
	"\x11documentation_url\x18\x03 \x01(\tR\x10documentationUrl\x12\x1f\n" +
	"\vsupport_url\x18\x04 \x01(\tR\n" +
	"supportUrl\x12\x1f\n" +
	"\vprivacy_url\x18\x05 \x01(\tR\n" +
	"privacyUrl\x12\x1f\n" +
	"\vlicense_url\x18\x06 \x01(\tR\n" +
	"licenseUrl\x12(\n" +
	"\x10offline_help_key\x18\a \x01(\tR\x0eofflineHelpKey*\xc6\x01\n" +
	"\rSettingSource\x12\x1e\n" +
	"\x1aSETTING_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SETTING_SOURCE_DEFAULT\x10\x01\x12\x17\n" +
	"\x13SETTING_SOURCE_USER\x10\x02\x12 \n" +
	"\x1cSETTING_SOURCE_DEVICE_POLICY\x10\x03\x12!\n" +
	"\x1dSETTING_SOURCE_ACCOUNT_POLICY\x10\x04\x12\x1b\n" +
	"\x17SETTING_SOURCE_PLATFORM\x10\x05*\xc7\x01\n" +
	"\x11LifecycleBehavior\x12\"\n" +
	"\x1eLIFECYCLE_BEHAVIOR_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eLIFECYCLE_BEHAVIOR_KEEP_INTENT\x10\x01\x12\x1e\n" +
	"\x1aLIFECYCLE_BEHAVIOR_CONNECT\x10\x02\x12!\n" +
	"\x1dLIFECYCLE_BEHAVIOR_DISCONNECT\x10\x03\x12'\n" +
	"#LIFECYCLE_BEHAVIOR_PLATFORM_MANAGED\x10\x04*\xa7\x02\n" +
	"\rPreferenceKey\x12\x1e\n" +
	"\x1aPREFERENCE_KEY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPREFERENCE_KEY_ALLOW_INBOUND\x10\x01\x12\x1d\n" +
	"\x19PREFERENCE_KEY_ACCEPT_DNS\x10\x02\x12 \n" +
	"\x1cPREFERENCE_KEY_ACCEPT_ROUTES\x10\x03\x12 \n" +
	"\x1cPREFERENCE_KEY_RUNTIME_START\x10\x04\x12\x1a\n" +
	"\x16PREFERENCE_KEY_UI_QUIT\x10\x05\x12\x1e\n" +
	"\x1aPREFERENCE_KEY_USER_LOGOFF\x10\x06\x12\x1a\n" +
	"\x16PREFERENCE_KEY_SUSPEND\x10\a\x12\x19\n" +
	"\x15PREFERENCE_KEY_RESUME\x10\b*S\n" +
	"\tLanAccess\x12\x1a\n" +
	"\x16LAN_ACCESS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10LAN_ACCESS_BLOCK\x10\x01\x12\x14\n" +
	"\x10LAN_ACCESS_ALLOW\x10\x02*\xae\x01\n" +
	"\x0eExitFamilyMode\x12 \n" +
	"\x1cEXIT_FAMILY_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EXIT_FAMILY_MODE_NONE\x10\x01\x12\x1e\n" +
	"\x1aEXIT_FAMILY_MODE_IPV4_ONLY\x10\x02\x12\x1e\n" +
	"\x1aEXIT_FAMILY_MODE_IPV6_ONLY\x10\x03\x12\x1f\n" +
	"\x1bEXIT_FAMILY_MODE_DUAL_STACK\x10\x04*s\n" +
	"\n" +
	"ApplyState\x12\x1b\n" +
	"\x17APPLY_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13APPLY_STATE_PENDING\x10\x01\x12\x17\n" +
	"\x13APPLY_STATE_APPLIED\x10\x02\x12\x16\n" +
	"\x12APPLY_STATE_FAILED\x10\x03*\x99\x01\n" +
	"\fResourceKind\x12\x1d\n" +
	"\x19RESOURCE_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RESOURCE_KIND_HOST\x10\x01\x12\x18\n" +
	"\x14RESOURCE_KIND_SUBNET\x10\x02\x12\x19\n" +
	"\x15RESOURCE_KIND_SERVICE\x10\x03\x12\x1d\n" +
	"\x19RESOURCE_KIND_APPLICATION\x10\x04*\xaa\x01\n" +
	"\x14UpdateClassification\x12%\n" +
	"!UPDATE_CLASSIFICATION_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eUPDATE_CLASSIFICATION_ORDINARY\x10\x01\x12\"\n" +
	"\x1eUPDATE_CLASSIFICATION_SECURITY\x10\x02\x12#\n" +
	"\x1fUPDATE_CLASSIFICATION_MANDATORY\x10\x03*\xd7\x01\n" +
	"\x13DistributionChannel\x12$\n" +
	" DISTRIBUTION_CHANNEL_UNSPECIFIED\x10\x00\x12'\n" +
	"#DISTRIBUTION_CHANNEL_VENDOR_PACKAGE\x10\x01\x12(\n" +
	"$DISTRIBUTION_CHANNEL_PACKAGE_MANAGER\x10\x02\x12\"\n" +
	"\x1eDISTRIBUTION_CHANNEL_APP_STORE\x10\x03\x12#\n" +
	"\x1fDISTRIBUTION_CHANNEL_ENTERPRISE\x10\x04*\xa4\x01\n" +
	"\x12CompatibilityState\x12#\n" +
	"\x1fCOMPATIBILITY_STATE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCOMPATIBILITY_STATE_COMPATIBLE\x10\x01\x12$\n" +
	" COMPATIBILITY_STATE_INCOMPATIBLE\x10\x02\x12\x1f\n" +
	"\x1bCOMPATIBILITY_STATE_UNKNOWN\x10\x03*\xf5\x01\n" +
	"\vUpdateState\x12\x1c\n" +
	"\x18UPDATE_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14UPDATE_STATE_UNKNOWN\x10\x01\x12\x1b\n" +
	"\x17UPDATE_STATE_UP_TO_DATE\x10\x02\x12\x1a\n" +
	"\x16UPDATE_STATE_AVAILABLE\x10\x03\x12*\n" +
	"&UPDATE_STATE_EXTERNAL_MANAGER_REQUIRED\x10\x04\x12#\n" +
	"\x1fUPDATE_STATE_SOURCE_UNAVAILABLE\x10\x05\x12$\n" +
	" UPDATE_STATE_VERIFICATION_FAILED\x10\x06*N\n" +
	"\x0eLifecycleEvent\x12\x1f\n" +
	"\x1bLIFECYCLE_EVENT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17LIFECYCLE_EVENT_UI_QUIT\x10\x01B6Z4github.com/endless-net/client/clientipc/v0;clientipcb\x06proto3"

var (
	file_client_v0_features_proto_rawDescOnce sync.Once
	file_client_v0_features_proto_rawDescData []byte
)

func file_client_v0_features_proto_rawDescGZIP() []byte {
	file_client_v0_features_proto_rawDescOnce.Do(func() {
		file_client_v0_features_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v0_features_proto_rawDesc), len(file_client_v0_features_proto_rawDesc)))
	})
	return file_client_v0_features_proto_rawDescData
}

var file_client_v0_features_proto_enumTypes = make([]protoimpl.EnumInfo, 12)
var file_client_v0_features_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_client_v0_features_proto_goTypes = []any{
	(SettingSource)(0),            // 0: client.v0.SettingSource
	(LifecycleBehavior)(0),        // 1: client.v0.LifecycleBehavior
	(PreferenceKey)(0),            // 2: client.v0.PreferenceKey
	(LanAccess)(0),                // 3: client.v0.LanAccess
	(ExitFamilyMode)(0),           // 4: client.v0.ExitFamilyMode
	(ApplyState)(0),               // 5: client.v0.ApplyState
	(ResourceKind)(0),             // 6: client.v0.ResourceKind
	(UpdateClassification)(0),     // 7: client.v0.UpdateClassification
	(DistributionChannel)(0),      // 8: client.v0.DistributionChannel
	(CompatibilityState)(0),       // 9: client.v0.CompatibilityState
	(UpdateState)(0),              // 10: client.v0.UpdateState
	(LifecycleEvent)(0),           // 11: client.v0.LifecycleEvent
	(*SettingControl)(nil),        // 12: client.v0.SettingControl
	(*BooleanSetting)(nil),        // 13: client.v0.BooleanSetting
	(*LifecycleSetting)(nil),      // 14: client.v0.LifecycleSetting
	(*RuntimeLifecycle)(nil),      // 15: client.v0.RuntimeLifecycle
	(*Preferences)(nil),           // 16: client.v0.Preferences
	(*PreferencesPatch)(nil),      // 17: client.v0.PreferencesPatch
	(*ManagedSetting)(nil),        // 18: client.v0.ManagedSetting
	(*ExitNode)(nil),              // 19: client.v0.ExitNode
	(*ExitFamilyStatus)(nil),      // 20: client.v0.ExitFamilyStatus
	(*ExitNodeStatus)(nil),        // 21: client.v0.ExitNodeStatus
	(*HostTarget)(nil),            // 22: client.v0.HostTarget
	(*SubnetTarget)(nil),          // 23: client.v0.SubnetTarget
	(*ServiceTarget)(nil),         // 24: client.v0.ServiceTarget
	(*ApplicationTarget)(nil),     // 25: client.v0.ApplicationTarget
	(*Resource)(nil),              // 26: client.v0.Resource
	(*Compatibility)(nil),         // 27: client.v0.Compatibility
	(*VerifiedUpdate)(nil),        // 28: client.v0.VerifiedUpdate
	(*UpdateInfo)(nil),            // 29: client.v0.UpdateInfo
	(*SupportInfo)(nil),           // 30: client.v0.SupportInfo
	(*Restriction)(nil),           // 31: client.v0.Restriction
	(*SnapshotMetadata)(nil),      // 32: client.v0.SnapshotMetadata
	(*Failure)(nil),               // 33: client.v0.Failure
	(*timestamppb.Timestamp)(nil), // 34: google.protobuf.Timestamp
	(*BuildIdentity)(nil),         // 35: client.v0.BuildIdentity
}
var file_client_v0_features_proto_depIdxs = []int32{
	0,  // 0: client.v0.SettingControl.source:type_name -> client.v0.SettingSource
	31, // 1: client.v0.SettingControl.mutation:type_name -> client.v0.Restriction
	12, // 2: client.v0.BooleanSetting.control:type_name -> client.v0.SettingControl
	1,  // 3: client.v0.LifecycleSetting.effective:type_name -> client.v0.LifecycleBehavior
	1,  // 4: client.v0.LifecycleSetting.requested:type_name -> client.v0.LifecycleBehavior
	12, // 5: client.v0.LifecycleSetting.control:type_name -> client.v0.SettingControl
	1,  // 6: client.v0.LifecycleSetting.allowed_values:type_name -> client.v0.LifecycleBehavior
	14, // 7: client.v0.RuntimeLifecycle.runtime_start:type_name -> client.v0.LifecycleSetting
	14, // 8: client.v0.RuntimeLifecycle.ui_quit:type_name -> client.v0.LifecycleSetting
	14, // 9: client.v0.RuntimeLifecycle.user_logoff:type_name -> client.v0.LifecycleSetting
	14, // 10: client.v0.RuntimeLifecycle.suspend:type_name -> client.v0.LifecycleSetting
	14, // 11: client.v0.RuntimeLifecycle.resume:type_name -> client.v0.LifecycleSetting
	32, // 12: client.v0.Preferences.metadata:type_name -> client.v0.SnapshotMetadata
	13, // 13: client.v0.Preferences.allow_inbound:type_name -> client.v0.BooleanSetting
	13, // 14: client.v0.Preferences.accept_dns:type_name -> client.v0.BooleanSetting
	13, // 15: client.v0.Preferences.accept_routes:type_name -> client.v0.BooleanSetting
	15, // 16: client.v0.Preferences.lifecycle:type_name -> client.v0.RuntimeLifecycle
	1,  // 17: client.v0.PreferencesPatch.runtime_start:type_name -> client.v0.LifecycleBehavior
	1,  // 18: client.v0.PreferencesPatch.ui_quit:type_name -> client.v0.LifecycleBehavior
	1,  // 19: client.v0.PreferencesPatch.user_logoff:type_name -> client.v0.LifecycleBehavior
	1,  // 20: client.v0.PreferencesPatch.suspend:type_name -> client.v0.LifecycleBehavior
	1,  // 21: client.v0.PreferencesPatch.resume:type_name -> client.v0.LifecycleBehavior
	2,  // 22: client.v0.ManagedSetting.key:type_name -> client.v0.PreferenceKey
	12, // 23: client.v0.ManagedSetting.control:type_name -> client.v0.SettingControl
	1,  // 24: client.v0.ManagedSetting.lifecycle_value:type_name -> client.v0.LifecycleBehavior
	31, // 25: client.v0.ExitNode.selection:type_name -> client.v0.Restriction
	3,  // 26: client.v0.ExitNode.allowed_lan_access:type_name -> client.v0.LanAccess
	4,  // 27: client.v0.ExitNode.allowed_family_modes:type_name -> client.v0.ExitFamilyMode
	5,  // 28: client.v0.ExitFamilyStatus.apply_state:type_name -> client.v0.ApplyState
	33, // 29: client.v0.ExitFamilyStatus.failure:type_name -> client.v0.Failure
	32, // 30: client.v0.ExitNodeStatus.metadata:type_name -> client.v0.SnapshotMetadata
	3,  // 31: client.v0.ExitNodeStatus.requested_lan_access:type_name -> client.v0.LanAccess
	3,  // 32: client.v0.ExitNodeStatus.effective_lan_access:type_name -> client.v0.LanAccess
	5,  // 33: client.v0.ExitNodeStatus.apply_state:type_name -> client.v0.ApplyState
	12, // 34: client.v0.ExitNodeStatus.control:type_name -> client.v0.SettingControl
	33, // 35: client.v0.ExitNodeStatus.failure:type_name -> client.v0.Failure
	4,  // 36: client.v0.ExitNodeStatus.requested_family_mode:type_name -> client.v0.ExitFamilyMode
	20, // 37: client.v0.ExitNodeStatus.ipv4:type_name -> client.v0.ExitFamilyStatus
	20, // 38: client.v0.ExitNodeStatus.ipv6:type_name -> client.v0.ExitFamilyStatus
	6,  // 39: client.v0.Resource.kind:type_name -> client.v0.ResourceKind
	31, // 40: client.v0.Resource.availability:type_name -> client.v0.Restriction
	13, // 41: client.v0.Resource.enabled:type_name -> client.v0.BooleanSetting
	22, // 42: client.v0.Resource.host:type_name -> client.v0.HostTarget
	23, // 43: client.v0.Resource.subnet:type_name -> client.v0.SubnetTarget
	24, // 44: client.v0.Resource.service:type_name -> client.v0.ServiceTarget
	25, // 45: client.v0.Resource.application:type_name -> client.v0.ApplicationTarget
	9,  // 46: client.v0.Compatibility.state:type_name -> client.v0.CompatibilityState
	34, // 47: client.v0.VerifiedUpdate.verified_at:type_name -> google.protobuf.Timestamp
	34, // 48: client.v0.VerifiedUpdate.expires_at:type_name -> google.protobuf.Timestamp
	35, // 49: client.v0.VerifiedUpdate.runtime:type_name -> client.v0.BuildIdentity
	27, // 50: client.v0.VerifiedUpdate.compatibility:type_name -> client.v0.Compatibility
	7,  // 51: client.v0.VerifiedUpdate.classification:type_name -> client.v0.UpdateClassification
	8,  // 52: client.v0.VerifiedUpdate.channel:type_name -> client.v0.DistributionChannel
	34, // 53: client.v0.VerifiedUpdate.mandatory_after:type_name -> google.protobuf.Timestamp
	32, // 54: client.v0.UpdateInfo.metadata:type_name -> client.v0.SnapshotMetadata
	35, // 55: client.v0.UpdateInfo.installed_runtime:type_name -> client.v0.BuildIdentity
	35, // 56: client.v0.UpdateInfo.reported_ui:type_name -> client.v0.BuildIdentity
	27, // 57: client.v0.UpdateInfo.installed_pair:type_name -> client.v0.Compatibility
	10, // 58: client.v0.UpdateInfo.state:type_name -> client.v0.UpdateState
	28, // 59: client.v0.UpdateInfo.available:type_name -> client.v0.VerifiedUpdate
	31, // 60: client.v0.UpdateInfo.discovery:type_name -> client.v0.Restriction
	35, // 61: client.v0.SupportInfo.runtime:type_name -> client.v0.BuildIdentity
	62, // [62:62] is the sub-list for method output_type
	62, // [62:62] is the sub-list for method input_type
	62, // [62:62] is the sub-list for extension type_name
	62, // [62:62] is the sub-list for extension extendee
	0,  // [0:62] is the sub-list for field type_name
}

func init() { file_client_v0_features_proto_init() }
func file_client_v0_features_proto_init() {
	if File_client_v0_features_proto != nil {
		return
	}
	file_client_v0_common_proto_init()
	file_client_v0_features_proto_msgTypes[1].OneofWrappers = []any{}
	file_client_v0_features_proto_msgTypes[2].OneofWrappers = []any{}
	file_client_v0_features_proto_msgTypes[5].OneofWrappers = []any{}
	file_client_v0_features_proto_msgTypes[6].OneofWrappers = []any{
		(*ManagedSetting_BooleanValue)(nil),
		(*ManagedSetting_LifecycleValue)(nil),
	}
	file_client_v0_features_proto_msgTypes[8].OneofWrappers = []any{}
	file_client_v0_features_proto_msgTypes[9].OneofWrappers = []any{}
	file_client_v0_features_proto_msgTypes[14].OneofWrappers = []any{
		(*Resource_Host)(nil),
		(*Resource_Subnet)(nil),
		(*Resource_Service)(nil),
		(*Resource_Application)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v0_features_proto_rawDesc), len(file_client_v0_features_proto_rawDesc)),
			NumEnums:      12,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_v0_features_proto_goTypes,
		DependencyIndexes: file_client_v0_features_proto_depIdxs,
		EnumInfos:         file_client_v0_features_proto_enumTypes,
		MessageInfos:      file_client_v0_features_proto_msgTypes,
	}.Build()
	File_client_v0_features_proto = out.File
	file_client_v0_features_proto_goTypes = nil
	file_client_v0_features_proto_depIdxs = nil
}
