// Command dartmetadata generates pairing constants from the embedded descriptor.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/endless-net/client/clientipc/rpc"
)

func main() {
	output := flag.String("out", "../packages/client_api/lib/src/contract.dart", "generated Dart metadata path")
	flag.Parse()
	content := fmt.Sprintf(`// Generated by clientipc/internal/dartmetadata. Do not edit.
/// Exact producer identity for bootstrap and every subsequent v0 RPC.
abstract final class ClientContract {
  static const protocol = '%s';
  static const version = %d;
  static const sha256 = '%s';
  static const metadata = <String, String>{
    '%s': protocol,
    '%s': '%d',
    '%s': sha256,
  };
}
`, rpc.Protocol, rpc.Version, rpc.Digest(), strings.ToLower(rpc.ProtocolHeader), strings.ToLower(rpc.VersionHeader), rpc.Version, strings.ToLower(rpc.DigestHeader))
	if err := os.WriteFile(*output, []byte(content), 0644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
