// Accepted producer-owned local RPC surface. Authorization annotations are normative.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: client/v0/service.proto

package clientipcconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v0 "github.com/endless-net/client/clientipc/v0"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ClientServiceName is the fully-qualified name of the ClientService service.
	ClientServiceName = "client.v0.ClientService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ClientServiceGetRuntimeInfoProcedure is the fully-qualified name of the ClientService's
	// GetRuntimeInfo RPC.
	ClientServiceGetRuntimeInfoProcedure = "/client.v0.ClientService/GetRuntimeInfo"
	// ClientServiceGetStatusProcedure is the fully-qualified name of the ClientService's GetStatus RPC.
	ClientServiceGetStatusProcedure = "/client.v0.ClientService/GetStatus"
	// ClientServiceWatchEventsProcedure is the fully-qualified name of the ClientService's WatchEvents
	// RPC.
	ClientServiceWatchEventsProcedure = "/client.v0.ClientService/WatchEvents"
	// ClientServiceGetOperationProcedure is the fully-qualified name of the ClientService's
	// GetOperation RPC.
	ClientServiceGetOperationProcedure = "/client.v0.ClientService/GetOperation"
	// ClientServiceEnrollProcedure is the fully-qualified name of the ClientService's Enroll RPC.
	ClientServiceEnrollProcedure = "/client.v0.ClientService/Enroll"
	// ClientServiceConnectProcedure is the fully-qualified name of the ClientService's Connect RPC.
	ClientServiceConnectProcedure = "/client.v0.ClientService/Connect"
	// ClientServiceDisconnectProcedure is the fully-qualified name of the ClientService's Disconnect
	// RPC.
	ClientServiceDisconnectProcedure = "/client.v0.ClientService/Disconnect"
	// ClientServiceGetServerIdentityProcedure is the fully-qualified name of the ClientService's
	// GetServerIdentity RPC.
	ClientServiceGetServerIdentityProcedure = "/client.v0.ClientService/GetServerIdentity"
	// ClientServiceTrustServerIdentityProcedure is the fully-qualified name of the ClientService's
	// TrustServerIdentity RPC.
	ClientServiceTrustServerIdentityProcedure = "/client.v0.ClientService/TrustServerIdentity"
	// ClientServiceLogoutProcedure is the fully-qualified name of the ClientService's Logout RPC.
	ClientServiceLogoutProcedure = "/client.v0.ClientService/Logout"
	// ClientServiceForgetLocalEnrollmentProcedure is the fully-qualified name of the ClientService's
	// ForgetLocalEnrollment RPC.
	ClientServiceForgetLocalEnrollmentProcedure = "/client.v0.ClientService/ForgetLocalEnrollment"
	// ClientServiceListNetworksProcedure is the fully-qualified name of the ClientService's
	// ListNetworks RPC.
	ClientServiceListNetworksProcedure = "/client.v0.ClientService/ListNetworks"
	// ClientServiceSelectNetworkProcedure is the fully-qualified name of the ClientService's
	// SelectNetwork RPC.
	ClientServiceSelectNetworkProcedure = "/client.v0.ClientService/SelectNetwork"
	// ClientServiceListPeersProcedure is the fully-qualified name of the ClientService's ListPeers RPC.
	ClientServiceListPeersProcedure = "/client.v0.ClientService/ListPeers"
	// ClientServiceGetDiagnosticsProcedure is the fully-qualified name of the ClientService's
	// GetDiagnostics RPC.
	ClientServiceGetDiagnosticsProcedure = "/client.v0.ClientService/GetDiagnostics"
	// ClientServiceCreateDiagnosticsBundleProcedure is the fully-qualified name of the ClientService's
	// CreateDiagnosticsBundle RPC.
	ClientServiceCreateDiagnosticsBundleProcedure = "/client.v0.ClientService/CreateDiagnosticsBundle"
	// ClientServiceReadDiagnosticsBundleProcedure is the fully-qualified name of the ClientService's
	// ReadDiagnosticsBundle RPC.
	ClientServiceReadDiagnosticsBundleProcedure = "/client.v0.ClientService/ReadDiagnosticsBundle"
	// ClientServiceListRecentLogsProcedure is the fully-qualified name of the ClientService's
	// ListRecentLogs RPC.
	ClientServiceListRecentLogsProcedure = "/client.v0.ClientService/ListRecentLogs"
	// ClientServiceListProfilesProcedure is the fully-qualified name of the ClientService's
	// ListProfiles RPC.
	ClientServiceListProfilesProcedure = "/client.v0.ClientService/ListProfiles"
	// ClientServiceCreateProfileProcedure is the fully-qualified name of the ClientService's
	// CreateProfile RPC.
	ClientServiceCreateProfileProcedure = "/client.v0.ClientService/CreateProfile"
	// ClientServiceSelectProfileProcedure is the fully-qualified name of the ClientService's
	// SelectProfile RPC.
	ClientServiceSelectProfileProcedure = "/client.v0.ClientService/SelectProfile"
	// ClientServiceRenameProfileProcedure is the fully-qualified name of the ClientService's
	// RenameProfile RPC.
	ClientServiceRenameProfileProcedure = "/client.v0.ClientService/RenameProfile"
	// ClientServiceRemoveProfileProcedure is the fully-qualified name of the ClientService's
	// RemoveProfile RPC.
	ClientServiceRemoveProfileProcedure = "/client.v0.ClientService/RemoveProfile"
	// ClientServiceGetSessionProcedure is the fully-qualified name of the ClientService's GetSession
	// RPC.
	ClientServiceGetSessionProcedure = "/client.v0.ClientService/GetSession"
	// ClientServiceRenewSessionProcedure is the fully-qualified name of the ClientService's
	// RenewSession RPC.
	ClientServiceRenewSessionProcedure = "/client.v0.ClientService/RenewSession"
	// ClientServiceListExitNodesProcedure is the fully-qualified name of the ClientService's
	// ListExitNodes RPC.
	ClientServiceListExitNodesProcedure = "/client.v0.ClientService/ListExitNodes"
	// ClientServiceGetExitNodeProcedure is the fully-qualified name of the ClientService's GetExitNode
	// RPC.
	ClientServiceGetExitNodeProcedure = "/client.v0.ClientService/GetExitNode"
	// ClientServiceSelectExitNodeProcedure is the fully-qualified name of the ClientService's
	// SelectExitNode RPC.
	ClientServiceSelectExitNodeProcedure = "/client.v0.ClientService/SelectExitNode"
	// ClientServiceClearExitNodeProcedure is the fully-qualified name of the ClientService's
	// ClearExitNode RPC.
	ClientServiceClearExitNodeProcedure = "/client.v0.ClientService/ClearExitNode"
	// ClientServiceGetPreferencesProcedure is the fully-qualified name of the ClientService's
	// GetPreferences RPC.
	ClientServiceGetPreferencesProcedure = "/client.v0.ClientService/GetPreferences"
	// ClientServiceSetPreferencesProcedure is the fully-qualified name of the ClientService's
	// SetPreferences RPC.
	ClientServiceSetPreferencesProcedure = "/client.v0.ClientService/SetPreferences"
	// ClientServiceResetPreferencesProcedure is the fully-qualified name of the ClientService's
	// ResetPreferences RPC.
	ClientServiceResetPreferencesProcedure = "/client.v0.ClientService/ResetPreferences"
	// ClientServiceListManagedSettingsProcedure is the fully-qualified name of the ClientService's
	// ListManagedSettings RPC.
	ClientServiceListManagedSettingsProcedure = "/client.v0.ClientService/ListManagedSettings"
	// ClientServiceListResourcesProcedure is the fully-qualified name of the ClientService's
	// ListResources RPC.
	ClientServiceListResourcesProcedure = "/client.v0.ClientService/ListResources"
	// ClientServiceSetResourceEnabledProcedure is the fully-qualified name of the ClientService's
	// SetResourceEnabled RPC.
	ClientServiceSetResourceEnabledProcedure = "/client.v0.ClientService/SetResourceEnabled"
	// ClientServiceNotifyLifecycleProcedure is the fully-qualified name of the ClientService's
	// NotifyLifecycle RPC.
	ClientServiceNotifyLifecycleProcedure = "/client.v0.ClientService/NotifyLifecycle"
	// ClientServiceGetUpdateInfoProcedure is the fully-qualified name of the ClientService's
	// GetUpdateInfo RPC.
	ClientServiceGetUpdateInfoProcedure = "/client.v0.ClientService/GetUpdateInfo"
	// ClientServiceGetSupportInfoProcedure is the fully-qualified name of the ClientService's
	// GetSupportInfo RPC.
	ClientServiceGetSupportInfoProcedure = "/client.v0.ClientService/GetSupportInfo"
)

// ClientServiceClient is a client for the client.v0.ClientService service.
type ClientServiceClient interface {
	// UF-04, UF-20, UF-22, UF-23: installed identity and caller-filtered capabilities.
	GetRuntimeInfo(context.Context, *connect.Request[v0.GetRuntimeInfoRequest]) (*connect.Response[v0.GetRuntimeInfoResponse], error)
	// UF-04, UF-09: authoritative active-context snapshot.
	GetStatus(context.Context, *connect.Request[v0.GetStatusRequest]) (*connect.Response[v0.GetStatusResponse], error)
	// UF-04, UF-09, UF-15: snapshot first, then typed changes; no replay cursor.
	WatchEvents(context.Context, *connect.Request[v0.WatchEventsRequest]) (*connect.ServerStreamForClient[v0.WatchEventsResponse], error)
	// Read a caller-owned operation after timeout or reconnection.
	GetOperation(context.Context, *connect.Request[v0.GetOperationRequest]) (*connect.Response[v0.GetOperationResponse], error)
	// UF-03: initial unowned installation uses the ownership-claim exception.
	Enroll(context.Context, *connect.Request[v0.EnrollRequest]) (*connect.Response[v0.EnrollResponse], error)
	// UF-05: persist connected intent, then reconcile runtime.
	Connect(context.Context, *connect.Request[v0.ConnectRequest]) (*connect.Response[v0.ConnectResponse], error)
	// UF-05: persist disconnected intent; retain registration.
	Disconnect(context.Context, *connect.Request[v0.DisconnectRequest]) (*connect.Response[v0.DisconnectResponse], error)
	// UF-10: review announced and trusted identity for a profile.
	GetServerIdentity(context.Context, *connect.Request[v0.GetServerIdentityRequest]) (*connect.Response[v0.GetServerIdentityResponse], error)
	// UF-10: fixed-purpose privileged operation, matching the current announcement.
	TrustServerIdentity(context.Context, *connect.Request[v0.TrustServerIdentityRequest]) (*connect.Response[v0.TrustServerIdentityResponse], error)
	// UF-12: remote confirmation is required before deleting local registration.
	Logout(context.Context, *connect.Request[v0.LogoutRequest]) (*connect.Response[v0.LogoutResponse], error)
	// UF-12: explicit local-only cleanup; never claims remote revocation.
	ForgetLocalEnrollment(context.Context, *connect.Request[v0.ForgetLocalEnrollmentRequest]) (*connect.Response[v0.ForgetLocalEnrollmentResponse], error)
	// UF-07: only already granted networks for this profile.
	ListNetworks(context.Context, *connect.Request[v0.ListNetworksRequest]) (*connect.Response[v0.ListNetworksResponse], error)
	// UF-07: select an enrolled network by stable ID.
	SelectNetwork(context.Context, *connect.Request[v0.SelectNetworkRequest]) (*connect.Response[v0.SelectNetworkResponse], error)
	// UF-06, UF-19: filtered peer search and path inspection.
	ListPeers(context.Context, *connect.Request[v0.ListPeersRequest]) (*connect.Response[v0.ListPeersResponse], error)
	// UF-11: bounded producer-redacted snapshot.
	GetDiagnostics(context.Context, *connect.Request[v0.GetDiagnosticsRequest]) (*connect.Response[v0.GetDiagnosticsResponse], error)
	// UF-11: local-only redacted archive, no upload or packet capture.
	CreateDiagnosticsBundle(context.Context, *connect.Request[v0.CreateDiagnosticsBundleRequest]) (*connect.Response[v0.CreateDiagnosticsBundleResponse], error)
	// UF-11: caller-bound handle; bounded chunks, no filesystem path input.
	ReadDiagnosticsBundle(context.Context, *connect.Request[v0.ReadDiagnosticsBundleRequest]) (*connect.Response[v0.ReadDiagnosticsBundleResponse], error)
	// UF-11: bounded redacted log entries.
	ListRecentLogs(context.Context, *connect.Request[v0.ListRecentLogsRequest]) (*connect.Response[v0.ListRecentLogsResponse], error)
	// UF-16: local owner profiles, one active at most.
	ListProfiles(context.Context, *connect.Request[v0.ListProfilesRequest]) (*connect.Response[v0.ListProfilesResponse], error)
	// UF-16: create empty context; enrollment is a separate explicit action.
	CreateProfile(context.Context, *connect.Request[v0.CreateProfileRequest]) (*connect.Response[v0.CreateProfileResponse], error)
	// UF-16: atomic context switch, report actual connection interruption.
	SelectProfile(context.Context, *connect.Request[v0.SelectProfileRequest]) (*connect.Response[v0.SelectProfileResponse], error)
	// UF-16: change display name only; identity and origin are immutable.
	RenameProfile(context.Context, *connect.Request[v0.RenameProfileRequest]) (*connect.Response[v0.RenameProfileResponse], error)
	// UF-16: only inactive profiles with no remaining registration/session.
	RemoveProfile(context.Context, *connect.Request[v0.RemoveProfileRequest]) (*connect.Response[v0.RemoveProfileResponse], error)
	// UF-17: expiry, warning deadline and renewal availability.
	GetSession(context.Context, *connect.Request[v0.GetSessionRequest]) (*connect.Response[v0.GetSessionResponse], error)
	// UF-17: no caller-supplied callback URL or browser credential.
	RenewSession(context.Context, *connect.Request[v0.RenewSessionRequest]) (*connect.Response[v0.RenewSessionResponse], error)
	// UF-08: list authorized consumer-side egress choices.
	ListExitNodes(context.Context, *connect.Request[v0.ListExitNodesRequest]) (*connect.Response[v0.ListExitNodesResponse], error)
	// UF-08: requested/effective selection, LAN policy and apply outcome.
	GetExitNode(context.Context, *connect.Request[v0.GetExitNodeRequest]) (*connect.Response[v0.GetExitNodeResponse], error)
	// UF-08: only an authorized catalog ID; never arbitrary routes.
	SelectExitNode(context.Context, *connect.Request[v0.SelectExitNodeRequest]) (*connect.Response[v0.SelectExitNodeResponse], error)
	// UF-08: explicit removal of consumer-side egress selection.
	ClearExitNode(context.Context, *connect.Request[v0.ClearExitNodeRequest]) (*connect.Response[v0.ClearExitNodeResponse], error)
	// UF-18, UF-21: effective values, user overrides and locks.
	GetPreferences(context.Context, *connect.Request[v0.GetPreferencesRequest]) (*connect.Response[v0.GetPreferencesResponse], error)
	// UF-18, UF-21: nonempty typed patch, all-or-nothing validation.
	SetPreferences(context.Context, *connect.Request[v0.SetPreferencesRequest]) (*connect.Response[v0.SetPreferencesResponse], error)
	// UF-18, UF-21: remove named user overrides; managed values remain.
	ResetPreferences(context.Context, *connect.Request[v0.ResetPreferencesRequest]) (*connect.Response[v0.ResetPreferencesResponse], error)
	// UF-20: read-only effective runtime policy and next-action owner.
	ListManagedSettings(context.Context, *connect.Request[v0.ListManagedSettingsRequest]) (*connect.Response[v0.ListManagedSettingsResponse], error)
	// UF-19: granted catalog, availability, overlaps and local selection.
	ListResources(context.Context, *connect.Request[v0.ListResourcesRequest]) (*connect.Response[v0.ListResourcesResponse], error)
	// UF-19: local subset selection cannot expand backend authorization.
	SetResourceEnabled(context.Context, *connect.Request[v0.SetResourceEnabledRequest]) (*connect.Response[v0.SetResourceEnabledResponse], error)
	// UF-21: explicit graceful UI quit only; OS lifecycle comes from runtime adapters.
	NotifyLifecycle(context.Context, *connect.Request[v0.NotifyLifecycleRequest]) (*connect.Response[v0.NotifyLifecycleResponse], error)
	// UF-22: verified distribution projection and installed-pair compatibility.
	GetUpdateInfo(context.Context, *connect.Request[v0.GetUpdateInfoRequest]) (*connect.Response[v0.GetUpdateInfoResponse], error)
	// UF-23: validated product links and offline-help key.
	GetSupportInfo(context.Context, *connect.Request[v0.GetSupportInfoRequest]) (*connect.Response[v0.GetSupportInfoResponse], error)
}

// NewClientServiceClient constructs a client for the client.v0.ClientService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewClientServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ClientServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	clientServiceMethods := v0.File_client_v0_service_proto.Services().ByName("ClientService").Methods()
	return &clientServiceClient{
		getRuntimeInfo: connect.NewClient[v0.GetRuntimeInfoRequest, v0.GetRuntimeInfoResponse](
			httpClient,
			baseURL+ClientServiceGetRuntimeInfoProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetRuntimeInfo")),
			connect.WithClientOptions(opts...),
		),
		getStatus: connect.NewClient[v0.GetStatusRequest, v0.GetStatusResponse](
			httpClient,
			baseURL+ClientServiceGetStatusProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		watchEvents: connect.NewClient[v0.WatchEventsRequest, v0.WatchEventsResponse](
			httpClient,
			baseURL+ClientServiceWatchEventsProcedure,
			connect.WithSchema(clientServiceMethods.ByName("WatchEvents")),
			connect.WithClientOptions(opts...),
		),
		getOperation: connect.NewClient[v0.GetOperationRequest, v0.GetOperationResponse](
			httpClient,
			baseURL+ClientServiceGetOperationProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetOperation")),
			connect.WithClientOptions(opts...),
		),
		enroll: connect.NewClient[v0.EnrollRequest, v0.EnrollResponse](
			httpClient,
			baseURL+ClientServiceEnrollProcedure,
			connect.WithSchema(clientServiceMethods.ByName("Enroll")),
			connect.WithClientOptions(opts...),
		),
		connect: connect.NewClient[v0.ConnectRequest, v0.ConnectResponse](
			httpClient,
			baseURL+ClientServiceConnectProcedure,
			connect.WithSchema(clientServiceMethods.ByName("Connect")),
			connect.WithClientOptions(opts...),
		),
		disconnect: connect.NewClient[v0.DisconnectRequest, v0.DisconnectResponse](
			httpClient,
			baseURL+ClientServiceDisconnectProcedure,
			connect.WithSchema(clientServiceMethods.ByName("Disconnect")),
			connect.WithClientOptions(opts...),
		),
		getServerIdentity: connect.NewClient[v0.GetServerIdentityRequest, v0.GetServerIdentityResponse](
			httpClient,
			baseURL+ClientServiceGetServerIdentityProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetServerIdentity")),
			connect.WithClientOptions(opts...),
		),
		trustServerIdentity: connect.NewClient[v0.TrustServerIdentityRequest, v0.TrustServerIdentityResponse](
			httpClient,
			baseURL+ClientServiceTrustServerIdentityProcedure,
			connect.WithSchema(clientServiceMethods.ByName("TrustServerIdentity")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v0.LogoutRequest, v0.LogoutResponse](
			httpClient,
			baseURL+ClientServiceLogoutProcedure,
			connect.WithSchema(clientServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		forgetLocalEnrollment: connect.NewClient[v0.ForgetLocalEnrollmentRequest, v0.ForgetLocalEnrollmentResponse](
			httpClient,
			baseURL+ClientServiceForgetLocalEnrollmentProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ForgetLocalEnrollment")),
			connect.WithClientOptions(opts...),
		),
		listNetworks: connect.NewClient[v0.ListNetworksRequest, v0.ListNetworksResponse](
			httpClient,
			baseURL+ClientServiceListNetworksProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ListNetworks")),
			connect.WithClientOptions(opts...),
		),
		selectNetwork: connect.NewClient[v0.SelectNetworkRequest, v0.SelectNetworkResponse](
			httpClient,
			baseURL+ClientServiceSelectNetworkProcedure,
			connect.WithSchema(clientServiceMethods.ByName("SelectNetwork")),
			connect.WithClientOptions(opts...),
		),
		listPeers: connect.NewClient[v0.ListPeersRequest, v0.ListPeersResponse](
			httpClient,
			baseURL+ClientServiceListPeersProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ListPeers")),
			connect.WithClientOptions(opts...),
		),
		getDiagnostics: connect.NewClient[v0.GetDiagnosticsRequest, v0.GetDiagnosticsResponse](
			httpClient,
			baseURL+ClientServiceGetDiagnosticsProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetDiagnostics")),
			connect.WithClientOptions(opts...),
		),
		createDiagnosticsBundle: connect.NewClient[v0.CreateDiagnosticsBundleRequest, v0.CreateDiagnosticsBundleResponse](
			httpClient,
			baseURL+ClientServiceCreateDiagnosticsBundleProcedure,
			connect.WithSchema(clientServiceMethods.ByName("CreateDiagnosticsBundle")),
			connect.WithClientOptions(opts...),
		),
		readDiagnosticsBundle: connect.NewClient[v0.ReadDiagnosticsBundleRequest, v0.ReadDiagnosticsBundleResponse](
			httpClient,
			baseURL+ClientServiceReadDiagnosticsBundleProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ReadDiagnosticsBundle")),
			connect.WithClientOptions(opts...),
		),
		listRecentLogs: connect.NewClient[v0.ListRecentLogsRequest, v0.ListRecentLogsResponse](
			httpClient,
			baseURL+ClientServiceListRecentLogsProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ListRecentLogs")),
			connect.WithClientOptions(opts...),
		),
		listProfiles: connect.NewClient[v0.ListProfilesRequest, v0.ListProfilesResponse](
			httpClient,
			baseURL+ClientServiceListProfilesProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ListProfiles")),
			connect.WithClientOptions(opts...),
		),
		createProfile: connect.NewClient[v0.CreateProfileRequest, v0.CreateProfileResponse](
			httpClient,
			baseURL+ClientServiceCreateProfileProcedure,
			connect.WithSchema(clientServiceMethods.ByName("CreateProfile")),
			connect.WithClientOptions(opts...),
		),
		selectProfile: connect.NewClient[v0.SelectProfileRequest, v0.SelectProfileResponse](
			httpClient,
			baseURL+ClientServiceSelectProfileProcedure,
			connect.WithSchema(clientServiceMethods.ByName("SelectProfile")),
			connect.WithClientOptions(opts...),
		),
		renameProfile: connect.NewClient[v0.RenameProfileRequest, v0.RenameProfileResponse](
			httpClient,
			baseURL+ClientServiceRenameProfileProcedure,
			connect.WithSchema(clientServiceMethods.ByName("RenameProfile")),
			connect.WithClientOptions(opts...),
		),
		removeProfile: connect.NewClient[v0.RemoveProfileRequest, v0.RemoveProfileResponse](
			httpClient,
			baseURL+ClientServiceRemoveProfileProcedure,
			connect.WithSchema(clientServiceMethods.ByName("RemoveProfile")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[v0.GetSessionRequest, v0.GetSessionResponse](
			httpClient,
			baseURL+ClientServiceGetSessionProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		renewSession: connect.NewClient[v0.RenewSessionRequest, v0.RenewSessionResponse](
			httpClient,
			baseURL+ClientServiceRenewSessionProcedure,
			connect.WithSchema(clientServiceMethods.ByName("RenewSession")),
			connect.WithClientOptions(opts...),
		),
		listExitNodes: connect.NewClient[v0.ListExitNodesRequest, v0.ListExitNodesResponse](
			httpClient,
			baseURL+ClientServiceListExitNodesProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ListExitNodes")),
			connect.WithClientOptions(opts...),
		),
		getExitNode: connect.NewClient[v0.GetExitNodeRequest, v0.GetExitNodeResponse](
			httpClient,
			baseURL+ClientServiceGetExitNodeProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetExitNode")),
			connect.WithClientOptions(opts...),
		),
		selectExitNode: connect.NewClient[v0.SelectExitNodeRequest, v0.SelectExitNodeResponse](
			httpClient,
			baseURL+ClientServiceSelectExitNodeProcedure,
			connect.WithSchema(clientServiceMethods.ByName("SelectExitNode")),
			connect.WithClientOptions(opts...),
		),
		clearExitNode: connect.NewClient[v0.ClearExitNodeRequest, v0.ClearExitNodeResponse](
			httpClient,
			baseURL+ClientServiceClearExitNodeProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ClearExitNode")),
			connect.WithClientOptions(opts...),
		),
		getPreferences: connect.NewClient[v0.GetPreferencesRequest, v0.GetPreferencesResponse](
			httpClient,
			baseURL+ClientServiceGetPreferencesProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetPreferences")),
			connect.WithClientOptions(opts...),
		),
		setPreferences: connect.NewClient[v0.SetPreferencesRequest, v0.SetPreferencesResponse](
			httpClient,
			baseURL+ClientServiceSetPreferencesProcedure,
			connect.WithSchema(clientServiceMethods.ByName("SetPreferences")),
			connect.WithClientOptions(opts...),
		),
		resetPreferences: connect.NewClient[v0.ResetPreferencesRequest, v0.ResetPreferencesResponse](
			httpClient,
			baseURL+ClientServiceResetPreferencesProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ResetPreferences")),
			connect.WithClientOptions(opts...),
		),
		listManagedSettings: connect.NewClient[v0.ListManagedSettingsRequest, v0.ListManagedSettingsResponse](
			httpClient,
			baseURL+ClientServiceListManagedSettingsProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ListManagedSettings")),
			connect.WithClientOptions(opts...),
		),
		listResources: connect.NewClient[v0.ListResourcesRequest, v0.ListResourcesResponse](
			httpClient,
			baseURL+ClientServiceListResourcesProcedure,
			connect.WithSchema(clientServiceMethods.ByName("ListResources")),
			connect.WithClientOptions(opts...),
		),
		setResourceEnabled: connect.NewClient[v0.SetResourceEnabledRequest, v0.SetResourceEnabledResponse](
			httpClient,
			baseURL+ClientServiceSetResourceEnabledProcedure,
			connect.WithSchema(clientServiceMethods.ByName("SetResourceEnabled")),
			connect.WithClientOptions(opts...),
		),
		notifyLifecycle: connect.NewClient[v0.NotifyLifecycleRequest, v0.NotifyLifecycleResponse](
			httpClient,
			baseURL+ClientServiceNotifyLifecycleProcedure,
			connect.WithSchema(clientServiceMethods.ByName("NotifyLifecycle")),
			connect.WithClientOptions(opts...),
		),
		getUpdateInfo: connect.NewClient[v0.GetUpdateInfoRequest, v0.GetUpdateInfoResponse](
			httpClient,
			baseURL+ClientServiceGetUpdateInfoProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetUpdateInfo")),
			connect.WithClientOptions(opts...),
		),
		getSupportInfo: connect.NewClient[v0.GetSupportInfoRequest, v0.GetSupportInfoResponse](
			httpClient,
			baseURL+ClientServiceGetSupportInfoProcedure,
			connect.WithSchema(clientServiceMethods.ByName("GetSupportInfo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// clientServiceClient implements ClientServiceClient.
type clientServiceClient struct {
	getRuntimeInfo          *connect.Client[v0.GetRuntimeInfoRequest, v0.GetRuntimeInfoResponse]
	getStatus               *connect.Client[v0.GetStatusRequest, v0.GetStatusResponse]
	watchEvents             *connect.Client[v0.WatchEventsRequest, v0.WatchEventsResponse]
	getOperation            *connect.Client[v0.GetOperationRequest, v0.GetOperationResponse]
	enroll                  *connect.Client[v0.EnrollRequest, v0.EnrollResponse]
	connect                 *connect.Client[v0.ConnectRequest, v0.ConnectResponse]
	disconnect              *connect.Client[v0.DisconnectRequest, v0.DisconnectResponse]
	getServerIdentity       *connect.Client[v0.GetServerIdentityRequest, v0.GetServerIdentityResponse]
	trustServerIdentity     *connect.Client[v0.TrustServerIdentityRequest, v0.TrustServerIdentityResponse]
	logout                  *connect.Client[v0.LogoutRequest, v0.LogoutResponse]
	forgetLocalEnrollment   *connect.Client[v0.ForgetLocalEnrollmentRequest, v0.ForgetLocalEnrollmentResponse]
	listNetworks            *connect.Client[v0.ListNetworksRequest, v0.ListNetworksResponse]
	selectNetwork           *connect.Client[v0.SelectNetworkRequest, v0.SelectNetworkResponse]
	listPeers               *connect.Client[v0.ListPeersRequest, v0.ListPeersResponse]
	getDiagnostics          *connect.Client[v0.GetDiagnosticsRequest, v0.GetDiagnosticsResponse]
	createDiagnosticsBundle *connect.Client[v0.CreateDiagnosticsBundleRequest, v0.CreateDiagnosticsBundleResponse]
	readDiagnosticsBundle   *connect.Client[v0.ReadDiagnosticsBundleRequest, v0.ReadDiagnosticsBundleResponse]
	listRecentLogs          *connect.Client[v0.ListRecentLogsRequest, v0.ListRecentLogsResponse]
	listProfiles            *connect.Client[v0.ListProfilesRequest, v0.ListProfilesResponse]
	createProfile           *connect.Client[v0.CreateProfileRequest, v0.CreateProfileResponse]
	selectProfile           *connect.Client[v0.SelectProfileRequest, v0.SelectProfileResponse]
	renameProfile           *connect.Client[v0.RenameProfileRequest, v0.RenameProfileResponse]
	removeProfile           *connect.Client[v0.RemoveProfileRequest, v0.RemoveProfileResponse]
	getSession              *connect.Client[v0.GetSessionRequest, v0.GetSessionResponse]
	renewSession            *connect.Client[v0.RenewSessionRequest, v0.RenewSessionResponse]
	listExitNodes           *connect.Client[v0.ListExitNodesRequest, v0.ListExitNodesResponse]
	getExitNode             *connect.Client[v0.GetExitNodeRequest, v0.GetExitNodeResponse]
	selectExitNode          *connect.Client[v0.SelectExitNodeRequest, v0.SelectExitNodeResponse]
	clearExitNode           *connect.Client[v0.ClearExitNodeRequest, v0.ClearExitNodeResponse]
	getPreferences          *connect.Client[v0.GetPreferencesRequest, v0.GetPreferencesResponse]
	setPreferences          *connect.Client[v0.SetPreferencesRequest, v0.SetPreferencesResponse]
	resetPreferences        *connect.Client[v0.ResetPreferencesRequest, v0.ResetPreferencesResponse]
	listManagedSettings     *connect.Client[v0.ListManagedSettingsRequest, v0.ListManagedSettingsResponse]
	listResources           *connect.Client[v0.ListResourcesRequest, v0.ListResourcesResponse]
	setResourceEnabled      *connect.Client[v0.SetResourceEnabledRequest, v0.SetResourceEnabledResponse]
	notifyLifecycle         *connect.Client[v0.NotifyLifecycleRequest, v0.NotifyLifecycleResponse]
	getUpdateInfo           *connect.Client[v0.GetUpdateInfoRequest, v0.GetUpdateInfoResponse]
	getSupportInfo          *connect.Client[v0.GetSupportInfoRequest, v0.GetSupportInfoResponse]
}

// GetRuntimeInfo calls client.v0.ClientService.GetRuntimeInfo.
func (c *clientServiceClient) GetRuntimeInfo(ctx context.Context, req *connect.Request[v0.GetRuntimeInfoRequest]) (*connect.Response[v0.GetRuntimeInfoResponse], error) {
	return c.getRuntimeInfo.CallUnary(ctx, req)
}

// GetStatus calls client.v0.ClientService.GetStatus.
func (c *clientServiceClient) GetStatus(ctx context.Context, req *connect.Request[v0.GetStatusRequest]) (*connect.Response[v0.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// WatchEvents calls client.v0.ClientService.WatchEvents.
func (c *clientServiceClient) WatchEvents(ctx context.Context, req *connect.Request[v0.WatchEventsRequest]) (*connect.ServerStreamForClient[v0.WatchEventsResponse], error) {
	return c.watchEvents.CallServerStream(ctx, req)
}

// GetOperation calls client.v0.ClientService.GetOperation.
func (c *clientServiceClient) GetOperation(ctx context.Context, req *connect.Request[v0.GetOperationRequest]) (*connect.Response[v0.GetOperationResponse], error) {
	return c.getOperation.CallUnary(ctx, req)
}

// Enroll calls client.v0.ClientService.Enroll.
func (c *clientServiceClient) Enroll(ctx context.Context, req *connect.Request[v0.EnrollRequest]) (*connect.Response[v0.EnrollResponse], error) {
	return c.enroll.CallUnary(ctx, req)
}

// Connect calls client.v0.ClientService.Connect.
func (c *clientServiceClient) Connect(ctx context.Context, req *connect.Request[v0.ConnectRequest]) (*connect.Response[v0.ConnectResponse], error) {
	return c.connect.CallUnary(ctx, req)
}

// Disconnect calls client.v0.ClientService.Disconnect.
func (c *clientServiceClient) Disconnect(ctx context.Context, req *connect.Request[v0.DisconnectRequest]) (*connect.Response[v0.DisconnectResponse], error) {
	return c.disconnect.CallUnary(ctx, req)
}

// GetServerIdentity calls client.v0.ClientService.GetServerIdentity.
func (c *clientServiceClient) GetServerIdentity(ctx context.Context, req *connect.Request[v0.GetServerIdentityRequest]) (*connect.Response[v0.GetServerIdentityResponse], error) {
	return c.getServerIdentity.CallUnary(ctx, req)
}

// TrustServerIdentity calls client.v0.ClientService.TrustServerIdentity.
func (c *clientServiceClient) TrustServerIdentity(ctx context.Context, req *connect.Request[v0.TrustServerIdentityRequest]) (*connect.Response[v0.TrustServerIdentityResponse], error) {
	return c.trustServerIdentity.CallUnary(ctx, req)
}

// Logout calls client.v0.ClientService.Logout.
func (c *clientServiceClient) Logout(ctx context.Context, req *connect.Request[v0.LogoutRequest]) (*connect.Response[v0.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// ForgetLocalEnrollment calls client.v0.ClientService.ForgetLocalEnrollment.
func (c *clientServiceClient) ForgetLocalEnrollment(ctx context.Context, req *connect.Request[v0.ForgetLocalEnrollmentRequest]) (*connect.Response[v0.ForgetLocalEnrollmentResponse], error) {
	return c.forgetLocalEnrollment.CallUnary(ctx, req)
}

// ListNetworks calls client.v0.ClientService.ListNetworks.
func (c *clientServiceClient) ListNetworks(ctx context.Context, req *connect.Request[v0.ListNetworksRequest]) (*connect.Response[v0.ListNetworksResponse], error) {
	return c.listNetworks.CallUnary(ctx, req)
}

// SelectNetwork calls client.v0.ClientService.SelectNetwork.
func (c *clientServiceClient) SelectNetwork(ctx context.Context, req *connect.Request[v0.SelectNetworkRequest]) (*connect.Response[v0.SelectNetworkResponse], error) {
	return c.selectNetwork.CallUnary(ctx, req)
}

// ListPeers calls client.v0.ClientService.ListPeers.
func (c *clientServiceClient) ListPeers(ctx context.Context, req *connect.Request[v0.ListPeersRequest]) (*connect.Response[v0.ListPeersResponse], error) {
	return c.listPeers.CallUnary(ctx, req)
}

// GetDiagnostics calls client.v0.ClientService.GetDiagnostics.
func (c *clientServiceClient) GetDiagnostics(ctx context.Context, req *connect.Request[v0.GetDiagnosticsRequest]) (*connect.Response[v0.GetDiagnosticsResponse], error) {
	return c.getDiagnostics.CallUnary(ctx, req)
}

// CreateDiagnosticsBundle calls client.v0.ClientService.CreateDiagnosticsBundle.
func (c *clientServiceClient) CreateDiagnosticsBundle(ctx context.Context, req *connect.Request[v0.CreateDiagnosticsBundleRequest]) (*connect.Response[v0.CreateDiagnosticsBundleResponse], error) {
	return c.createDiagnosticsBundle.CallUnary(ctx, req)
}

// ReadDiagnosticsBundle calls client.v0.ClientService.ReadDiagnosticsBundle.
func (c *clientServiceClient) ReadDiagnosticsBundle(ctx context.Context, req *connect.Request[v0.ReadDiagnosticsBundleRequest]) (*connect.Response[v0.ReadDiagnosticsBundleResponse], error) {
	return c.readDiagnosticsBundle.CallUnary(ctx, req)
}

// ListRecentLogs calls client.v0.ClientService.ListRecentLogs.
func (c *clientServiceClient) ListRecentLogs(ctx context.Context, req *connect.Request[v0.ListRecentLogsRequest]) (*connect.Response[v0.ListRecentLogsResponse], error) {
	return c.listRecentLogs.CallUnary(ctx, req)
}

// ListProfiles calls client.v0.ClientService.ListProfiles.
func (c *clientServiceClient) ListProfiles(ctx context.Context, req *connect.Request[v0.ListProfilesRequest]) (*connect.Response[v0.ListProfilesResponse], error) {
	return c.listProfiles.CallUnary(ctx, req)
}

// CreateProfile calls client.v0.ClientService.CreateProfile.
func (c *clientServiceClient) CreateProfile(ctx context.Context, req *connect.Request[v0.CreateProfileRequest]) (*connect.Response[v0.CreateProfileResponse], error) {
	return c.createProfile.CallUnary(ctx, req)
}

// SelectProfile calls client.v0.ClientService.SelectProfile.
func (c *clientServiceClient) SelectProfile(ctx context.Context, req *connect.Request[v0.SelectProfileRequest]) (*connect.Response[v0.SelectProfileResponse], error) {
	return c.selectProfile.CallUnary(ctx, req)
}

// RenameProfile calls client.v0.ClientService.RenameProfile.
func (c *clientServiceClient) RenameProfile(ctx context.Context, req *connect.Request[v0.RenameProfileRequest]) (*connect.Response[v0.RenameProfileResponse], error) {
	return c.renameProfile.CallUnary(ctx, req)
}

// RemoveProfile calls client.v0.ClientService.RemoveProfile.
func (c *clientServiceClient) RemoveProfile(ctx context.Context, req *connect.Request[v0.RemoveProfileRequest]) (*connect.Response[v0.RemoveProfileResponse], error) {
	return c.removeProfile.CallUnary(ctx, req)
}

// GetSession calls client.v0.ClientService.GetSession.
func (c *clientServiceClient) GetSession(ctx context.Context, req *connect.Request[v0.GetSessionRequest]) (*connect.Response[v0.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// RenewSession calls client.v0.ClientService.RenewSession.
func (c *clientServiceClient) RenewSession(ctx context.Context, req *connect.Request[v0.RenewSessionRequest]) (*connect.Response[v0.RenewSessionResponse], error) {
	return c.renewSession.CallUnary(ctx, req)
}

// ListExitNodes calls client.v0.ClientService.ListExitNodes.
func (c *clientServiceClient) ListExitNodes(ctx context.Context, req *connect.Request[v0.ListExitNodesRequest]) (*connect.Response[v0.ListExitNodesResponse], error) {
	return c.listExitNodes.CallUnary(ctx, req)
}

// GetExitNode calls client.v0.ClientService.GetExitNode.
func (c *clientServiceClient) GetExitNode(ctx context.Context, req *connect.Request[v0.GetExitNodeRequest]) (*connect.Response[v0.GetExitNodeResponse], error) {
	return c.getExitNode.CallUnary(ctx, req)
}

// SelectExitNode calls client.v0.ClientService.SelectExitNode.
func (c *clientServiceClient) SelectExitNode(ctx context.Context, req *connect.Request[v0.SelectExitNodeRequest]) (*connect.Response[v0.SelectExitNodeResponse], error) {
	return c.selectExitNode.CallUnary(ctx, req)
}

// ClearExitNode calls client.v0.ClientService.ClearExitNode.
func (c *clientServiceClient) ClearExitNode(ctx context.Context, req *connect.Request[v0.ClearExitNodeRequest]) (*connect.Response[v0.ClearExitNodeResponse], error) {
	return c.clearExitNode.CallUnary(ctx, req)
}

// GetPreferences calls client.v0.ClientService.GetPreferences.
func (c *clientServiceClient) GetPreferences(ctx context.Context, req *connect.Request[v0.GetPreferencesRequest]) (*connect.Response[v0.GetPreferencesResponse], error) {
	return c.getPreferences.CallUnary(ctx, req)
}

// SetPreferences calls client.v0.ClientService.SetPreferences.
func (c *clientServiceClient) SetPreferences(ctx context.Context, req *connect.Request[v0.SetPreferencesRequest]) (*connect.Response[v0.SetPreferencesResponse], error) {
	return c.setPreferences.CallUnary(ctx, req)
}

// ResetPreferences calls client.v0.ClientService.ResetPreferences.
func (c *clientServiceClient) ResetPreferences(ctx context.Context, req *connect.Request[v0.ResetPreferencesRequest]) (*connect.Response[v0.ResetPreferencesResponse], error) {
	return c.resetPreferences.CallUnary(ctx, req)
}

// ListManagedSettings calls client.v0.ClientService.ListManagedSettings.
func (c *clientServiceClient) ListManagedSettings(ctx context.Context, req *connect.Request[v0.ListManagedSettingsRequest]) (*connect.Response[v0.ListManagedSettingsResponse], error) {
	return c.listManagedSettings.CallUnary(ctx, req)
}

// ListResources calls client.v0.ClientService.ListResources.
func (c *clientServiceClient) ListResources(ctx context.Context, req *connect.Request[v0.ListResourcesRequest]) (*connect.Response[v0.ListResourcesResponse], error) {
	return c.listResources.CallUnary(ctx, req)
}

// SetResourceEnabled calls client.v0.ClientService.SetResourceEnabled.
func (c *clientServiceClient) SetResourceEnabled(ctx context.Context, req *connect.Request[v0.SetResourceEnabledRequest]) (*connect.Response[v0.SetResourceEnabledResponse], error) {
	return c.setResourceEnabled.CallUnary(ctx, req)
}

// NotifyLifecycle calls client.v0.ClientService.NotifyLifecycle.
func (c *clientServiceClient) NotifyLifecycle(ctx context.Context, req *connect.Request[v0.NotifyLifecycleRequest]) (*connect.Response[v0.NotifyLifecycleResponse], error) {
	return c.notifyLifecycle.CallUnary(ctx, req)
}

// GetUpdateInfo calls client.v0.ClientService.GetUpdateInfo.
func (c *clientServiceClient) GetUpdateInfo(ctx context.Context, req *connect.Request[v0.GetUpdateInfoRequest]) (*connect.Response[v0.GetUpdateInfoResponse], error) {
	return c.getUpdateInfo.CallUnary(ctx, req)
}

// GetSupportInfo calls client.v0.ClientService.GetSupportInfo.
func (c *clientServiceClient) GetSupportInfo(ctx context.Context, req *connect.Request[v0.GetSupportInfoRequest]) (*connect.Response[v0.GetSupportInfoResponse], error) {
	return c.getSupportInfo.CallUnary(ctx, req)
}

// ClientServiceHandler is an implementation of the client.v0.ClientService service.
type ClientServiceHandler interface {
	// UF-04, UF-20, UF-22, UF-23: installed identity and caller-filtered capabilities.
	GetRuntimeInfo(context.Context, *connect.Request[v0.GetRuntimeInfoRequest]) (*connect.Response[v0.GetRuntimeInfoResponse], error)
	// UF-04, UF-09: authoritative active-context snapshot.
	GetStatus(context.Context, *connect.Request[v0.GetStatusRequest]) (*connect.Response[v0.GetStatusResponse], error)
	// UF-04, UF-09, UF-15: snapshot first, then typed changes; no replay cursor.
	WatchEvents(context.Context, *connect.Request[v0.WatchEventsRequest], *connect.ServerStream[v0.WatchEventsResponse]) error
	// Read a caller-owned operation after timeout or reconnection.
	GetOperation(context.Context, *connect.Request[v0.GetOperationRequest]) (*connect.Response[v0.GetOperationResponse], error)
	// UF-03: initial unowned installation uses the ownership-claim exception.
	Enroll(context.Context, *connect.Request[v0.EnrollRequest]) (*connect.Response[v0.EnrollResponse], error)
	// UF-05: persist connected intent, then reconcile runtime.
	Connect(context.Context, *connect.Request[v0.ConnectRequest]) (*connect.Response[v0.ConnectResponse], error)
	// UF-05: persist disconnected intent; retain registration.
	Disconnect(context.Context, *connect.Request[v0.DisconnectRequest]) (*connect.Response[v0.DisconnectResponse], error)
	// UF-10: review announced and trusted identity for a profile.
	GetServerIdentity(context.Context, *connect.Request[v0.GetServerIdentityRequest]) (*connect.Response[v0.GetServerIdentityResponse], error)
	// UF-10: fixed-purpose privileged operation, matching the current announcement.
	TrustServerIdentity(context.Context, *connect.Request[v0.TrustServerIdentityRequest]) (*connect.Response[v0.TrustServerIdentityResponse], error)
	// UF-12: remote confirmation is required before deleting local registration.
	Logout(context.Context, *connect.Request[v0.LogoutRequest]) (*connect.Response[v0.LogoutResponse], error)
	// UF-12: explicit local-only cleanup; never claims remote revocation.
	ForgetLocalEnrollment(context.Context, *connect.Request[v0.ForgetLocalEnrollmentRequest]) (*connect.Response[v0.ForgetLocalEnrollmentResponse], error)
	// UF-07: only already granted networks for this profile.
	ListNetworks(context.Context, *connect.Request[v0.ListNetworksRequest]) (*connect.Response[v0.ListNetworksResponse], error)
	// UF-07: select an enrolled network by stable ID.
	SelectNetwork(context.Context, *connect.Request[v0.SelectNetworkRequest]) (*connect.Response[v0.SelectNetworkResponse], error)
	// UF-06, UF-19: filtered peer search and path inspection.
	ListPeers(context.Context, *connect.Request[v0.ListPeersRequest]) (*connect.Response[v0.ListPeersResponse], error)
	// UF-11: bounded producer-redacted snapshot.
	GetDiagnostics(context.Context, *connect.Request[v0.GetDiagnosticsRequest]) (*connect.Response[v0.GetDiagnosticsResponse], error)
	// UF-11: local-only redacted archive, no upload or packet capture.
	CreateDiagnosticsBundle(context.Context, *connect.Request[v0.CreateDiagnosticsBundleRequest]) (*connect.Response[v0.CreateDiagnosticsBundleResponse], error)
	// UF-11: caller-bound handle; bounded chunks, no filesystem path input.
	ReadDiagnosticsBundle(context.Context, *connect.Request[v0.ReadDiagnosticsBundleRequest]) (*connect.Response[v0.ReadDiagnosticsBundleResponse], error)
	// UF-11: bounded redacted log entries.
	ListRecentLogs(context.Context, *connect.Request[v0.ListRecentLogsRequest]) (*connect.Response[v0.ListRecentLogsResponse], error)
	// UF-16: local owner profiles, one active at most.
	ListProfiles(context.Context, *connect.Request[v0.ListProfilesRequest]) (*connect.Response[v0.ListProfilesResponse], error)
	// UF-16: create empty context; enrollment is a separate explicit action.
	CreateProfile(context.Context, *connect.Request[v0.CreateProfileRequest]) (*connect.Response[v0.CreateProfileResponse], error)
	// UF-16: atomic context switch, report actual connection interruption.
	SelectProfile(context.Context, *connect.Request[v0.SelectProfileRequest]) (*connect.Response[v0.SelectProfileResponse], error)
	// UF-16: change display name only; identity and origin are immutable.
	RenameProfile(context.Context, *connect.Request[v0.RenameProfileRequest]) (*connect.Response[v0.RenameProfileResponse], error)
	// UF-16: only inactive profiles with no remaining registration/session.
	RemoveProfile(context.Context, *connect.Request[v0.RemoveProfileRequest]) (*connect.Response[v0.RemoveProfileResponse], error)
	// UF-17: expiry, warning deadline and renewal availability.
	GetSession(context.Context, *connect.Request[v0.GetSessionRequest]) (*connect.Response[v0.GetSessionResponse], error)
	// UF-17: no caller-supplied callback URL or browser credential.
	RenewSession(context.Context, *connect.Request[v0.RenewSessionRequest]) (*connect.Response[v0.RenewSessionResponse], error)
	// UF-08: list authorized consumer-side egress choices.
	ListExitNodes(context.Context, *connect.Request[v0.ListExitNodesRequest]) (*connect.Response[v0.ListExitNodesResponse], error)
	// UF-08: requested/effective selection, LAN policy and apply outcome.
	GetExitNode(context.Context, *connect.Request[v0.GetExitNodeRequest]) (*connect.Response[v0.GetExitNodeResponse], error)
	// UF-08: only an authorized catalog ID; never arbitrary routes.
	SelectExitNode(context.Context, *connect.Request[v0.SelectExitNodeRequest]) (*connect.Response[v0.SelectExitNodeResponse], error)
	// UF-08: explicit removal of consumer-side egress selection.
	ClearExitNode(context.Context, *connect.Request[v0.ClearExitNodeRequest]) (*connect.Response[v0.ClearExitNodeResponse], error)
	// UF-18, UF-21: effective values, user overrides and locks.
	GetPreferences(context.Context, *connect.Request[v0.GetPreferencesRequest]) (*connect.Response[v0.GetPreferencesResponse], error)
	// UF-18, UF-21: nonempty typed patch, all-or-nothing validation.
	SetPreferences(context.Context, *connect.Request[v0.SetPreferencesRequest]) (*connect.Response[v0.SetPreferencesResponse], error)
	// UF-18, UF-21: remove named user overrides; managed values remain.
	ResetPreferences(context.Context, *connect.Request[v0.ResetPreferencesRequest]) (*connect.Response[v0.ResetPreferencesResponse], error)
	// UF-20: read-only effective runtime policy and next-action owner.
	ListManagedSettings(context.Context, *connect.Request[v0.ListManagedSettingsRequest]) (*connect.Response[v0.ListManagedSettingsResponse], error)
	// UF-19: granted catalog, availability, overlaps and local selection.
	ListResources(context.Context, *connect.Request[v0.ListResourcesRequest]) (*connect.Response[v0.ListResourcesResponse], error)
	// UF-19: local subset selection cannot expand backend authorization.
	SetResourceEnabled(context.Context, *connect.Request[v0.SetResourceEnabledRequest]) (*connect.Response[v0.SetResourceEnabledResponse], error)
	// UF-21: explicit graceful UI quit only; OS lifecycle comes from runtime adapters.
	NotifyLifecycle(context.Context, *connect.Request[v0.NotifyLifecycleRequest]) (*connect.Response[v0.NotifyLifecycleResponse], error)
	// UF-22: verified distribution projection and installed-pair compatibility.
	GetUpdateInfo(context.Context, *connect.Request[v0.GetUpdateInfoRequest]) (*connect.Response[v0.GetUpdateInfoResponse], error)
	// UF-23: validated product links and offline-help key.
	GetSupportInfo(context.Context, *connect.Request[v0.GetSupportInfoRequest]) (*connect.Response[v0.GetSupportInfoResponse], error)
}

// NewClientServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewClientServiceHandler(svc ClientServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	clientServiceMethods := v0.File_client_v0_service_proto.Services().ByName("ClientService").Methods()
	clientServiceGetRuntimeInfoHandler := connect.NewUnaryHandler(
		ClientServiceGetRuntimeInfoProcedure,
		svc.GetRuntimeInfo,
		connect.WithSchema(clientServiceMethods.ByName("GetRuntimeInfo")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceGetStatusHandler := connect.NewUnaryHandler(
		ClientServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(clientServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceWatchEventsHandler := connect.NewServerStreamHandler(
		ClientServiceWatchEventsProcedure,
		svc.WatchEvents,
		connect.WithSchema(clientServiceMethods.ByName("WatchEvents")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceGetOperationHandler := connect.NewUnaryHandler(
		ClientServiceGetOperationProcedure,
		svc.GetOperation,
		connect.WithSchema(clientServiceMethods.ByName("GetOperation")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceEnrollHandler := connect.NewUnaryHandler(
		ClientServiceEnrollProcedure,
		svc.Enroll,
		connect.WithSchema(clientServiceMethods.ByName("Enroll")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceConnectHandler := connect.NewUnaryHandler(
		ClientServiceConnectProcedure,
		svc.Connect,
		connect.WithSchema(clientServiceMethods.ByName("Connect")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceDisconnectHandler := connect.NewUnaryHandler(
		ClientServiceDisconnectProcedure,
		svc.Disconnect,
		connect.WithSchema(clientServiceMethods.ByName("Disconnect")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceGetServerIdentityHandler := connect.NewUnaryHandler(
		ClientServiceGetServerIdentityProcedure,
		svc.GetServerIdentity,
		connect.WithSchema(clientServiceMethods.ByName("GetServerIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceTrustServerIdentityHandler := connect.NewUnaryHandler(
		ClientServiceTrustServerIdentityProcedure,
		svc.TrustServerIdentity,
		connect.WithSchema(clientServiceMethods.ByName("TrustServerIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceLogoutHandler := connect.NewUnaryHandler(
		ClientServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(clientServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceForgetLocalEnrollmentHandler := connect.NewUnaryHandler(
		ClientServiceForgetLocalEnrollmentProcedure,
		svc.ForgetLocalEnrollment,
		connect.WithSchema(clientServiceMethods.ByName("ForgetLocalEnrollment")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceListNetworksHandler := connect.NewUnaryHandler(
		ClientServiceListNetworksProcedure,
		svc.ListNetworks,
		connect.WithSchema(clientServiceMethods.ByName("ListNetworks")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceSelectNetworkHandler := connect.NewUnaryHandler(
		ClientServiceSelectNetworkProcedure,
		svc.SelectNetwork,
		connect.WithSchema(clientServiceMethods.ByName("SelectNetwork")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceListPeersHandler := connect.NewUnaryHandler(
		ClientServiceListPeersProcedure,
		svc.ListPeers,
		connect.WithSchema(clientServiceMethods.ByName("ListPeers")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceGetDiagnosticsHandler := connect.NewUnaryHandler(
		ClientServiceGetDiagnosticsProcedure,
		svc.GetDiagnostics,
		connect.WithSchema(clientServiceMethods.ByName("GetDiagnostics")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceCreateDiagnosticsBundleHandler := connect.NewUnaryHandler(
		ClientServiceCreateDiagnosticsBundleProcedure,
		svc.CreateDiagnosticsBundle,
		connect.WithSchema(clientServiceMethods.ByName("CreateDiagnosticsBundle")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceReadDiagnosticsBundleHandler := connect.NewUnaryHandler(
		ClientServiceReadDiagnosticsBundleProcedure,
		svc.ReadDiagnosticsBundle,
		connect.WithSchema(clientServiceMethods.ByName("ReadDiagnosticsBundle")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceListRecentLogsHandler := connect.NewUnaryHandler(
		ClientServiceListRecentLogsProcedure,
		svc.ListRecentLogs,
		connect.WithSchema(clientServiceMethods.ByName("ListRecentLogs")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceListProfilesHandler := connect.NewUnaryHandler(
		ClientServiceListProfilesProcedure,
		svc.ListProfiles,
		connect.WithSchema(clientServiceMethods.ByName("ListProfiles")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceCreateProfileHandler := connect.NewUnaryHandler(
		ClientServiceCreateProfileProcedure,
		svc.CreateProfile,
		connect.WithSchema(clientServiceMethods.ByName("CreateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceSelectProfileHandler := connect.NewUnaryHandler(
		ClientServiceSelectProfileProcedure,
		svc.SelectProfile,
		connect.WithSchema(clientServiceMethods.ByName("SelectProfile")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceRenameProfileHandler := connect.NewUnaryHandler(
		ClientServiceRenameProfileProcedure,
		svc.RenameProfile,
		connect.WithSchema(clientServiceMethods.ByName("RenameProfile")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceRemoveProfileHandler := connect.NewUnaryHandler(
		ClientServiceRemoveProfileProcedure,
		svc.RemoveProfile,
		connect.WithSchema(clientServiceMethods.ByName("RemoveProfile")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceGetSessionHandler := connect.NewUnaryHandler(
		ClientServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(clientServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceRenewSessionHandler := connect.NewUnaryHandler(
		ClientServiceRenewSessionProcedure,
		svc.RenewSession,
		connect.WithSchema(clientServiceMethods.ByName("RenewSession")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceListExitNodesHandler := connect.NewUnaryHandler(
		ClientServiceListExitNodesProcedure,
		svc.ListExitNodes,
		connect.WithSchema(clientServiceMethods.ByName("ListExitNodes")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceGetExitNodeHandler := connect.NewUnaryHandler(
		ClientServiceGetExitNodeProcedure,
		svc.GetExitNode,
		connect.WithSchema(clientServiceMethods.ByName("GetExitNode")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceSelectExitNodeHandler := connect.NewUnaryHandler(
		ClientServiceSelectExitNodeProcedure,
		svc.SelectExitNode,
		connect.WithSchema(clientServiceMethods.ByName("SelectExitNode")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceClearExitNodeHandler := connect.NewUnaryHandler(
		ClientServiceClearExitNodeProcedure,
		svc.ClearExitNode,
		connect.WithSchema(clientServiceMethods.ByName("ClearExitNode")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceGetPreferencesHandler := connect.NewUnaryHandler(
		ClientServiceGetPreferencesProcedure,
		svc.GetPreferences,
		connect.WithSchema(clientServiceMethods.ByName("GetPreferences")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceSetPreferencesHandler := connect.NewUnaryHandler(
		ClientServiceSetPreferencesProcedure,
		svc.SetPreferences,
		connect.WithSchema(clientServiceMethods.ByName("SetPreferences")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceResetPreferencesHandler := connect.NewUnaryHandler(
		ClientServiceResetPreferencesProcedure,
		svc.ResetPreferences,
		connect.WithSchema(clientServiceMethods.ByName("ResetPreferences")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceListManagedSettingsHandler := connect.NewUnaryHandler(
		ClientServiceListManagedSettingsProcedure,
		svc.ListManagedSettings,
		connect.WithSchema(clientServiceMethods.ByName("ListManagedSettings")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceListResourcesHandler := connect.NewUnaryHandler(
		ClientServiceListResourcesProcedure,
		svc.ListResources,
		connect.WithSchema(clientServiceMethods.ByName("ListResources")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceSetResourceEnabledHandler := connect.NewUnaryHandler(
		ClientServiceSetResourceEnabledProcedure,
		svc.SetResourceEnabled,
		connect.WithSchema(clientServiceMethods.ByName("SetResourceEnabled")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceNotifyLifecycleHandler := connect.NewUnaryHandler(
		ClientServiceNotifyLifecycleProcedure,
		svc.NotifyLifecycle,
		connect.WithSchema(clientServiceMethods.ByName("NotifyLifecycle")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceGetUpdateInfoHandler := connect.NewUnaryHandler(
		ClientServiceGetUpdateInfoProcedure,
		svc.GetUpdateInfo,
		connect.WithSchema(clientServiceMethods.ByName("GetUpdateInfo")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceGetSupportInfoHandler := connect.NewUnaryHandler(
		ClientServiceGetSupportInfoProcedure,
		svc.GetSupportInfo,
		connect.WithSchema(clientServiceMethods.ByName("GetSupportInfo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/client.v0.ClientService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ClientServiceGetRuntimeInfoProcedure:
			clientServiceGetRuntimeInfoHandler.ServeHTTP(w, r)
		case ClientServiceGetStatusProcedure:
			clientServiceGetStatusHandler.ServeHTTP(w, r)
		case ClientServiceWatchEventsProcedure:
			clientServiceWatchEventsHandler.ServeHTTP(w, r)
		case ClientServiceGetOperationProcedure:
			clientServiceGetOperationHandler.ServeHTTP(w, r)
		case ClientServiceEnrollProcedure:
			clientServiceEnrollHandler.ServeHTTP(w, r)
		case ClientServiceConnectProcedure:
			clientServiceConnectHandler.ServeHTTP(w, r)
		case ClientServiceDisconnectProcedure:
			clientServiceDisconnectHandler.ServeHTTP(w, r)
		case ClientServiceGetServerIdentityProcedure:
			clientServiceGetServerIdentityHandler.ServeHTTP(w, r)
		case ClientServiceTrustServerIdentityProcedure:
			clientServiceTrustServerIdentityHandler.ServeHTTP(w, r)
		case ClientServiceLogoutProcedure:
			clientServiceLogoutHandler.ServeHTTP(w, r)
		case ClientServiceForgetLocalEnrollmentProcedure:
			clientServiceForgetLocalEnrollmentHandler.ServeHTTP(w, r)
		case ClientServiceListNetworksProcedure:
			clientServiceListNetworksHandler.ServeHTTP(w, r)
		case ClientServiceSelectNetworkProcedure:
			clientServiceSelectNetworkHandler.ServeHTTP(w, r)
		case ClientServiceListPeersProcedure:
			clientServiceListPeersHandler.ServeHTTP(w, r)
		case ClientServiceGetDiagnosticsProcedure:
			clientServiceGetDiagnosticsHandler.ServeHTTP(w, r)
		case ClientServiceCreateDiagnosticsBundleProcedure:
			clientServiceCreateDiagnosticsBundleHandler.ServeHTTP(w, r)
		case ClientServiceReadDiagnosticsBundleProcedure:
			clientServiceReadDiagnosticsBundleHandler.ServeHTTP(w, r)
		case ClientServiceListRecentLogsProcedure:
			clientServiceListRecentLogsHandler.ServeHTTP(w, r)
		case ClientServiceListProfilesProcedure:
			clientServiceListProfilesHandler.ServeHTTP(w, r)
		case ClientServiceCreateProfileProcedure:
			clientServiceCreateProfileHandler.ServeHTTP(w, r)
		case ClientServiceSelectProfileProcedure:
			clientServiceSelectProfileHandler.ServeHTTP(w, r)
		case ClientServiceRenameProfileProcedure:
			clientServiceRenameProfileHandler.ServeHTTP(w, r)
		case ClientServiceRemoveProfileProcedure:
			clientServiceRemoveProfileHandler.ServeHTTP(w, r)
		case ClientServiceGetSessionProcedure:
			clientServiceGetSessionHandler.ServeHTTP(w, r)
		case ClientServiceRenewSessionProcedure:
			clientServiceRenewSessionHandler.ServeHTTP(w, r)
		case ClientServiceListExitNodesProcedure:
			clientServiceListExitNodesHandler.ServeHTTP(w, r)
		case ClientServiceGetExitNodeProcedure:
			clientServiceGetExitNodeHandler.ServeHTTP(w, r)
		case ClientServiceSelectExitNodeProcedure:
			clientServiceSelectExitNodeHandler.ServeHTTP(w, r)
		case ClientServiceClearExitNodeProcedure:
			clientServiceClearExitNodeHandler.ServeHTTP(w, r)
		case ClientServiceGetPreferencesProcedure:
			clientServiceGetPreferencesHandler.ServeHTTP(w, r)
		case ClientServiceSetPreferencesProcedure:
			clientServiceSetPreferencesHandler.ServeHTTP(w, r)
		case ClientServiceResetPreferencesProcedure:
			clientServiceResetPreferencesHandler.ServeHTTP(w, r)
		case ClientServiceListManagedSettingsProcedure:
			clientServiceListManagedSettingsHandler.ServeHTTP(w, r)
		case ClientServiceListResourcesProcedure:
			clientServiceListResourcesHandler.ServeHTTP(w, r)
		case ClientServiceSetResourceEnabledProcedure:
			clientServiceSetResourceEnabledHandler.ServeHTTP(w, r)
		case ClientServiceNotifyLifecycleProcedure:
			clientServiceNotifyLifecycleHandler.ServeHTTP(w, r)
		case ClientServiceGetUpdateInfoProcedure:
			clientServiceGetUpdateInfoHandler.ServeHTTP(w, r)
		case ClientServiceGetSupportInfoProcedure:
			clientServiceGetSupportInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedClientServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedClientServiceHandler struct{}

func (UnimplementedClientServiceHandler) GetRuntimeInfo(context.Context, *connect.Request[v0.GetRuntimeInfoRequest]) (*connect.Response[v0.GetRuntimeInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.GetRuntimeInfo is not implemented"))
}

func (UnimplementedClientServiceHandler) GetStatus(context.Context, *connect.Request[v0.GetStatusRequest]) (*connect.Response[v0.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.GetStatus is not implemented"))
}

func (UnimplementedClientServiceHandler) WatchEvents(context.Context, *connect.Request[v0.WatchEventsRequest], *connect.ServerStream[v0.WatchEventsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.WatchEvents is not implemented"))
}

func (UnimplementedClientServiceHandler) GetOperation(context.Context, *connect.Request[v0.GetOperationRequest]) (*connect.Response[v0.GetOperationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.GetOperation is not implemented"))
}

func (UnimplementedClientServiceHandler) Enroll(context.Context, *connect.Request[v0.EnrollRequest]) (*connect.Response[v0.EnrollResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.Enroll is not implemented"))
}

func (UnimplementedClientServiceHandler) Connect(context.Context, *connect.Request[v0.ConnectRequest]) (*connect.Response[v0.ConnectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.Connect is not implemented"))
}

func (UnimplementedClientServiceHandler) Disconnect(context.Context, *connect.Request[v0.DisconnectRequest]) (*connect.Response[v0.DisconnectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.Disconnect is not implemented"))
}

func (UnimplementedClientServiceHandler) GetServerIdentity(context.Context, *connect.Request[v0.GetServerIdentityRequest]) (*connect.Response[v0.GetServerIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.GetServerIdentity is not implemented"))
}

func (UnimplementedClientServiceHandler) TrustServerIdentity(context.Context, *connect.Request[v0.TrustServerIdentityRequest]) (*connect.Response[v0.TrustServerIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.TrustServerIdentity is not implemented"))
}

func (UnimplementedClientServiceHandler) Logout(context.Context, *connect.Request[v0.LogoutRequest]) (*connect.Response[v0.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.Logout is not implemented"))
}

func (UnimplementedClientServiceHandler) ForgetLocalEnrollment(context.Context, *connect.Request[v0.ForgetLocalEnrollmentRequest]) (*connect.Response[v0.ForgetLocalEnrollmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ForgetLocalEnrollment is not implemented"))
}

func (UnimplementedClientServiceHandler) ListNetworks(context.Context, *connect.Request[v0.ListNetworksRequest]) (*connect.Response[v0.ListNetworksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ListNetworks is not implemented"))
}

func (UnimplementedClientServiceHandler) SelectNetwork(context.Context, *connect.Request[v0.SelectNetworkRequest]) (*connect.Response[v0.SelectNetworkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.SelectNetwork is not implemented"))
}

func (UnimplementedClientServiceHandler) ListPeers(context.Context, *connect.Request[v0.ListPeersRequest]) (*connect.Response[v0.ListPeersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ListPeers is not implemented"))
}

func (UnimplementedClientServiceHandler) GetDiagnostics(context.Context, *connect.Request[v0.GetDiagnosticsRequest]) (*connect.Response[v0.GetDiagnosticsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.GetDiagnostics is not implemented"))
}

func (UnimplementedClientServiceHandler) CreateDiagnosticsBundle(context.Context, *connect.Request[v0.CreateDiagnosticsBundleRequest]) (*connect.Response[v0.CreateDiagnosticsBundleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.CreateDiagnosticsBundle is not implemented"))
}

func (UnimplementedClientServiceHandler) ReadDiagnosticsBundle(context.Context, *connect.Request[v0.ReadDiagnosticsBundleRequest]) (*connect.Response[v0.ReadDiagnosticsBundleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ReadDiagnosticsBundle is not implemented"))
}

func (UnimplementedClientServiceHandler) ListRecentLogs(context.Context, *connect.Request[v0.ListRecentLogsRequest]) (*connect.Response[v0.ListRecentLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ListRecentLogs is not implemented"))
}

func (UnimplementedClientServiceHandler) ListProfiles(context.Context, *connect.Request[v0.ListProfilesRequest]) (*connect.Response[v0.ListProfilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ListProfiles is not implemented"))
}

func (UnimplementedClientServiceHandler) CreateProfile(context.Context, *connect.Request[v0.CreateProfileRequest]) (*connect.Response[v0.CreateProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.CreateProfile is not implemented"))
}

func (UnimplementedClientServiceHandler) SelectProfile(context.Context, *connect.Request[v0.SelectProfileRequest]) (*connect.Response[v0.SelectProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.SelectProfile is not implemented"))
}

func (UnimplementedClientServiceHandler) RenameProfile(context.Context, *connect.Request[v0.RenameProfileRequest]) (*connect.Response[v0.RenameProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.RenameProfile is not implemented"))
}

func (UnimplementedClientServiceHandler) RemoveProfile(context.Context, *connect.Request[v0.RemoveProfileRequest]) (*connect.Response[v0.RemoveProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.RemoveProfile is not implemented"))
}

func (UnimplementedClientServiceHandler) GetSession(context.Context, *connect.Request[v0.GetSessionRequest]) (*connect.Response[v0.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.GetSession is not implemented"))
}

func (UnimplementedClientServiceHandler) RenewSession(context.Context, *connect.Request[v0.RenewSessionRequest]) (*connect.Response[v0.RenewSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.RenewSession is not implemented"))
}

func (UnimplementedClientServiceHandler) ListExitNodes(context.Context, *connect.Request[v0.ListExitNodesRequest]) (*connect.Response[v0.ListExitNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ListExitNodes is not implemented"))
}

func (UnimplementedClientServiceHandler) GetExitNode(context.Context, *connect.Request[v0.GetExitNodeRequest]) (*connect.Response[v0.GetExitNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.GetExitNode is not implemented"))
}

func (UnimplementedClientServiceHandler) SelectExitNode(context.Context, *connect.Request[v0.SelectExitNodeRequest]) (*connect.Response[v0.SelectExitNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.SelectExitNode is not implemented"))
}

func (UnimplementedClientServiceHandler) ClearExitNode(context.Context, *connect.Request[v0.ClearExitNodeRequest]) (*connect.Response[v0.ClearExitNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ClearExitNode is not implemented"))
}

func (UnimplementedClientServiceHandler) GetPreferences(context.Context, *connect.Request[v0.GetPreferencesRequest]) (*connect.Response[v0.GetPreferencesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.GetPreferences is not implemented"))
}

func (UnimplementedClientServiceHandler) SetPreferences(context.Context, *connect.Request[v0.SetPreferencesRequest]) (*connect.Response[v0.SetPreferencesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.SetPreferences is not implemented"))
}

func (UnimplementedClientServiceHandler) ResetPreferences(context.Context, *connect.Request[v0.ResetPreferencesRequest]) (*connect.Response[v0.ResetPreferencesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ResetPreferences is not implemented"))
}

func (UnimplementedClientServiceHandler) ListManagedSettings(context.Context, *connect.Request[v0.ListManagedSettingsRequest]) (*connect.Response[v0.ListManagedSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ListManagedSettings is not implemented"))
}

func (UnimplementedClientServiceHandler) ListResources(context.Context, *connect.Request[v0.ListResourcesRequest]) (*connect.Response[v0.ListResourcesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.ListResources is not implemented"))
}

func (UnimplementedClientServiceHandler) SetResourceEnabled(context.Context, *connect.Request[v0.SetResourceEnabledRequest]) (*connect.Response[v0.SetResourceEnabledResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.SetResourceEnabled is not implemented"))
}

func (UnimplementedClientServiceHandler) NotifyLifecycle(context.Context, *connect.Request[v0.NotifyLifecycleRequest]) (*connect.Response[v0.NotifyLifecycleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.NotifyLifecycle is not implemented"))
}

func (UnimplementedClientServiceHandler) GetUpdateInfo(context.Context, *connect.Request[v0.GetUpdateInfoRequest]) (*connect.Response[v0.GetUpdateInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.GetUpdateInfo is not implemented"))
}

func (UnimplementedClientServiceHandler) GetSupportInfo(context.Context, *connect.Request[v0.GetSupportInfoRequest]) (*connect.Response[v0.GetSupportInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("client.v0.ClientService.GetSupportInfo is not implemented"))
}
